### ISSUE TITLE
Dependency to "typo3-ter/autoloader" inside composer.json don't work in TYPO3 6.2

### ISSUE THREAD

**Issue by rabe69** [lochmueller/calendarize#11]
Because of this:
 
"require": {
    "typo3-ter/autoloader": "~1.6"
  }

inside composer.json I can not install calendarize using new installation method of TYPO3 using composer.

The package "typo3-ter/autoloader" will not be found.

Removing helps, but maybe (I'm not sure) it also works, if you add the TYPO3-Composer-Repository in a repository section:

"repositories": [
	{
		"type": "composer",
		"url": "http://composer.typo3.org/"
	}
]
 
EDIT: I had a conversation with helhum on slack about this problem. May be it's a bug comes from TYPO3/Composer-Repository-Server.. Stay tuned

EDIT2: helhum mean it's better (at the moment) to remove dependencies (require-section) inside composer.json or whole composer.json, before it is fixed inside TYPO3

**Comment by kaizwier** [comment]
This bugfix doesn't work for me with Typo3 version 7.3.1. Any further ideas?

**Comment by lochmueller** [comment]
Hey @kaizwier 
can you describe the problem? I have no problems to install autoloader and calendarize, if I remove the dependencies? Do you gat any error message?

Regards,
Tim

**Comment by lochmueller** [comment]
I dropped the composer.json, because it is not possible to define dependencies to extensions.... and the extensino require the autoloader extension?!?! Ticket closed!
