### ISSUE TITLE
weekly event with one exclude date

### ISSUE THREAD

**Issue by charly83** [lochmueller/calendarize#111]
Hello!

When I create a periodical weekly event with one exclude date, I can't edit this event.
The following error message is displayed:
> Type value timeExclude from database record not defined in TCA of table tx_calendarize_domain_model_configuration and neither 0 nor 1 are defined as fallback.

**Comment by lochmueller** [comment]
Hey @charly83 , I think you update the calendarize shortly and do not run the Upgrade-Wizard in the Install-Tool? There are no "timeExclude" records anymore....

**Comment by charly83** [comment]
This was also my first idea, but this don't solve this issue.

Currently I have changed it in the database.

**Comment by lochmueller** [comment]
With the current version (after you execute the upgrade assistent), the type value should only be "time", "group" or "external". Furthermore there is a handling field that should be "include", "exclude" or "override". Please check this... Perhaps you find a bug in the migration assistent of the upgrade wizard. But I need same more information....

**Comment by charly83** [comment]
The type of the faulty record is "timeExclude". The handling field is "NULL"

I think the migration assistant don't work at my system (typo3 7.6.11).

**Comment by lochmueller** [comment]
Good point. We should change the check to 'handling="" OR handling IS NULL' ( https://github.com/lochmueller/calendarize/blob/master/Classes/Updates/NewIncludeExcludeStructureUpdate.php#L38 ) and drop the check of the type. Perhaps this is the problem (related to your MySQL version). I will check this in the next days and release a new version...
