### ISSUE TITLE
Enddate in month view is wrong (fullcalendar)

### ISSUE THREAD

**Issue by netthinks** [lochmueller/calendarize#116]
When I'm using fullcalendar in month view, the last day is not shown in calendar:
![25-11-_2016_09-22-12](https://cloud.githubusercontent.com/assets/23073131/20618764/2b31fb3e-b2f1-11e6-9495-be1301014f18.jpg)

TYPO3 7.6, calendarize 2.6.1

**Comment by lochmueller** [comment]
I debug the problem... I think it is a Fullcalendar IO bug. I updated the framework to 3.0.1, fix also the weekStart settings and a allDay bug: https://github.com/lochmueller/calendarize/commit/bf230ef7caa02b7f6fcc951bd161152c8c7a6a31
But no result. Any news @netthinks ? Do you create a bugreport for Fullcalendar IO also?

**Comment by netthinks** [comment]
ok, updated to 2.7.0, but now I've got a new error:
Fatal error: Class 'HDNET\Calendarize\ViewHelpers\DateTime\DateTimeUtility' not found in /html/typo3/typo3conf/ext/calendarize/Classes/ViewHelpers/DateTime/IndexOnDayViewHelper.php on line 34

**Comment by lochmueller** [comment]
Already fixed in current master: https://github.com/lochmueller/calendarize/commit/64e77f77e0f864b5135460a69989c7075d19c6d3

**Comment by netthinks** [comment]
ok, tried from current master and updated Fullcalendar to 3.1.0. Problem is the same, i will create a bugreport for Fullcalendar.

**Comment by lochmueller** [comment]
Fixed with last commit. Documentation of Fullcalendar said: "It is the moment immediately after the event has ended. For example, if the last full day of an event is Thursday, the exclusive end of the event will be 00:00:00 on Friday!" So... if the Event ends on 2016-01-08 the string in the output have to be 2016-01-09 ;)

**Comment by netthinks** [comment]
in that case I've solved it with this:
`<f:format.date format="{f:if(condition: index.allDay, then: 'Y-m-d', else: 'c')}" base="{index.endDateComplete}">+1 day</f:format.date>`

**Comment by lochmueller** [comment]
Also good idea (better than current patch). I will migrate to your example shortly...
