### ISSUE TITLE
sys_category is not respected in 2.6.1

### ISSUE THREAD

**Issue by netthinks** [lochmueller/calendarize#117]
Until 2.6.1, the sys_categories for calendarize records were respected, this seems to be gone in 2.6.1

TYPO3 7.6

**Comment by lochmueller** [comment]
Do you try to migrate the plugin settings to the "Plugin configuration"-record and select this configuration in every plugin? The configuration of custom events is part of the Plugin configuration in the feature, because the Flexform of the plugin is not realy extendable...

**Comment by netthinks** [comment]
the plugin configuration is empty, how can I migrate the settings?

**Comment by lochmueller** [comment]
Create one new "Plugin Configuration" Record in one of your stroage folder. Configure the needed settings. Select the newly created "Plugin Configuration" in your Plugin. You can remove the old settings in the Plugin after...

**Comment by netthinks** [comment]
the "Plugin Configuration" has not the option to choose sys_categories then. How can I realize this now?

**Comment by lochmueller** [comment]
Hmm... thats not good :( I will check this in the next days...

**Comment by cabi** [comment]
I add for me in my _cabi_events_ Extension the file
`Configuration/TCA/Overrides/tx_calendarize_domain_model_pluginconfiguration.php `
and add there the the sys_categories

```
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::makeCategorizable(
    'cabi_events',
    'tx_calendarize_domain_model_pluginconfiguration',
    'categories',
    [
        // Set a custom label
        'label' => 'LLL:EXT:cabi_events/Resources/Private/Language/locallang.xlf:tx_cabievents_domain_model_event.categories',
        // This field should not be an exclude-field
        'exclude' => false,
        // Override generic configuration, e.g. sort by title rather than by sorting
        'fieldConfiguration' => array(
            'foreign_table_where' => ' AND sys_category.sys_language_uid IN (-1, 0) ORDER BY sys_category.title ASC',
        ),
        // string (keyword), see TCA reference for details
        'l10n_mode' => 'exclude',
        // list of keywords, see TCA reference for details
        'l10n_display' => 'hideDiff',
    ]
);
```

In addition you have to add the categories to the 'defaultConstraints'. I use this slot for this
```
@signalClass \HDNET\Calendarize\Domain\Repository\IndexRepository
@signalName getDefaultConstraints
```
there you get the selected categories nicely with 
```
if (isset($contentRecord['settings']['pluginConfiguration']) && $contentRecord['settings']['pluginConfiguration'] instanceof \HDNET\CabiEvents\Domain\Model\PluginConfiguration) {
            /** @var \HDNET\CabiEvents\Domain\Model\PluginConfiguration $pluginConfiguration */
            $pluginConfiguration = $contentRecord['settings']['pluginConfiguration'];
            $categories = $pluginConfiguration->getCategories();
            foreach ($categories as $category) {
                $categoryIds[] = $category->getUid();
            }
        }
        if (empty($categoryIds)) {
            return [
                'indexIds' => $indexIds,
                'indexTypes' => $indexTypes,
                'contentRecord' => $contentRecord,
            ];
        }

        $databaseConnection = HelperUtility::getDatabaseConnection();
        $rows = $databaseConnection->exec_SELECTgetRows(
            'uid_foreign',
            'sys_category_record_mm',
            'tablenames="tx_cabievents_domain_model_event" AND uid_local IN (' . implode(',', $categoryIds) . ')'
        );
        foreach ($rows as $row) {
            $indexIds[] = (int)$row['uid_foreign'];
        }

        return [
            'indexIds' => $indexIds,
            'indexTypes' => $indexTypes,
            'contentRecord' => $contentRecord,
        ];
```

Then you need the in the PluginConfiguration selected categories in your template, this works fine with this slot
```
@signalClass HDNET\Calendarize\Controller\CalendarController
@signalName searchAction
```
there I translate the categories from the settings (uids) into an array with category-objects.

And at last I use the slot
```
@signalClass \HDNET\Calendarize\Domain\Repository\IndexRepository
@signalName findBySearchPre
```
to search for events with in the search-form selected categories.

I hope that helped a little bit,
Carsten

**Comment by plojewski** [comment]
Hi, when are you planning to add categories support please?

**Comment by lochmueller** [comment]
Categories for plugin configurations: https://github.com/lochmueller/calendarize/commit/62b88bceb2cd4bee302e8ecc05e5ba0da0c9d234
Next steps will follow shortly...
