### ISSUE TITLE
no events found

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#124]
Hi,
I use TYPO3 7.6.14, calendarize 2.7.1.
When changing anything in the backend plugin of calendarize no more events are founds and I get the message: 

    Es gibt keine Ereignisse in der aktuellen Ansicht.  

It's the same problem when I try to insert a new plugin of calendarize.

When I try to add a new event I can save the event. But I get in the  TYPO3 Debug Console the following when debugging is activated in the install tool:

    array(4 items)
    caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
    ERROR => 'Unknown column 'NEW584c76be0153c682101181' in 'where clause'' (60 chars)
     lastBuiltQuery => 'SELECT * FROM tx_calendarize_domain_model_event WHERE
    uid=NEW584c76be0153c68
    2101181 LIMIT 1' (91 chars)
    debug_backtrace => '{closure}#21 // TYPO3\CMS\Backend\Http\Application->run#20 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Http\RequestHan
      dler->handleRequest#302 // TYPO3\CMS\Backend\Http\RequestHandler->disp
      atch#95 // TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch#168 // call_u
      ser_func_array#54 // TYPO3\CMS\Backend\Controller\EditDocumentController->
      ;mainAction# // TYPO3\CMS\Backend\Controller\EditDocumentController->main
      #2043 // TYPO3\CMS\Backend\Controller\EditDocumentController->makeEditFor
      m#1009 // TYPO3\CMS\Backend\Form\FormDataCompiler->compile#1118 // TYPO3\
      CMS\Backend\Form\FormDataGroup\TcaDatabaseRecord->compile#99 // TYPO3\CMS
      \Backend\Form\FormDataProvider\TcaRecordTitle->addData#51 // TYPO3\CMS\Co
      re\Utility\GeneralUtility::callUserFunction#84 // call_user_func_array#4377 
      // HDNET\Calendarize\Service\TcaService->eventTitle# // TYPO3\CMS\Core\Da
      tabase\DatabaseConnection->exec_SELECTgetSingleRow#66 // TYPO3\CMS\Core\D
      atabase\DatabaseConnection->exec_SELECTquery#416 // TYPO3\CMS\Core\Databa
      se\DatabaseConnection->debug#314' (1054 chars)

    array(4 items)
     caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
    ERROR => 'Unknown column 'NEW584c76be0153c682101181' in 'where clause'' (60 chars)
    lastBuiltQuery => 'SELECT * FROM tx_calendarize_domain_model_event WHERE uid=NEW584c76be0153c68
    2101181 LIMIT 1' (91 chars)
    debug_backtrace => '{closure}#21 // TYPO3\CMS\Backend\Http\Application->run#20 // TYPO3\CMS\C
      ore\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Http\RequestHan
      dler->handleRequest#302 // TYPO3\CMS\Backend\Http\RequestHandler->disp
      atch#95 // TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch#168 // call_u
      ser_func_array#54 // TYPO3\CMS\Backend\Controller\EditDocumentController->
      ;mainAction# // TYPO3\CMS\Backend\Controller\EditDocumentController->main
      #2043 // TYPO3\CMS\Backend\Controller\EditDocumentController->makeEditFor
      m#1009 // TYPO3\CMS\Backend\Utility\BackendUtility::getRecordTitle#1175 // T
      YPO3\CMS\Core\Utility\GeneralUtility::callUserFunction#2212 // call_user_fun
      c_array#4377 // HDNET\Calendarize\Service\TcaService->eventTitle# // TYPO
      3\CMS\Core\Database\DatabaseConnection->exec_SELECTgetSingleRow#66 // TYP
      O3\CMS\Core\Database\DatabaseConnection->exec_SELECTquery#416 // TYPO3\CM
      S\Core\Database\DatabaseConnection->debug#314' (924 chars)

I can't say with what version the problem started for me.

Regards
Hobokens

**Comment by Hobokens** [comment]
I checked the problem again, 
After saving the plugin there is a new section in the xml-File:

        <sheet index="general">
            <language index="lDEF">
                <field index="settings.configuration">
                    <value index="vDEF"></value>
                </field>
                <field index="settings.sorting">
                    <value index="vDEF">ASC</value>
                </field>
                <field index="persistence.storagePid">
                    <value index="vDEF"></value>
                </field>
                <field index="persistence.recursive">
                    <value index="vDEF"></value>
                </field>
            </language>
        </sheet>

Removing this section the events are found again.

**Comment by lochmueller** [comment]
Hey @Hobokens 
you have to select a storge Page in your flexform and also a configuration....
Regards,
Tim

**Comment by Hobokens** [comment]
Hi Tim, 
thanks for the hint. I always used 'Record Storage Page' without problems but now you have to use 'Startingpoint'.
