### ISSUE TITLE
Strange behavior in WeeklyView - 1st column is emty

### ISSUE THREAD

**Issue by mminyades** [lochmueller/calendarize#125]
like in issue #103 WeeklyView renders empty columns.

version 2.6.1 worked for me

**Comment by lochmueller** [comment]
Do you try the current Release in TER?

**Comment by mminyades** [comment]
yes, after updating to 2.7.1 form TER, there are again empty columns.

info:
start-date of the recurring events was set to january 2016
- setting "weekStart = 2" shows the complete week (monday - sunday).
>"monday-column" shows no events.!

- setting "weekStart = 1" shows the complete week (sunday - saturday).
>events in "monday-column" are visible

version 2.6.1 seems to work fine.

**Comment by mminyades** [comment]
@lochmueller 
updated to 2.8.0 - still the same behavior
1st column in WeeklyView (in my configuration "monday") is empty

**Comment by mminyades** [comment]
any news about this bug?
is anyone able to reproduce it?

I would argue that the "WeeklyView" is a major feature and i am astonished that it does not get much attention?!!?

**Comment by lochmueller** [comment]
Hey @mminyades ,

I got still problems to reproduce your issue. My test case is:
- Create a event on 1. Jan (all day)
- Set the event to daily till end of month
- Create a plugin instance and select week view
- Take a look at the FE: There are 7 days with 1 event each
- Play with weekStart
- Every time I got 7 days with 1 event each

I need some more technical information / debugging information or configuration settings of time(zone) configuration of the server.

Please keep in mind, that all features in calendarize are "major" features and all of them get attention as much as I can give. Also note that it is non-commercial. So feel free to support with time, money or calmness ;)

Regards,
Tim

**Comment by mminyades** [comment]
hmmm... stange!

i will setup a fresh installation to test some configurations and report my insights here.

**Comment by lochmueller** [comment]
@mminyades Any news on this topic?

**Comment by lochmueller** [comment]
I close this issue. If there are some more debugging information pplease create a new issue or reopen this one.
Regards,
Tim
