### ISSUE TITLE
Set pagetitle to the event title on the detail page

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#139]
Set pagetitle to the event title on the detail page

**Comment by cabi** [comment]
```
use HDNET\Calendarize\Domain\Model\Index;

    /**
     * Fill the Search Form with additional variables.
     *
     * @signalClass HDNET\Calendarize\Controller\CalendarController
     * @signalName  detailAction
     *
     * @see         \HDNET\Calendarize\Controller\CalendarController::detailAction()
     *
     * @param Index $index
     * @param string $domain
     * @param array $extended
     * @param array $settings
     *
     * @return array
     */
    public function setPagetitleToEventtitle(Index $index, $domain, $extended, $settings)
    {
        $title = $index->getOriginalObject()->getTitle();
        $GLOBALS['TSFE']->page['title'] = $title;

        return [
            'index'      => $index,
            'domain'        => $domain,
            'extended'       => $extended,
            'settings'       => $settings
        ];
    }
```

**Comment by Terminator81** [comment]
what do I have to do to make this happen?

**Comment by lochmueller** [comment]
Please use the TitleTagViewHelper: https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/TitleTagViewHelper.php like in the default template: https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Event/Detail.html#L6

For detailed questions: Please use the TYPO3 Slack.

**Comment by Terminator81** [comment]
thanks.....works

**Comment by lochmueller** [comment]
> can the og:title also been set to the title of the event

of course: Write a ViewHelper or check who your current og:title is created and respect the site title in this context. Feel free to share your solution with us.
