### ISSUE TITLE
Questions Feeds and json

### ISSUE THREAD

**Issue by paulsen-it** [lochmueller/calendarize#140]
Hello,
thank you for this great Extension. But I have some questions to use all features.

1. There are Feeds, with the Format XML, RSS, iCal, it is possible to integrate also json?
2. How can I use the Feeds? Which URL have the Feeds? I don't find anything about that. Only one single Calendar Item can download as iCal, but where is the Feed?

Thank you

Björn

**Comment by lochmueller** [comment]
2.) The links are not actived by default:
https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/List.html#L7
1.)  You can create a new "json" template and link on the json-format (same as the others).

Regards,
Tim

**Comment by paulsen-it** [comment]
Thank you very much!
