### ISSUE TITLE
No dates in Calendarize Information

### ISSUE THREAD

**Issue by ArminVieweg** [lochmueller/calendarize#141]
Hello,
I'm trying out Calendarize the first time. Looks promising. But when I create a first test record, I just get this output:

![2017-01-23_1717](https://cloud.githubusercontent.com/assets/1275298/22212161/e9c1b7ca-e18f-11e6-829f-326daea0c347.png)

The actual days are missing. I tried it with the sample event and a news record (using calendarize_news).

Btw. I've got another bug. When I create a new example event, I get this sql error:

**Unknown column 'NEW58862d2cd42eb354915780' in 'where clause'**
```
SELECT * FROM tx_calendarize_domain_model_event WHERE uid=NEW58862d2cd42eb353915780 LIMIT 1
```
Stack trace says this method is involved: `HDNET\Calendarize\Service\TcaService->eventTitle`

I've tested with TYPO3 7.6.15 and PHP 5.6. The server is a Windows server.

Thanks in advance!
Armin

**Comment by ArminVieweg** [comment]
I've investigated a little bit...

The reason is the %G in your date format, which returns FALSE for me. When I replace it with %Y it works. Maybe some timezone configuration issues... I'll check this tomorrow.

**Comment by lochmueller** [comment]
The bug of the description is already fixed in the current master: https://github.com/lochmueller/calendarize/commit/c099e8abe459119b76bc647a213bc877fb17c3ec
If you have some more information about the "%G" vs. "%Y" problem please write me. Then I will fix this and create a new release....

**Comment by lochmueller** [comment]
I changed the format to "%Y". The SQL error was already fixed in the last version...
