### ISSUE TITLE
Add category selection to event list

### ISSUE THREAD

**Issue by npostnik** [lochmueller/calendarize#143]
Hi. I created an extension which handles events. Events are "calendarized" with calendarize. Each event can be assigned to one or many categories. I want to filter the event list by specifying categories (flexform).

That is what I found out so far: 
CalendarController::listAction expects a lot of arguments. If i.e. $startDate is set, then CalendarController::determineSearch triggers indexRepository->findBySearch. In this function there are two signal calls, which can be used to manipulate the arguments in order to set only specific indexUids. In my case I would determine which events are assigned to a desired category, change $arguments['indexIds'] and then select events by category selection.

My questions:
1) Argument $customSearch in IndexRepository->findBySearch is never used. Bug?
2) Is there a way to add something to the flexform configuration?
3) There is no signal call in the function IndexRepository->findList, which is called from CalendarController::listAction by default. How can I change the query in this function?

Maybe you have a totally different approach to this matter. How would you add category selection to plugin configuration?

Any help is appreciated. Thanks in advance.
Natalia

**Comment by lochmueller** [comment]
Related to your questsions:
1.) No. The customSearch are the fields of your Search-Partial for the "Search Form" View. If you add the categroy selection to the search form you can set the name of the field to "customSerch[myCategory]" and you get it in the signal. The paramater is only for the hooks, and not for the internal process.
2.) No. This is a general problem of FlexForm configurations. You can override the path the flexform and add the field in your on configuration (not realy updatable). The other solution is, to use the new configuration records. You can easily extend the table of the configuration records with DB/TCA.
3.) The list view is determinate by the settings in the FlexForm. Please use the search result view, if you want to manipulate the result list of your custom events. Alternativly you can push a change request and we add a signal to the findList also?!

I will add documentation/examples for category integration shortly.

Regards,
Tim

**Comment by Hobokens** [comment]
Some more documentation/examples would be great.

**Comment by lochmueller** [comment]
The calendarize default event use categories now and the slot handle the reduce process in the search result view (bugfix in the current master). More features/fixes in separate issues...
