### ISSUE TITLE
How to configure realurl

### ISSUE THREAD

**Issue by Terminator81** [lochmueller/calendarize#144]
Hello, 

can you tell me, how to get calendarize working in combination with realurl?

**Comment by lochmueller** [comment]
Do you check these:
https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst
and also the example:
https://github.com/lochmueller/calendarize/blob/37a6542515d040ad905c81545183f6b18e669d16/Classes/Hooks/RealurlConfiguration.php#L31

Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. If there are any problems/error please create a new issue....

Regards,
Tim
