### ISSUE TITLE
Translations (Localization)

### ISSUE THREAD

**Issue by tba6440** [lochmueller/calendarize#149]
If I localize an event record the Title, Abstract and Description are not visible in the front-end.
Is there any solution how can we manage the localizations?

The lang conf in Typo3 6.2.30 is 

// german
[globalVar = GP:L = 1]
    config.sys_language_uid = 1
    config.sys_language_mode = content_fallback ; 0
    config.sys_language_overlay = 1
    config.language = de
    config.locale_all = de_DE.UTF-8
    config.htmlTag_langKey = de-DE
[global]

**Comment by sheydin** [comment]
Same probleme here. Any solution yet?

**Comment by marcelbirrer** [comment]
same problem here. calendarize 3.1.2, TYPO3 8.7.8, localization settings like above.

**Comment by lochmueller** [comment]
Close this issue. Same problem described here: https://github.com/lochmueller/calendarize/issues/202
