### ISSUE TITLE
could the calender be cached?

### ISSUE THREAD

**Issue by c2po** [lochmueller/calendarize#15]
Hi,
the admin panels tells me that there is a USER_INT object for each calendarize plugin which slows down the website (some people like to integrate a calender on every page :( ) and which prevents indexed_search from indexing pages (list view). Is this necessary and why? Could this be changed?

**Comment by lochmueller** [comment]
Yes... I remove all (except search and result) from the nonCachableActions... The result action is explicit for search result pages, because this should not cached at all...
