### ISSUE TITLE
Migration translations to TYPO3 Translation Server

### ISSUE THREAD

**Issue by r4fx** [lochmueller/calendarize#157]
Please consider to migrate translations to TYPO3 Translation Server https://translation.typo3.org/
It's easier way to maintenance the translations.

https://forge.typo3.org/projects/team-translation

> Policy for new extensions
> Setting up a project on the translation server requires some manual steps. In order to get most efficiency and to ensure the continued existence of added extensions, new extensions to be added are subject to following requirements:
> 
> The extension candidate must be publicly available in TER
> The extension candidate must be marked as "stable" in TER (meaning it is actively supported)
> The extension candidate should have a minimum user base of 120 regular installs
> A ticket created by the maintainer of the extension is created for asking this

**Comment by lochmueller** [comment]
FYI: https://forge.typo3.org/issues/82203

**Comment by lochmueller** [comment]
@r4fx https://translation.typo3.org/projects/TYPO3.ext.calendarize/

**Comment by r4fx** [comment]
Great, thank you!
