### ISSUE TITLE
RealURL sync problems

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#159]
EXT:calendarize should take care of the URL data (tx_realurl_urldata) to drop old entries for "index" URLs.

**Comment by charly83** [comment]
I don't know if your issue has the same cause as my problem.
When I edit an calendarize entry and save the event with "save and close" everything seems to be all right. But in FE the event doesn't work any more and a have a lot of entries in the tx_realurl_urldata.

After clearing the entries in the table "tx_realurl_urldata" everything works perfekt.

**Comment by lochmueller** [comment]
Yes... the problem is, if you change date information of the event, new index items are created. Then the old URIs get invalid.

Solution: A Post-Index function that check the realurl Index and drop the old URI segments (and create new one).

**Comment by lochmueller** [comment]
Drop this. We will integrate the new link handling of TYPO3 9.5 which is much smarter than realurl and cooluri.

**Comment by mario-seidel** [comment]
This is not a good solution for TYPO3 < 9.5. Due the FE Url depends on the index, that is completly rewritten on every change, it is a mess for every URL rewriting.
Maybe a Signal Slot in IndexerService could help to adjust things when indexes are deleted?

**Comment by lochmueller** [comment]
Hey @mario-seidel ,
good point. I created a issue for this:
https://github.com/lochmueller/calendarize/issues/326
Regards,
Tim
