### ISSUE TITLE
Month view in 2.8.1 is not compatible with TYPO3 6.2

### ISSUE THREAD

**Issue by simare** [lochmueller/calendarize#162]
The month view uses the attribute `base` of `f:format.date` which is not supported in the fluid version shipping with TYPO3 6.2. So an exception is thrown when selecting an calendar view.
Last working version is 2.7.1.
https://github.com/lochmueller/calendarize/blob/2.8.1/Resources/Private/Partials/Month.html#L82

**Comment by lochmueller** [comment]
Hey @simare 
I close this issue. Sorry, but there will be no TYPO3 6.2 releases anmore ( https://github.com/lochmueller/calendarize/commit/8226885f6b14442f73b7c150357bc71dd3c5e4ad ). You could fix this directly in your template...
Regards,
Tim
