### ISSUE TITLE
Invalid argument exception thrown in \Calendarize\ViewHelpers\IfDateUpperViewHelper

### ISSUE THREAD

**Issue by miha1979** [lochmueller/calendarize#168]
Hello,

when I use Calenderize extension in TYPO2 8.7 I get the following error in daily view (german: Tagesansicht):

Exception handler (WEB): Uncaught TYPO3 Exception: #1256475113: The argument "check" was registered with type "string|\DateTime", but is of type "DateTime" in view helper.

What can I do to solve this error?
TYPO3 8.7.1, PHP 7.0.15, calendarize 3.1.1

Thank's Michael

**Comment by lochmueller** [comment]
Thanks for reporting. Fiexd with the attached patch.
