### ISSUE TITLE
Start_date values in table tx_calendarize_domain_model_index become faulty after switch to summer/winter time

### ISSUE THREAD

**Issue by topson** [lochmueller/calendarize#169]
Database entries in the column "start_date" in the table "tx_calendarize_domain_model_index" become faulty after crossing a time change date.
Example:
For reading puropses I've used from_unixtime() to read the database start_date values.
An event is created with the start date February the 2nd 2017 and takes place daily.
The database entries for the time period of Feb. 2nd to March the 26th will be flawless, meaning the start date would look like "2017-02-20 00:00:00".  
However in 2017,  the 26th of March marks the time change to summertime. The database entry of March the 27th will be faulty because the start date would look like "2017-03-27 01:00:00".
This problem also occurs going from summer to wintertime:
An Event with the start date of September 28th would have an database entry like "2017-09-28 00:00:00". Once October the 29th is reached database entries would look like "2017-10-30: 23:00:00".

If you have more that one reoccuring event, the FE-calendar will produce sorting issues.

**Comment by No5251** [comment]
Maybe this one gets also fixed through these:
https://forge.typo3.org/issues/68651
https://forge.typo3.org/issues/61110

**Comment by neonaut** [comment]
Hi! I've created a patch for the core. Would be nice if you could review it! https://review.typo3.org/#/c/52952/

Greetings. Paul

**Comment by lochmueller** [comment]
Hey... seems to be a mix up beween core and calendarize. I added also this patch:
https://github.com/lochmueller/calendarize/commit/857e067e04786d60a7d03590e21d5e44ddb2d4df
I will close this issue... if there are more problems I need more technical information about it...
