### ISSUE TITLE
Events on last day of month won't be shown

### ISSUE THREAD

**Issue by Schweriner** [lochmueller/calendarize#17]
Hey,
first I want to say thank you very much for the extension - nice work!

Currently running in troubles with events on 31th October - they wont be added to the month view. Using PHP 5.4 and TYPO3 6.2.15.

I guess the problem is located in the IndexRepository line 167:

For example october: 

This
$endTime = mktime(0, 0, 0, $month + 1, 0, $year);

results for me in 1446246000 (2015-10-30 23:00:00).

Maybe this would be a better solution?
$endTime = mktime(0, 0, 0, $month + 1, 1, $year);

Greetings from Schwerin, Germany

**Comment by lochmueller** [comment]
Thanks... your are right. Fixed in the next version and in master in a few seconds... :)
