### ISSUE TITLE
Categories disappear after a while

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#173]
Hi,
I have a strange problem with TYPO3 8.7.4 and calendarize 3.1.2

With the following simple part I show the categories under the event in list view.

	<f:if condition="{event.categories}">
		<div class="cal_category"> Kategorie:&nbsp;
			<f:for each="{event.categories}" as="category" iteration="it">
				{category.title}{f:if(condition: it.isLast, else: ',')}
			</f:for>
	        </div>               
	</f:if>

When the whole is cleared in the install tool I can see the categories for some hours (?) in FE. Then they disappear. I have no idea what the reason could be. I'm not sure whether the problem started with TYPO3 8.7.4 or earlier.
With TYPO3 7.6.x I never had problems.
Regards
Hobokens

**Comment by lochmueller** [comment]
Hey @Hobokens sounds strange. I will check the location of the category-API calls. Perhaps there is some mixup between ext_tables/ext_localconf/TCA configuration so the category is gone, if the first request is a backend/frontend/cli request etc.
Regards,
Tim

**Comment by Hobokens** [comment]
Hi, I just want to say that the problem still exists with TYPO3 8.7.8.
One more information that might be helpful: 
A have a calendar page where only events with a special category are shown. When the categories are disappeared as as described in my previous post no more events are shown.

Regards and thanks for the great extension
Hobokens

**Comment by lochmueller** [comment]
Fixed with last commit... thanks.
