### ISSUE TITLE
cHash empty

### ISSUE THREAD

**Issue by kan0ne** [lochmueller/calendarize#174]
Hello,
for our new projekt we want to use calendarize, because it is so flexible. The first impression is very good.
But now i run into an error:
	
Page Not Found
Reason: Request parameters could not be validated (&cHash empty)

I added a search-Plugin and a result-List plugin to a page and got this error after search.
I am using Typo3 8.7.4 and Calendarize 3.1.2

Thx for helping

**Comment by lochmueller** [comment]
https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/Link/AbstractLinkViewHelper.php#L61
I reset the URIBuilder before the link is build. 
So the cHash usage should be set by default...

Could you run some debugging?!

Regards,
Tim

**Comment by kan0ne** [comment]
Yes i did some debugging but i didnt find the problem.
I think the URIBuilder is not the Problem, because the error happens only on POST for the searchresults page.
When the request method is GET the site opens normally.

Maybe i miss something on setting up the search with calendarize?
Is there an example usage or a tutorial, where i can have a look?

Regards,
Martin

**Comment by lochmueller** [comment]
Hey Martin,
do you integrate a own Event model? Do you have a custom search template? https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Event/Search.html Please take care, that you use the form-ViewHelper and the namespace "customSearch" in it.

Please check all posts parameter, if there are some "strage" params?!
Do you use the Search and the Searchresult Plugin on the page? Any more, that could throw this error. Please active only Search and Searchresult for your tests..

Regards,
Tim

**Comment by kan0ne** [comment]
hi,

i have no own event model nor a custom search template.
I just installed the extension from ter and created some events.
- added a search plugin to my page
- added a searchresults plugin to my page
- added a details plugin to details page
- every plugin i configured exactly the same (detail: details page, list: my page)

Opening my page i see the search form and my list of events.

when i configure: $GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = false
i get
`Argument 6 passed to HDNET\Calendarize\Slots\EventSearch::setIdsByCustomSearch() must be of the type array, boolean given`

should i try to exclude some parameters with [cHashExcludedParameters] 

Regards,
martin

**Comment by lochmueller** [comment]
I fixed this problem ```Argument 6 passed to HDNET\Calendarize\Slots\EventSearch::setIdsByCustomSearch() must be of the type array, boolean given``` in the current master. Could you switch to dev-master and test ist again with ```pageNotFoundOnCHashError = false ```
https://github.com/lochmueller/calendarize/commit/8e208b0f43d8f97916c526e9783098064e75438f
Regards,
Tim

**Comment by kan0ne** [comment]
hi,

yes that works for me! thx

Regards,
martin

**Comment by lochmueller** [comment]
Great... I close this issue...
