### ISSUE TITLE
IndexerService->prepareIndex generates faulty Timestamps

### ISSUE THREAD

**Issue by j4k3** [lochmueller/calendarize#176]
Appended are some screenshots documenting an error in the IndexerService.  

The events have repeating occurences beginning in winter, all on the same day of the week. But during Summer Savings time the dates skip to the next day. The same happens in reverse for events that start in summer.

<img width="866" alt="bildschirmfoto 2017-08-09 um 09 37 24 1" src="https://user-images.githubusercontent.com/1037902/29616546-2d1424f8-8812-11e7-8c0d-1c33e7d5d6e7.png">
<img width="889" alt="bildschirmfoto 2017-08-08 um 17 00 12" src="https://user-images.githubusercontent.com/1037902/29616547-2d16228a-8812-11e7-9865-62124d74f7a4.png">

The Problem is, that the Date in the indexer table is generated based upon the DateTime object in the local TimeZone. This works if the timestamp is instead generated from DateTime objects in the UTC TimeZone.

-- 
$this->prepareRecordForDatabase($record);

++
$testa = \DateTime::createFromFormat(
	'Y-m-d',
	$record['start_date']->format('Y-m-d'),
	new \DateTimeZone('UTC')
);
$record['start_date'] = $testa;

$teste = \DateTime::createFromFormat(
	'Y-m-d',
	$record['end_date']->format('Y-m-d'),
	new \DateTimeZone('UTC')
);
$record['end_date'] = $teste;
$this->prepareRecordForDatabase($record);

**Comment by lochmueller** [comment]
Hey @j4k3 I will check this and add it to the extension...
