### ISSUE TITLE
Date in own Model

### ISSUE THREAD

**Issue by mithri** [lochmueller/calendarize#18]
Hi,

how is it possible to get the Date from the Calendarize Repository in my own Model/Controller? Is there an example anywhere? I just want to display the date in a list view from my extension.

Thanks for your help and for the geat extension.

Tobias

**Comment by lochmueller** [comment]
Hey @mithri 

the general idea is to fetch the Index items via the calendar plugin and get the originalObject via the index. If you use the model in your own extension and want to display e.g. all dates for the model in your own logic, the easiest way is the new findByTraversing in the indexRepository

```
$indexRepository = ...; // build Repository via object manager or DI
$index = new Index();
$index->setUid(0);
$index->setForeignTable('tx_tablename....');
$index->setForeignUid($this->getUid()); // UID of your model
$datesOfTheModel = $indexRepository->findByTraversing($index);
```

Regards,
Tim

**Comment by mithri** [comment]
Thank you. Now i understand findbyTraversing :-)
