### ISSUE TITLE
Getting annoying warnings

### ISSUE THREAD

**Issue by archer2410** [lochmueller/calendarize#181]
Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /www/htdocs/xxxx/xxxx/typo3conf/ext/calendarize/Classes/Slots/EventSearch.php line 116

Getting this a thousand times a week. Don't know if it's a bug or stupid me.

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master.
