### ISSUE TITLE
Index is cloned with Sysfolder, leaving indices orphaned

### ISSUE THREAD

**Issue by j4k3** [lochmueller/calendarize#183]
When cloning a Sysfolder, the existing event and index entires are copied over. The problem is, that the reference from index to event isn't updated. The copies of the events instead create new indices. The result is, that the indices to the original events reside in the copy with no way to remove them from within the backend.
The reference in the indexes should either be updated on copying, or not copied whatsoever.

**Comment by lochmueller** [comment]
Hey @j4k3 ,

this hook should already take care of this situation:
https://github.com/lochmueller/calendarize/blob/master/Classes/Hooks/ProcessCmdmapClass.php#L30

Could you run some debugging?
https://github.com/lochmueller/calendarize/blob/master/Classes/Hooks/ProcessCmdmapClass.php#L36
Perhaps there is missing some $this->copyMappingArray mapping stuff and check "isRecordCopied" to get the real/new ID of the record.

Regards,
Tim

**Comment by lochmueller** [comment]
Fixed by readOnly flag of the index table.
