### ISSUE TITLE
Calculation of recurring events is wrong

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/calendarize#185]
To reproduce:
Add an event at e.g. 2017-10-25 10:00 - 12:00 with weekly recurring ("Frequenz") of 5 times ("Anzahl").
Watch the wrong generated index record inside the event record and finally in the frontend output:
Wed 25.10.2017 - Wed 25.10.2017 (10:00 - 12:00)
Tue 31.10.2017 - Tue 31.10.2017 (10:00 - 12:00)
Tue 07.11.2017 - Tue 07.11.2017 (10:00 - 12:00)
Tue 14.11.2017 - Tue 14.11.2017 (10:00 - 12:00)
Tue 21.11.2017 - Tue 21.11.2017 (10:00 - 12:00)
Tue 28.11.2017 - Tue 28.11.2017 (10:00 - 12:00)

Finally I ask myself if the number of generated index records is also wrong, because there are 6 and not 5. But this could be discussed...

**Comment by lochmueller** [comment]
I will check this.... the number of entries is NOT wrong. I your create a single event and repeat it two times... the you will get 3 events.

The break in the days is wrong and could be related to daylight saving time...

Regards,
Tim

**Comment by mediaessenz** [comment]
As far as I see, the problem stuck somewhere in the `prepareRecordForDatabase` method of the indexPreparationService class.
I already tried to normalize (using DateTimeUtility::normalizeDateTimeSingle) the $value of all DateTimeInterface values, but this doesn't helps.

**Comment by lochmueller** [comment]
I close this issue. As described in many core issues, the timezone UTC is recommended: https://forge.typo3.org/issues/68651

**Comment by mediaessenz** [comment]
I wouldn't say, UTC is recommended in general. IMO UTC is (sadly) currently the only (halfway) working solution to circumnavigate the problems sitting in the core.
To name one upcoming problem with setting the timezone to UTC is the no more correctly working moments stuff inside calendarize, because moments uses the timezone of the client, which is for someone who lives in germany "Europe/Berlin" and *not* "UTC". Because of this, all dates defined in an "UTC"-Backend, will result in wrong dates generated by moments.

**Comment by mediaessenz** [comment]
Meanwhile I read some more about the DateTime "mess" of TYPO3.
It seems that some things get fixed in the last time, but Date (not DateTime) seems to be a still existing problem, because of the fact, that the timezone information gets irreversible lost, after TYPO3 normalize it to UTC before storing it.
This brings me to the point, that this bug can maybe simple be fixed by changing the eval value of the start_date and end_date from "date" to "datetime".
I will try this out now and will report ...

**Comment by mediaessenz** [comment]
After apply my patch you must reindex existing event indexes, if you change the timezone by php.ini or `$GLOBALS['TYPO3_CONF_VARS']['SYS']['phpTimezone']`
