### ISSUE TITLE
Categories in frontend don't work if logged out from backend 

### ISSUE THREAD

**Issue by mediaessenz** [lochmueller/calendarize#189]
Because of the current categorization way over the ext_tables.php, categories of events are only available in the frontend, if a user is logged into the backend.

Moving the code to `Configuration/TCA/Overrides/tx_calendarize_domain_model_event.php` will fix the problem.

This seem to be the same issue: https://github.com/lochmueller/calendarize/issues/173

**Comment by Hobokens** [comment]
@mediaessenz 
Thanks for the pull request. I checked it out immediately and the first impression is very positive. The categories are shown in all situations now.
