### ISSUE TITLE
Incorrect integration of ics-files

### ISSUE THREAD

**Issue by wullux** [lochmueller/calendarize#195]
The integration of ics-files generates wrong dates. 

Correct dates on my lokal machine in my example:

![ics_windows10](https://user-images.githubusercontent.com/11768030/32509408-7d58e04a-c3ed-11e7-9711-32235deb86a7.JPG)

The dates in calendarize differ (+2 days):

![ics_calendarize](https://user-images.githubusercontent.com/11768030/32509402-786b1c24-c3ed-11e7-9cce-e5be29c313b3.JPG)

To Reproduce integrate file 

https://www.schulferien.org/media/ical/deutschland/ferien_rheinland-pfalz_2017.ics?k=lU-Oq8L4m2qSgCJQSXr5lQ7YKemfiJW_OholfsJLxx5_Hp5Vbsb7gryYj_Z9ixvvK_acuwyMCaFchwcZ0t5oGg_9mZTQHi9fiBSqebzWZPQ

**Comment by wullux** [comment]
Hi Tim,
thank you very much for having a look at it! Unfornately in my installation the problem still occurs, also with the current master...
Perhaps you can have a look at my installation (mittwald)?

This is the code in the ics (Weihnachtsferien) from the example above:

BEGIN:VEVENT
CREATED:20171221T032002Z
LAST-MODIFIED:20171221T032002Z
DTSTAMP:20171221T032002Z
SUMMARY:Weihnachtsferien 2017 Rheinland-Pfalz
DTSTART;VALUE=DATE:20171222
DTEND;VALUE=DATE:20180110
URL:http://www.schulferien.org
DESCRIPTION:Alle Termine auf www.schulferien.org
TRANSP:TRANSPARENT
UID:F_2017_termin5a3b1a5412c1b@schulferien.org
END:VEVENT

As said on my win10 machine in outlook displayed as 
22.12.2017 - 09.01.2018
and in typo3 +2days
22.12.2017 - 11.01.2018 

Best wishes,
Dirk

**Comment by kmcs** [comment]
Hi,
I had the same issue with export of ics files.
Thats exacly the problem: https://stackoverflow.com/questions/47151477/ics-file-when-imported-in-outlook-shows-wrong-end-date-when-no-start-end-time?answertab=votes#tab-top

Here is my workaround:
https://gist.github.com/kmcs/b07dae379734f729bbdfb8bcbd9c79cb

Best regards,
Timo

**Comment by MichiBeck** [comment]
Same problem for me, is there a solution, can i change anything? The workaround from **kmcs** didn´t work for me...

**Comment by lochmueller** [comment]
There are only two positions in the code, that should changed to a working API:
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/ExternalTimeTable.php#L50
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/IcsReaderService.php

Perhaps we should switch to a more modern version for parsing the ics files:
e.g. https://github.com/u01jmg3/ics-parser

**Comment by MichiBeck** [comment]
This sound good!

**Comment by phvt** [comment]
sabre/vobject is another good option to consider: http://sabre.io/vobject/icalendar/

**Comment by lochmueller** [comment]
@phvt Good point. I think I will add the "blue print" so the admin/integrator can install the lib via `composer require sabre/vobject` and the new functions are used. I will keep the old parser for non-composer installations.

**Comment by lochmueller** [comment]
I close this issue. There are two problems related to newer issues: https://github.com/lochmueller/calendarize/issues/366 I will check the ICS import in ticket 366 completly
