### ISSUE TITLE
year.view variable $year empty

### ISSUE THREAD

**Issue by joka123** [lochmueller/calendarize#20]
when config the contentelement as year.view then the variable $year in controller ist empty and you will get no results from repository. 
my quick and dirty solution
    /**
     * Year action
     *
     * @param int $year
     *
     * @return void
     */
    public function yearAction($year = null)
    {
        $date = DateTimeUtility::normalizeDateTime(1, 1, $year);
        if ($year == null){
                $year = date('Y');
        }
        $this->view->assign('indices', $this->indexRepository->findYear($year));
        $this->view->assign('date', $date);
    }

regards
jochen kast

**Comment by lochmueller** [comment]
Thanks for reporting. Done with next git push... :)
