### ISSUE TITLE
Multilingual usage shows empty <li><a></a></li> for not active language

### ISSUE THREAD

**Issue by djrocher** [lochmueller/calendarize#202]
I'm using calendarize 3.1.2 in TYPO3 8.7.8 with common language settings:

```
# Website languages (DE = Default):
config {
sys_language_uid = 0
language = de
htmlTag_langKey = de
locale_all = de_DE.utf8
}
[globalVar = GP:L = 1]
config {
sys_language_uid = 1
language = en
htmlTag_langKey = en
locale_all = en_EN.utf8
}
[global]
```

I added English translations in the Backend:

![calendarize_github_backend](https://user-images.githubusercontent.com/34398958/33991577-613de8fc-e0cf-11e7-9221-22cada7d6ca2.jpg)

That's what it looks like in the Frontend (German and English language version):

![calendarize_github_de](https://user-images.githubusercontent.com/34398958/33991590-69998fd8-e0cf-11e7-8c30-9172ada42da0.jpg)
![calendarize_github_en](https://user-images.githubusercontent.com/34398958/33991597-6f3de57e-e0cf-11e7-8294-a30fd71861fd.jpg)

The source code shows that list elements without link texts (`<li><a></a></li>`) are generated for the NOT ACTIVE language:

`<td class="active hasEvents "> 04 <ul class="events"><li><a href="/de/fuer-einzelpersonen/kalender/detail/?tx_calendarize_calendar%5Bindex%5D=4385&amp;cHash=ca5e08efd60b37ea3c7acfaa297c95df"> TYPO3 Schulung </a></li><li><a href="/de/fuer-einzelpersonen/kalender/detail/?tx_calendarize_calendar%5Bindex%5D=4800&amp;cHash=949e378d340aa292cb646d3d0ab854df"></a></li></ul></td>`

In
typo3conf/ext/calendarize/Resources/Private/Partials/Month.html
the links to the detail page are set in line 47-49. It seems that the "for each loop" doesn't check to generate list elements only for the active language?

Any ideas to resolve this?

PS: Regarding this issue I didn't check the week and day view of the plugin yet.

**Comment by lochmueller** [comment]
@djrocher Short fix: You can check this in the template and just ignore the items that result in an empty li. Complex solution: We have to fix the selection of the events with DB/Extbase. I will check this soon...

**Comment by lochmueller** [comment]
New fix in the current master should solve this problem 👍
