### ISSUE TITLE
calendarize 3.2 / autoloader 4.0 - Problem with CoolUri

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#204]
Hi,
with TYPO4 8.7.9 and the above extensions I get the following warning

Core: Error handler (FE): PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class '\HDNET\Calendarize\Service\Url\CoolUri' not found in /html/typo3/typo3conf/ext/cooluri/Clas/Core/Functions.php line 331

For new or resaved events I can't open the detail view.

Regards
Hobokens

**Comment by lochmueller** [comment]
Hey @Hobokens ,
do you use the complete callback name described in the documentation? https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst
"Class not found" is strange, because the class name is the right one?!?!
Regards,
Tim

**Comment by Hobokens** [comment]
Hi Tim,
I'm using claendarize for quite a while with CoolUri and everything was fine. I ran into this problem after upgrading autocomplete and calendarize to the mentioned versions. Now I use only autoloader v4.0 und downgraded calendarize to 3.1.3.
Regards
Hobokens.

**Comment by Hobokens** [comment]
Hi, 
I checked the problem again with the newest autoloader and calendarize 3.2.1, Good news the problem is gone.
Regards
Hobokens
