### ISSUE TITLE
DateTime::setDate() error

### ISSUE THREAD

**Issue by klabauterKoffer** [lochmueller/calendarize#205]
Hello,
I use Typo3 8.7.8 with Calendarize 3.2.0 extension:
If you want to enter a repetition of a crop in the BE, the following error message appears:

Oops, an error occurred!
DateTime::setDate() expects parameter 1 to be integer, string given

Core: Exception handler (WEB): Uncaught TYPO3 Exception: DateTime::setDate() expects parameter 1 to be integer, string given | TypeError thrown in file /var/www/vhosts/.../httpdocs/typo3conf/ext/calendarize/Classes/Service/RecurrenceService.php in line 69. 

How can I fix the error?

A similar error appears if you want to display a monthly overview in FE:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: DateTime::setDate() expects parameter 1 to be integer, string given | TypeError thrown in file /var/www/vhosts/.../httpdocs/typo3conf/ext/calendarize/Classes/Utility/DateTimeUtility.php in line 119. 

Best Regards
Kurt

**Comment by lochmueller** [comment]
Hey @klabauterKoffer ,
thanks for reporting. The attached patch ( https://github.com/lochmueller/calendarize/commit/9dea819132ad5496d777b30e6717ce042815d282 ) fix this problem. The parameters of the setDate have to be integers.
Regards,
Tim

**Comment by jacques2017** [comment]
Hello,
why is the fixed Version not in TER? Please load it into TER.

Best Regards,
Jens

**Comment by lochmueller** [comment]
The TER release is the current (3.2.0). Next release will follow in the next days. If you need this fix shortly, please switch to "dev-masert#9dea819132ad5496d777b30e6717ce042815d282". Regards,
Tim

**Comment by jacques2017** [comment]
Thank you for your answer. 
I fixed it. 
But there another file to fix:
Classes/Domain/Repository/IndexRepository.php

$month and $year seems not to be integer
265    /**
266     * find Month.
267     *
268     * @param int $year
269     * @param int $month
270     *
271     * @return array|\TYPO3\CMS\Extbase\Persistence\QueryResultInterface
272     */
273    public function findMonth($year, $month)
274    {

275 old:        $startTime = \mktime(0, 0, 0, $month, 1, $year);
275 new:      $startTime = \mktime(0, 0, 0, (int) $month, 1, (int) $year);

276 old:       $endTime = \mktime(0, 0, 0, $month + 1, 1, $year) - 1;
276 new:     $endTime = \mktime(0, 0, 0, (int) $month + 1, 1, (int) $year) - 1;

277
278        return $this->findByTimeSlot($startTime, $endTime);
279    }

Jens

**Comment by lochmueller** [comment]
Fixed in current master: https://github.com/lochmueller/calendarize/commit/f9e625e8e2a700f81c5405421d127a8976f48294
