### ISSUE TITLE
Missing table tx_calendarize_domain_model_caldav

### ISSUE THREAD

**Issue by r3h6** [lochmueller/calendarize#207]
After installing get this error in list view:
```
array(4 items)
   caller => 'TYPO3\CMS\Core\Database\DatabaseConnection::exec_SELECTquery' (60 chars)
   ERROR => 'Table 'calendarize.tx_calendarize_domain_model_caldav' doesn't exist' (68 chars)
   lastBuiltQuery => 'SELECT uid FROM tx_calendarize_domain_model_caldav WHERE pid=0 AND tx_calend
      arize_domain_model_caldav.deleted=0 LIMIT 1' (119 chars)
   debug_backtrace => 'call_user_func#21 // {closure}# // TYPO3\CMS\Backend\Http\Application->run#2
      0 // TYPO3\CMS\Core\Core\Bootstrap->handleRequest#94 // TYPO3\CMS\Backend\Ht
      tp\BackendModuleRequestHandler->handleRequest#307 // TYPO3\CMS\Backend\Http\
      BackendModuleRequestHandler->dispatchModule#93 // TYPO3\CMS\Core\Http\Dispat
      cher->dispatch#202 // call_user_func_array#41 // TYPO3\CMS\Recordlist\Record
      List->mainAction# // TYPO3\CMS\Recordlist\RecordList->main#607 // TYPO3\CMS\
      Recordlist\RecordList\AbstractDatabaseRecordList->generateList#414 // TYPO3\
      CMS\Core\Database\DatabaseConnection->exec_SELECTgetSingleRow#488 // TYPO3\C
      MS\Core\Database\DatabaseConnection->exec_SELECTquery#431 // TYPO3\CMS\Core\
      Database\DatabaseConnection->debug#314' (722 chars)
```

**Comment by r3h6** [comment]
As well as for:
tx_calendarize_domain_model_configurationgroup
tx_calendarize_domain_model_event
tx_calendarize_domain_model_pluginconfiguration

...any TCA/*.php definition...

**Comment by lochmueller** [comment]
Du you install the extension in the right way? Composer + Extension manager?
Please uninstall and install the extension again. Seems that the install hooks are not executed (e.g. if you just enter a extension in the PackageStates manually).

**Comment by r3h6** [comment]
I installed through composer. After clearing caches and reinstall them it created only the table "tx_calendarize_domain_model_event" with only one attribute "category". After this I gave up ;-)
If no one else had these issue you can close this one.
Maybe the issue is rather related to the "autoloader" extension.

**Comment by lochmueller** [comment]
OK. I will close this issue.... I will double check autoloader/calendarize on the T3BOARD next week. Perhaps I found the same bug....

**Comment by Germar** [comment]
I had the same problem after installing with composer. Fixed it with `Admin Tools -> Maintanance -> Analyze Database Structure -> Apply selected changes`
