### ISSUE TITLE
RealUrl resolution is broken

### ISSUE THREAD

**Issue by j4k3** [lochmueller/calendarize#208]
I have an instance of calendarize running on this page,
http://www.marienhaus-klinikum-ahr.de/presseund-medien/veranstaltungen/

The URLs for the event occurences are auto generated. For some reason, the RealURL handles for these stop working after a while. For example these URLs did correctly resolve back to their event, but now, they just display the list of events.

http://www.marienhaus-klinikum-ahr.de/presseund-medien/veranstaltungen/event/informationsveranstaltung-fuer-schwangere-2018-01-22-07-00/
http://www.marienhaus-klinikum-ahr.de/presseund-medien/veranstaltungen/event/informationsveranstaltung-fuer-schwangere-2018-02-26-07-00/
http://www.marienhaus-klinikum-ahr.de/presseund-medien/veranstaltungen/event/informationsveranstaltung-fuer-schwangere-2018-03-26-07-00/

I've noticed that the hour in the time used is of the wrong format, it says 07-00 where the events starting time is actually 19:00, maybe thats the problem? There are entries in the tx_realurl_uniqalias table, that match the URLs generated in the value_alias field. These have value_ids for the correct event occurence.

I'd like to debug further but am a bit lost here. Is there a way to disable RealURL for this extension exclusively to fix this problem?

**Comment by lochmueller** [comment]
"Is there a way to disable RealURL for this extension exclusively to fix this problem?" I don't think so. The realurl alias table is invalid, if the event is saved with a new date. I will build a small test case at the weekend/next week at the T3BOARD...

**Comment by lochmueller** [comment]
Quick-fix: drop all RealURL information that points to calendarize entries. Clear the Frontend cache. Call the homepage and navigate to the event. I hope they build up in the correct way....

**Comment by j4k3** [comment]
Thanks for the swift reply.
For future reference, what helped was to execute this query, and then flush the Frontend Cache: 
`DELETE FROM `tx_realurl_urldata` WHERE `original_url` LIKE '%calendarize%'`

I still don't know whats going on, tho, because I don't think the dates for these event were changed. If theres anything I can do to further debug, just drop me a line.

**Comment by j4k3** [comment]
The error is now back on the same events as before. All events with multiple occurrences seem to have the same problem. 

The dates were not changed. In fact, nothing about the event nor the plugins was changed. The FronendCache of the page expired and was rebuilt.

Can I modify the extension to skip RealUrl creatation instead? I just need to get this working, I don't really care for the Urls.

**Comment by lochmueller** [comment]
Perhaps it is a option to disable the RealURL via extension configuration:
https://github.com/lochmueller/calendarize/blob/639c8eca647808be2c00a95f3d275f3234a074f9/Classes/Hooks/RealurlConfiguration.php
This should help in your case...

**Comment by lochmueller** [comment]
No more detail investigation here. Current TYPO3 Version (9.5) use a own "segment handling" for speaking URLs. So this is the focus
