### ISSUE TITLE
Access ContentObject in templates

### ISSUE THREAD

**Issue by napsio** [lochmueller/calendarize#209]
Is there any way to access the ContentObject in templates?

**Comment by lochmueller** [comment]
There are three information:
- data (the tt_content row)
- object (the Domain Modal)
- settings

What do you mean with "ContentObject"? The ContentObjectRenderer? or the current Model of the CE?

Regards,
Tim

**Comment by napsio** [comment]
I can't access "data" or "object" in the Month.html template. "data" is what I mean with ContentObject

There are the folowing variables:

- settings
- date
- indices
- extended

Regards,
napsio

**Comment by lochmueller** [comment]
Sorry for my last comment. Wrong extension in mind. Please ignore it.
I will check this at the weekend again...

**Comment by napsio** [comment]
Have you already checked this?

**Comment by lochmueller** [comment]
No news on this issue. I will check this and will comment here...
