### ISSUE TITLE
nice to have ordering for yearview

### ISSUE THREAD

**Issue by joka123** [lochmueller/calendarize#21]
$query->setOrderings([
            'start_date' => QueryInterface::ORDER_DESCENDING,
            'start_time' => QueryInterface::ORDER_DESCENDING,
        ]);
or like in indexRepository -> public function findByTraversing

**Comment by lochmueller** [comment]
All queries are sorted by the $defaultOrderings in the top of the class. The createQuery method check this variable and set the orderings directly. findByTraversing use the own orderings because the parameter are used to check if the ordering is ascending or descending.

So every query is sorted. Do you have an example? Can you check the result of the findYear? Perhaps it is a problem of the View?

**Comment by joka123** [comment]
i try to explain it with the following pictures
display with order descending (which i changed in the repository) - if 
there are more then one event at the day they should ordered desending


with the original code




Am 05.11.2015 um 18:16 schrieb Tim:
>
> All queries are sorted by the $defaultOrderings in the top of the 
> class. The createQuery method check this variable and set the 
> orderings directly. findByTraversing use the own orderings because the 
> parameter are used to check if the ordering is ascending or descending.
>
> So every query is sorted. Do you have an example? Can you check the 
> result of the findYear? Perhaps it is a problem of the View?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lochmueller/calendarize/issues/21#issuecomment-154126654>.
>

-- 
|-----------------------------------------------|
|* exmt - Büro für Programmierung und Design
|* jochen kast
|* hochstrasse 11
|* 90429 nürnberg
|* tel. 0911-3665916
|* fax. 0911-3665918
|* http://www.exmt.de
|-----------------------------------------------|

**Comment by lochmueller** [comment]
Hey @joka123 

I try to rebuild your situation, but my events (always on the same day in the year view) are always in the right order. I need same more details information i(e.g. debugging information). Furthermore there are no pictures attached...

Regards,
Tim

**Comment by joka123** [comment]
hey tim,
i have insert the pictures into the text, now they are in the 
attachment. maybe there is a misunderstanding. the events are allways in 
the correct dayes(everything is fine!) but when there are more then one 
event on a day they are ordered ascending, but i need them descending. 
that's all. so it's not really an issue. i write it will nice to have 
becuase then i have not to modify your sources.

all the best
jochen


Am 05.11.2015 um 19:48 schrieb Tim:
>
> Hey @joka123 <https://github.com/joka123>
>
> I try to rebuild your situation, but my events (always on the same day 
> in the year view) are always in the right order. I need same more 
> details information i(e.g. debugging information). Furthermore there 
> are no pictures attached...
>
> Regards,
> Tim
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/lochmueller/calendarize/issues/21#issuecomment-154150404>.
>

-- 
|-----------------------------------------------|
|* exmt - Büro für Programmierung und Design
|* jochen kast
|* hochstrasse 11
|* 90429 nürnberg
|* tel. 0911-3665916
|* fax. 0911-3665918
|* http://www.exmt.de
|-----------------------------------------------|

**Comment by lochmueller** [comment]
Add this option to the flexform.... Now you can select the order in the plugin.
