### ISSUE TITLE
control of a Calendarize object no longer seems to work

### ISSUE THREAD

**Issue by klabauterKoffer** [lochmueller/calendarize#210]
The frequency control of a Calendarize object no longer seems to work. A Monthly Recurring Event, always on the penultimate franchise does not generate recurring events in the calendar. But if you change to weekly, everything seems to work. How can that be done?

**Comment by lochmueller** [comment]
Hmm.... do you use a date like 2018-01-30? This date do not exist in Februar, so the date is "mixed". Is this the problem? What do you expect? Just the months with 30 days or e.g. switch to 29 (in februar)?

Regards,
Tim

**Comment by klabauterKoffer** [comment]
I give the following values:
General:
StartDate: 22.12.2017
EndDate: 22.12.2017
Start time: 15:30
End time: 18:00
Frequency: Monthly
Until date: 24.1.2020
Number: 25
Interval: 1
Repeat: penultimate
Day: Friday
Release dates and access rights
Start: 22.12.2017

Result:
There are 1 entry / entries in the index of the current record. The next 10 events (including today) are (ignored "enable columns") ...

     No events

In one of the previous versions that worked wonderfully too ...

**Comment by klabauterKoffer** [comment]
After  Fix #212 - Fix in_array check for strict variable types it works

**Comment by lochmueller** [comment]
Great... release will follow in the next days...
