### ISSUE TITLE
Monthly Interval doesn't work

### ISSUE THREAD

**Issue by jacques2017** [lochmueller/calendarize#212]
Hello, 
I try to set an event-interval every third wednesday in a month
But always I get only one index.
Can you test it?
I tried it with:
counter-interval:1
recurrence: monthly
day: wednesday (or every other day)
startdate: today
tilldate: 31.12.2018 or empty

Best Regards,
Jens

**Comment by lochmueller** [comment]
Found the bug in the current master. It was an invalid strict in_array check (so a type cast was missing). Fixed in current master... thanks for the report.
