### ISSUE TITLE
The ColumnMap for property "calendarize" of class "XXX\XXX\Domain\Model\Event" is missing.

### ISSUE THREAD

**Issue by etlam** [lochmueller/calendarize#214]
Hello Tim,

I used calendarize to calendarize my own Event Model and I am facing a weired issue.
I hope you can help me, as I already spent a whole day searching for the error.

I wrote a module where frontend users can manage their own events.
When I am using Typo3 (normally, looged in at frontend and backend at the same time) everything works as expected after clearing all caches.
Clearing the cache and browsing the page as frontend user in incognito tab results in an empty related calendarize-object (null) and when values of this object are used in a database query I get an error message: "The ColumnMap for property "calendarize" of class \XXX\XXX\Domain\Model\Event" is missing.

The really strange about the error:
The first impression after clearing the cache counts.
Frontend & backend user at the same time -> it works for all users, even the one in incognito tab
Frontend user in incognito tab -> for all future requests the related calendarize object is NULL

Caching is disabled for all frontend plugin actions and on the page the plugin is added to.

For me it looks like a problem with the column mapping.
But I did not figured out, how your column mapping works with autoloader and why it should not be working for a frontendUser.

Maybe you can provide any help or tips.

Thanks in advance
Malte

**Comment by lochmueller** [comment]
Hmm... sound line some missing TS configuration (or in the wrong file) of EXT:calendarize. I will check this in the next days...

**Comment by etlam** [comment]
This would be great.
If you need further informations or my source code I can provide it.

Is the problem maybe related to this breaking change (Breaking: #78384 - Frontend ignores TCA in ext_tables.php) in Typo3 8.5?
https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Breaking-78384-FrontendIgnoresTCAInExtTables.html

**Comment by lochmueller** [comment]
I will check this. Thanks for the hint.

**Comment by etlam** [comment]
Hello Tim,
could you please give some hints how you would try to debug this problem.
Thanks in advance
Malte

**Comment by lochmueller** [comment]
Hey Malte,

sorry I donot have enough time at the moment.
I think there is some missing TS for the extbase base domain mapping.
But i don't check this in detail yet....

Regards,
Tim
