### ISSUE TITLE
composer.json typo-version

### ISSUE THREAD

**Issue by dpfahlbusch** [lochmueller/calendarize#216]
Hey,
i think there is a typo in your composer.json.
instead of typo3-cms-core 7.6.13 it is 7.6.23

**Comment by lochmueller** [comment]
Thanks. fixed to "~7.6.13". So all 7.6.x versions since 13 are ok. I think there are some bugfixes in 7.6.13 that EXT:calendarize is needed... Thanks for the hint of the missing "~".
Regards,
Tim
