### ISSUE TITLE
Switching to next week doesn’t work

### ISSUE THREAD

**Issue by klodeckl** [lochmueller/calendarize#217]
I just wanted to test the extension and wanted to switch one week further, but no change, the url changes but the output not. Even when disabling the cache for the page it does not work. TYPO3 8.

**Comment by lochmueller** [comment]
Do you use the version 3.2.2 released on last Tuesday?

**Comment by lochmueller** [comment]
No feedback... fixed in current release: https://github.com/lochmueller/calendarize/commit/c6b6e738f051c8613d3276cb02ae32da5119c1d1

**Comment by klodeckl** [comment]
Sorry for my late. It seems it was not the latest version and config was not optimal, works now. Thanks!
