### ISSUE TITLE
Avoid TimeSelection.js in FE

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#219]
https://github.com/lochmueller/calendarize/blob/639c8eca647808be2c00a95f3d275f3234a074f9/Classes/Service/TimeSelectionWizard.php#L42
https://www.hdnet.de/blog/calendarize-der-etwas-bessere-typo3-kalender/#comment-40524

**Comment by klabauterKoffer** [comment]
Thank you for your very quick responce. I found my mistake. However, I'm not sure why the TimeSelectoin.js appeared in the frontend.
