### ISSUE TITLE
How can I customize frontend search

### ISSUE THREAD

**Issue by jacques2017** [lochmueller/calendarize#221]
In frontend I want search for events. But if the searchword match only the organizer or location the events are not found. How can I customize the search to search in location and organizer?

Best regards,

Jens

**Comment by lochmueller** [comment]
There is a Slot in the Repository functions to search of custom fields or foreign objects. You can use this slots...

Regards,
Tim

**Comment by lochmueller** [comment]
Note: Please use TYPO3 Slack for general questions/communication and the issue tracker only for issues.
