### ISSUE TITLE
Compatibility problems Typo3 7.6.24

### ISSUE THREAD

**Issue by vigger1980** [lochmueller/calendarize#222]
I have tried to include the extension on my site. The list view also worked without any problems. The following error always occurred in the detail view:
Argument 3 passed to 
HDNET\Calendarize\ViewHelpers\TitleTagViewHelper::renderStatic() 
must be an instance of 
TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface, instance of 
TYPO3\CMS\Fluid\Core\Rendering\RenderingContext given, called in 
/www/htdocs/XXXXXXXXXXXX/typo3_src-7.6.24/typo3/sysext/fluid/Resources/PHP/Traits/CompileWithRenderStatic.php on line 47

Tried with AutoLoader 3.0.0 & 3.2.0.

The Problem was solved after installing the Calendarize Extension in version 2.1.0 (the last one that does not support Typo3 8.x.x)

Greetz
Vigger

**Comment by lochmueller** [comment]
I know this problem. TYPO3 change this parameter to the orginal fluid class. I have no good solution for the old TYPO3. Best solution: Upgrade to 8.x ;)
I will keep this issue open... perhaps I found a nice solution in the next days...

**Comment by vigger1980** [comment]
I'm using tt_news too - and this plugin is not compatible with 8.x.

If you can recommend an alternative to tt_news, the old problem is obsolete :)
The last update date of tt_news suggests that I should be looking for something new anyway....

**Comment by lochmueller** [comment]
It is recommended to switch vom EXT:tt_news to EXT:news.

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @vigger1980 ,

there will be no new 7.x release. Please use a older version or update the TYPO3 to 8.x.
Sorry...

Regards,
Tim
