### ISSUE TITLE
search results on page 2

### ISSUE THREAD

**Issue by kan0ne** [lochmueller/calendarize#223]
Hello,

i have a strange behavior on my side.
steps to follow:
1. search for events between two dates (in my case 10.05.2018 - 18.05.2018)
2. more results than 10, so there is a pagination
3. go to 2nd page of the results
4. im on the 2nd page but the startdate/enddate inputs are reseting to (21.03.2018 - 21.04.2018)
5. and the results on that 2nd page are also between that date and not the one i am searching for

the same is happening when i search for a word, going to second page resets the search.
can someone confirm this behavior, or is it because of changing the templates?

im using:
- TYPO3 8.7.11
- calendarize 3.2.2

greetings martin

**Comment by kan0ne** [comment]
hello again,

i tested it again on an clean TYPO3 8.7.9 installation with calendarize 3.2.2
ang got the same results.

the search resets when switching to another page.

greetings martin

**Comment by kan0ne** [comment]
any news?

**Comment by lochmueller** [comment]
Hey @kan0ne 
there are no news on this topic so far.
I will check this in the next days/week.
Regards,
Tim

**Comment by BebeBarron** [comment]
Hello Tim,

we still face the issue which Martin described on 21.03.

Did the new Version 3.2.5. fix this issue?

We are now on TYPO3 8.7.11 so to update your extension we have to first update the TYPO3.

Thanks and best regards,
Christiane

**Comment by lochmueller** [comment]
@BebeBarron All versions are compatible to TYPO3 8.7.x. I think you use a old PHP version, right?

**Comment by BebeBarron** [comment]
In the meanwhile updating to 3.2.5. works... But the issue still exists...

Hmh PHP Version is 7.0.31. we can think about updating this too.

But still our question: Is there a fix for the described issue?

**Comment by lochmueller** [comment]
Hey @BebeBarron 
no. I have to check this issue... i will send you feedback shortly.
Regards,
Tim

**Comment by chrissonntag** [comment]
**Solution**: Overwrite <code>EXT:calendarize/Resources/Private/Partials/List.html</code> and add <code>addQueryStringMethod: 'GET,POST'</code>  to the pagination widget configuration.
See
<code>
<f:widget.paginate objects="{indices}" as="paginatedIndices" configuration="{itemsPerPage: 10, insertAbove: 1, insertBelow: 1, maximumNumberOfLinks: 10, addQueryStringMethod: 'GET,POST'}">
</code>
Nevertheless caching of listAction could also be an issue. If you like to disable it, make sure that calendarize is being loaded before your own customized extension (<code>ext_emconf.php</code>) and put the following code into your <code>ext_tables.php</code>
<code>
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['extbase']['extensions']['Calendarize']['plugins']['Calendar']['controllers']['Calendar']['nonCacheableActions'][] = 'list';
</code>

@lochmueller Couldn't you just add <code>addQueryStringMethod: 'GET,POST'</code> by default, respectively even better put the whole pagination configuration into <code>{settings}</code> making it possible to configure it via TypoScript?

**Comment by j4k3** [comment]
Chimimg in with @chrissonntag , the correct way to integrate pagination into searchable lists is to restore the arguments by recreating them in the query string. This will work for most use cases unless the serialized parameters get too long to transfer via a GET request.
