### ISSUE TITLE
Fatal error in FE due to missing partial Template

### ISSUE THREAD

**Issue by angeloprevitali** [lochmueller/calendarize#224]
By installing your extension EXT:calendarize version 3.2.2 and TYPO3 CMS version 8.7.12 and configuring it as described and adding some items by opening the FE there is an Fatal Error due to a missing Template in the Partials.

Fatal error: Uncaught TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException: The Fluid template files "/fileadmin/templates/calendarize/Partials//Title.html", "/fileadmin/templates/calendarize/Partials//Title", "/typo3conf/ext/calendarize/Resources/Private/Partials//Title.html", "/typo3conf/ext/calendarize/Resources/Private/Partials//Title" could not be loaded. in /vendor/typo3fluid/fluid/src/View/TemplatePaths.php:722 Stack trace: #0 /vendor/typo3fluid/fluid/src/View/TemplatePaths.php(691): TYPO3Fluid\Fluid\View\TemplatePaths->resolveFileInPaths(Array, '/Title') #1 /typo3/sysext/fluid/Classes/View/TemplatePaths.php(180): TYPO3Fluid\Fluid\View\TemplatePaths->getPartia in /vendor/typo3fluid/fluid/src/View/TemplatePaths.php on line 722 

Can you fix that?

I think, that the url of the Partial Template in your extension somewhere is wrong. As I see TYPO3 would like to open a PArtial in 

/typo3conf/ext/calendarize/Resources/Private/Partials//Title.html

but it doeas NOT exisit. The file mentioned is leading in another folder so the folder construct of the templates seems to be wrong.

Thanks.

Best regards,
Angelo

**Comment by lochmueller** [comment]
Do you use the "default" Event model? Why the configuration have no valid partialIdentifier:
https://github.com/lochmueller/calendarize/blob/09f99756e9b0dee963f8ccce27310271f882bfdd/Resources/Private/Partials/Event/ListItem.html#L19
Please run some debugging in the template. Do you update and old version and have some old templates?
Regards,
Tim

**Comment by angeloprevitali** [comment]
> Do you update and old version and have some old templates?
It is a brandnew installation. I never installed it before.

**Comment by lochmueller** [comment]
You have to check this error by yourself. I cannot recreate this situation. The path "Resources/Private/Partials//Title.html" is wrong because there is a missing folder name ("//") for the "partialIdentifier". But I cannot rebuild this problem. Please run some debugging in your DEV system...

**Comment by lochmueller** [comment]
No feedback. I close this issue.
If there is a "//" in the URL, there is a missing partial configuration or TS.
Should not happen with the default event structure..

Regards,
Tim

**Comment by blueamerican** [comment]
calendarize 4.1.3, TYPO3 8.7.24
I have the same error in backend, when clicking on the calendarie module:

Uncaught TYPO3 Exception
#1225709595: The Fluid template files "/www/44/rp-hosting/5144065/6144065/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials//Title.html", "/www/44/rp-hosting/4065/61440/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials//Title" could not be loaded.

If i delete the file
typo3conf\ext\calendarize\Resources\Private\Partials\Event\Title.html

i get this error:
#1225709595: The Fluid template files "/www/415637_70794/rp-hosting/5144065/6144065/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials/Event/Title.html", "/www/415637_70794/rp-hosting/5144065/6144065/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials/Event/Title" could not be loaded.

the last error is correct, but the first error i do not understand.
The reason for this is not a missing partialIdentifier.

**Comment by lochmueller** [comment]
@blueamerican 
The Title partial is always called by the templates. Please debug the index element in front of the <f:render partial="...Title" />
Regards,
Tim

**Comment by blueamerican** [comment]
ah.. this is interesting:
after replacing "{index.configuration.partialIdentifier}" with "Event" in 
typo3conf\ext\calendarize\Resources\Private\Partials\Backend\Row.html

there comes this error:
#123678123: No valid configuration for the current index: CalextendedEvent 

CalextendedEvent is my own event model, but i have deinstalled this extension in order to fix the bug.
From where does this error come? The extension is deinstalled..

**Comment by lochmueller** [comment]
@blueamerican 
You could check, why "partialIdentifier" is empty in "configuration" or why the event cannot load the configuration. I need some technical details. I think you register you own event in the wrong way. Do you call the registration in ext_tables and ext_localconf with the same configuration array like this:  https://github.com/lochmueller/calendarize/blob/master/Classes/Register.php#L77

**Comment by blueamerican** [comment]
this is from my register.php:

    ```

public static function getDefaultCalendarizeConfiguration(): array
    {
        $configuration = [
            'uniqueRegisterKey' => 'CalextendedEvent', // A unique Key for the register (e.g. you Extension Key + "Event")
            'title'             => 'Calextended Event', // The title for your events (this is shown in the FlexForm configuration of the Plugins)
            'modelName'         => \MarkusDuebbert\Calextended\Domain\Model\Event::class, // the name of your model
            'partialIdentifier' => 'CalextendedEvent', // the identifier of the partials for your event. In most cases this is also unique
            'tableName'         => 'tx_calextended_domain_model_event', // the table name of your event table
            'required'          => true, // set to true, than your event need a least one event configuration
            //'subClasses'        => array of classnames, // insert here all classNames, which are used for the extended models
            'subClasses'        => array(),
        ];

        return $configuration;
    }

```

and this is the actual message i get when clicking the backend module:
"/www/415637_70794/rp-hosting/55/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials/CalextendedEvent/Title" could not be loaded.

Is my partialIdentifier wrong?
must it be "Event"?

**Comment by lochmueller** [comment]
Hmm... looks right. How do you add the Partial Path to the partialRootPaths in TS?

**Comment by blueamerican** [comment]
I have these new constants:
plugin.tx_calendarize.view.partialRootPath = EXT:calextended/Resources/Private/Extensions/Calendarize/Partials/

this works fine for my FE templates.
But in BE i get this error:
#1225709595: The Fluid template files "/www/415637_70794/rp-hosting/55/typo3cms/muster82/typo3conf/ext/calendarize/Resources/Private/Partials/CalextendedEvent/Title.html" could not be loaded

Why is the Title.html see screen above not used?
Are you sure, that there is no error in code?

**Comment by lochmueller** [comment]
Do you create a ext_typoscript_setup.txt file in your extension (extension root folder)? TS for Backend use the own templates paths. E.g.
```
module.tx_calendarize {
  view {
    partialRootPaths {
      300 = EXT:site/Resources/Private/Extension/calendarize/Partials/
    }

    layoutRootPaths {
      300 = EXT:site/Resources/Private/Extension/calendarize/Layouts/
    }

    templateRootPaths {
      300 = EXT:site/Resources/Private/Extension/calendarize/Templates/
    }
  }
}
```

**Comment by blueamerican** [comment]
ahh. that's it... thank you Tim.. my fault.
