### ISSUE TITLE
Bug by primary installing extension 3.2.2 due to wrong SQL commands

### ISSUE THREAD

**Issue by angeloprevitali** [lochmueller/calendarize#225]
Hello

if you make a fresh install of the EXT:calendarize verison 3.2.2 you can not create new items because of

1. by installing the extension the missing mySQL fields and tables gets NOT created (you got to make a compare in the install tool to create them!)
2. By doing a compare in the install tool there werde some mySQL Queries that can be NOT executed du to wrong formats. 

The following tables CAN NOT BE created or modified:

`ALTER TABLE `tx_calendarize_domain_model_event` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_event` ADD PRIMARY KEY (uid)
ALTER TABLE `tx_calendarize_domain_model_index` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_index` ADD PRIMARY KEY (uid)
ALTER TABLE `tx_calendarize_domain_model_pluginconfiguration` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_pluginconfiguration` ADD PRIMARY KEY (uid) `

Can you fix that asap?

Regards,
Angelo

**Comment by lochmueller** [comment]
Hey @angeloprevitali 
The tables already exists otherwise TYPO3 would't create this "Add" queries. Please uninstall the extension, drop the tx_calendarize_* tables and install the extension again.

Regards,
Tim

**Comment by angeloprevitali** [comment]
Hi Tim

that's what I did but without success. It seems that mySQL "caches" somehow the bad tables.. Is there any other solution? Normally it shouldn't happen, right? At least i never had a such a strange thing like this. I tried to install the extnesion to an brandnew TYPO3 and on this one NO tables gets created after installing. I had to make a compare to create the tables. Unusual..

Thanks for helping me out.

Regards,
Angelo

**Comment by lochmueller** [comment]
Strange. It is accually a error of EXT:autoloader and not calendarize. Autoloader use the Model-Table-Mapping mechanisms and tabel structures. I will check this in the next week... Regards, Tim

**Comment by lochmueller** [comment]
Hey @angeloprevitali 
I restup my test system and cannot rebuild this issue... Do you have some more information?
Do you drop the tables, deinstall the extension and after the installation the tables are still corrupt?
Regards,
Tim

**Comment by angeloprevitali** [comment]
Hi Tim
YES. I tried this on three different installations of a TYPO3 CMS verson 8.7.13 on a LINUX OS with PHP 7.1.
There is NO chance to make a compare after installing the extension. See https://github.com/lochmueller/calendarize/issues/225#issue-312416375 due to a wrong SQL syntax.
And - YEs, it is a brandnew blank installation of your extension I tried.
Any other hints?
Regards,
Angelo

**Comment by lochmueller** [comment]
You have to check this error also by yourself. I cannot recreate this situation. The autoloader extension create the complete table (including the uid). So there is no "ALTER TABLE" of primary fields after that... Could you run some debugging on your DEV machine?

**Comment by lochmueller** [comment]
I close this issue.
