### ISSUE TITLE
get title of event

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#226]
Hi,
I use TYPO3 8.7.13 and calendarize 3.2.2.
With this TS I want to add the current event title on top of my menu but I don't get it.

	lib.mobileMenu = COA
	lib.mobileMenu {		
		50 = RECORDS
		50 {
			stdWrap.if.isTrue.data = GP:tx_calendarize_calendar|index
			dontCheckPid = 1
			tables = tx_calendarize_domain_model_event
			source.data = GP:tx_calendarize_calendar|index
			source.intval = 1
			conf.tx_calendarize_domain_model_event = TEXT
			conf.tx_calendarize_domain_model_event {
				field = title
				htmlSpecialChars = 1
			}
		}
		60 = HMENU
		(...)
    }

Thanks for any hint.
Regards
Hobokens

**Comment by lochmueller** [comment]
Hey @Hobokens 
RECORDS is not possible, because the ID is not the ID of the event table - it is the ID of the index.
I Build a CONTENT select incl. a join between the event and the index table
```lib.eventTitle = CONTENT
lib.eventTitle {
    table = tx_calendarize_domain_model_event
    select {
      pidInList = XXXXXX
      selectFields = tx_calendarize_domain_model_event.*
      join = tx_calendarize_domain_model_index ON tx_calendarize_domain_model_event.uid = tx_calendarize_domain_model_index.foreign_uid AND tx_calendarize_domain_model_index.foreign_table="tx_calendarize_domain_model_event"
      where.data = GP:tx_calendarize_calendar|index
      where.intval = 1
      where.wrap = tx_calendarize_domain_model_index.uid=|
    }
    renderObj = TEXT
    renderObj.field = title
    renderObj.htmlSpecialChars = 1
}

page.1000 < lib.eventTitle
page.1000.wrap = <h3>|</h3>
```
Please replace the "XXX" with the PID of your storge and check it in your HMENU context.

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @Hobokens 
do you try it without the HMENU to avoid problems related to the HMENU TS.
Please try page.99999 < lib.eventTitle first. Please take care that you init the the lib with "lib.eventTitle = CONTENT". It was missing in my example also ;)
Regards,
Tim

**Comment by Hobokens** [comment]
Hi Tim,
the missing
`lib.eventTitle = CONTENT`
caused the problem. Now everything is perfect.
Thanks a lot for your support.

Regards
Hobokens
