### ISSUE TITLE
No localized events are shown in detail view of events

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#236]
There seems to be problem with the translation handling of events in TYPO3 8.7.16 with calendarize 3.2.5. when switching the language in an ebent detail view.
The system is configured something like this:
config {
  language = de
  htmlTag_langKey = de
  sys_language_overlay = 1
  sys_language_uid = 0
  locale_all = de_DE.utf8
}
[globalVar = GP:L = 1]
config {
  sys_language_uid = 1
  language = cn
  locale_all = zh_CN.utf-8
  htmlTag_langKey = zh-cn
  sys_language_overlay = 0
}
[global]
Problem is  when switching the language with a simple languageMenu there is only shown the date and no content. 
The URL contains an index like e.g. tx_calendarize_calendar[index]=4547

--> when looking in the database the foreign_uid is the uid of the actual shown event and not the translated, so there's no relation to the localized and translated event

can you confirm that or do you have a solution?

**Comment by lochmueller** [comment]
New option in current master should prevent this situation 👍
