### ISSUE TITLE
Exeption from IndexRepository: mktime() expects parameter 4 to be integer, string given

### ISSUE THREAD

**Issue by zwenn** [lochmueller/calendarize#237]
on line 339 in public function findDay($year, $month, $day)

Calling from CalendarController in line 339 submits the parameter as string

This Solution works for me:
IndexRepository on line 337 
$startTime = \mktime(0, 0, 0, (int) $month, (int) $day, (int) $year);

Typo3 8.7.17, PHP7.2.1,calendarize 3.2.5

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master.... 👍
