### ISSUE TITLE
CoolUri:  Special characters in title tag

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#238]
Hi Tim,
I have a problem with some special characters like ' or " in the title tag.  I first asked on [stackoverflow](https://stackoverflow.com/questions/51601868/typo3-special-characters-in-title-tag) before I realized that the problem is related to CoolUri and calendarize. It would be nice to have a solution for the unattractive rendering of the title. Thanks for any help.
Regards
Hobokens

**Comment by lochmueller** [comment]
Do you test this function:
https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/TitleTagViewHelper.php#L31

This is the only location where the page title is set by calendarize. It is the same ViewHelper as EXT:news is used. but perhaps we should add this format viewHelper in the Template also:
https://github.com/georgringer/news/blob/master/Resources/Private/Templates/News/Detail.html#L21

Could you try this and send me some feedback?!

Regards,
Tim

**Comment by Hobokens** [comment]
Hi Tim,
I have added the 'f:format.htmlentitiesDecode Viewhelper' but this doesn't solve the problem;
    `<c:titleTag>`
       `<f:format.htmlentitiesDecode>`
            `<f:render partial="{index.configuration.partialIdentifier}/Title" arguments="{index: index}"/>`
        `</f:format.htmlentitiesDecode>`
    `</c:titleTag>`

BTW within the news extension the problem doesn't exist.

Regards
Hobokens

**Comment by lochmueller** [comment]
Hmmm.... strange. Could you run same tests? Output of the title variable etc.

**Comment by Hobokens** [comment]
If I write
```
<c:titleTag>
<f:format.htmlentitiesDecode>
{index.originalObject.title}
</f:format.htmlentitiesDecode>
</c:titleTag>
```
the title tag is fine, with
```
<c:titleTag>
<f:format.htmlentitiesDecode>
<f:render partial="{index.configuration.partialIdentifier}/Title" arguments="{index: index}"/>
</f:format.htmlentitiesDecode>
</c:titleTag>
```
I have the described problem.
Regards
Hobokens

**Comment by lochmueller** [comment]
I close this issue... no more power into realurl and cooluri integration. Focus on TYPO3 9.x URl handling.
