### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by derhalbbrite** [lochmueller/calendarize#239]
Typo3 8.7.17

Installation went fine.
After adding that plugin to the pages content this appeard:
Unknown column 'tx_calendarize_domain_model_pluginconfiguration.uid' in 'field list'. Es ist ein SQL-Fehler aufgetreten. Dies kann auf eine Schema-Abweichung zwischen TCA und der Datenbank hindeuten. Versuchen Sie im Install Tool einen Datenbank-Vergleich durchzuführen.

**Comment by lochmueller** [comment]
Please uninstall and reinstall the extenion and please check the DB compare. Does the "tx_calendarize_domain_model_pluginconfiguration" table exists? Which extension are installed in your env? Do you use composer based setup?

**Comment by lochmueller** [comment]
No feedback since no. I test the process with the current masters (versions will be released in the next 2 days). no problems... please try a reinstall of the extension at the end of the week or send us some more detailed information
