### ISSUE TITLE
Wrong date in month view after change from summer time to winter time

### ISSUE THREAD

**Issue by dbfischer** [lochmueller/calendarize#240]
After 28th October (change from summer time to winter time) in month view all events are shown one day earlier, e.g. Allerheiligen is 31.10.2018 and not 01.11.2018. The week normally begins with Monday. After 28th October it begins with Sunday.
Latest Version 3.2.5 installed.
TYPO3 8.7.17

**Comment by dbfischer** [comment]
Solved ... there was no static template included.
No idea why this happend ... sorry.

**Comment by lochmueller** [comment]
👍
