### ISSUE TITLE
End date not optional

### ISSUE THREAD

**Issue by hasenbalg** [lochmueller/calendarize#241]
While evaluating your extension I got the following error:

> 2: SQL error: 'Incorrect integer value: '' for column 'end_date' at row 1' (tx_calendarize_domain_model_configuration:NEW5b8542f5aae32629804128)

I left the End date field and the End time field empty. Both should be optional.

Leaving only the End time filed empty the error is similar:
> 2: SQL error: 'Incorrect integer value: '' for column 'end_date' at row 1' (tx_calendarize_domain_model_configuration:NEW5b854197d5581458599965)
 

I am using MySQL 5.7.23 and TYPO3 8.7.18

**Comment by lochmueller** [comment]
@hasenbalg Do you use MySQL in strict mode?
