### ISSUE TITLE
use the new linkhandler with CoolUri

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#243]
Hi,
I use TYPO3 8.7.19. 
With the following TS the events are shown in the link browser
```
TCEMAIN.linkHandler.tx_calendarize {
	handler = TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler
	label = Calendarize
	configuration {
		table = tx_calendarize_domain_model_event
		storagePid = 143
		hidePageTree = 0
	}
	scanAfter = page
}
```
To resolve the link in the frontend I add

```
config.recordLinks.tx_calendarize {
	typolink {
		parameter = 134
		additionalParams.data = field:uid
		additionalParams.wrap = &tx_calendarize_calendar[index]=|
		useCacheHash = 1
	}
}
```
The generated link is

`https://www.mydomain.org/termine/veranstaltungskalender/idx-712.html`

instead of the link which is generated by CoolUri:

`https://www.mydomain.org/termine/veranstaltungskalender/name-of-the-event-year-month-day-hour-minute.html`

**Comment by lochmueller** [comment]
There is a small Cooluri helper for the alias: https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst

The problem in your configuration is, that you select a "Event" in the Backend and Link to an "Index" in the frontend. But ID 1 for the Event is NOT ID 1 for the Index. So there is some "mix up" in the configuration.

One solution could be
```
config.recordLinks.event {
	typolink {
		parameter = {$pid.eventDetail}
		additionalParams.data = field:uid
		additionalParams.wrap = &tx_calendarize_calendar[index]=|
		additionalParams.preUserFunc = TEST\Site\Service\EventLinkHandler->parseLinkHandlerTypolink
		useCacheHash = 1
	}
}
```

An a function that resolve the right index
```


    /**
     * Get the right Index ID by the event ID
     *
     * @param int $eventId
     *
     * @return int
     */
    protected function getIndexIdByEventId(int $eventId): int
    {
        $objectManager = new ObjectManager();

        /** @var EventRepository $eventRepository */
        $eventRepository = $objectManager->get(EventRepository::class);

        /** @var Event $event */
        $event = $eventRepository->findByUid($eventId);

        if (!is_object($event)) {
            return 0;
        }

        /** @var IndexRepository $indexRepository */
        $indexRepository = $objectManager->get(IndexRepository::class);

        try {
            $result = $indexRepository->findByEventTraversing($event, true, false, 1, QueryInterface::ORDER_ASCENDING);
            if (empty($result)) {
                $result = $indexRepository->findByEventTraversing($event, false, true, 1, QueryInterface::ORDER_DESCENDING);
            }
        } catch (\Exception $ex) {
            return 0;

        }

        if (empty($result)) {
            return 0;
        }

        /** @var Index $index */
        $index = $result[0];
        return (int)$index->getUid();
    }
```

As result. The link link always to the next event. If there are no events in the feature the link point to the last item in the past.

Regards,
Tim

**Comment by Hobokens** [comment]
Many thanks Tim for your detailed answer. I will check it out.

**Comment by lochmueller** [comment]
I added the method to the extension: https://github.com/lochmueller/calendarize/commit/cb41b9f0f37fc2e9b472b81096f80f38c04ed2d2
Will be part of the next release.

**Comment by Hobokens** [comment]
thanks  a lot :-)

**Comment by wazum** [comment]
@lochmueller  I can't understand how a protected method added to the extension should help anyone here?
https://github.com/lochmueller/calendarize/blob/4df0581802b63fa1099df302a9d215ccffed5d72/Classes/Domain/Repository/EventRepository.php#L68

**Comment by lochmueller** [comment]
Hey @wazum 
The method is public in next release. 

Please create a new issues next time. 
It is easier in the development workflow...
Regards,
Tim
