### ISSUE TITLE
Doctrine tries parsing Annotations

### ISSUE THREAD

**Issue by PascaleBeier** [lochmueller/calendarize#250]
Doctrine throws an AnnotationException when loading TCA from autoloader, resulting in missing TCA Configuration

```
(1/1) Doctrine\Common\Annotations\AnnotationException
[Semantical Error] The annotation "@db" in property HDNET\Calendarize\Domain\Model\Configuration::$type was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

coming from upstream https://github.com/lochmueller/autoloader/issues/123

**Comment by lochmueller** [comment]
Is fixed with EXT:autoloader 6.0.2

Thanks for the report,
Tim
