### ISSUE TITLE
How do you set storagePid per PluginConfiguration Model?

### ISSUE THREAD

**Issue by PascaleBeier** [lochmueller/calendarize#254]
In TYPO3 v9, there doesn't seem to be a way to set storagePid per PluginConfigurationModel other than manipulating the Database Entry manually - or am I missing something?

**Comment by lochmueller** [comment]
Current situation:
- EXT:calendarize/Configuration/TCA/tx_calendarize_domain_model_pluginconfiguration.php Line 85 + 89
Reason:
- It is tricky to override the stroagepage in PluginConfigurationService
