### ISSUE TITLE
does not render with stock bootstrap_package

### ISSUE THREAD

**Issue by christen90** [lochmueller/calendarize#255]
got errors until I included fluid_styled_content. If calendarize depends on that template it should be listed in install instructions.

TYPO3 9.5.0
PHP Version 7.2.10
Bootstrap Package 10.0.2

**Comment by lochmueller** [comment]
Hey @christen90 Could you send me the error? This would help me to help you ;)

**Comment by lochmueller** [comment]
Furthermore which version of EXT:autoloader and EXT:calendarize do you use? The releases of today? 6.0.2 and 4.0.1?

**Comment by christen90** [comment]
Hey @lochmueller I used the newest releases.

typo3 is not very specific with its debug messages.
Oops, an error occurred! Code: 201810102210561eba5ebc

WARNING | TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher | Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign.

**Comment by PascaleBeier** [comment]
Can't reproduce on master

**Comment by lochmueller** [comment]
Perhaps it is the order of the static templates in TS? Does Boostrap Package drop "tt_content >" in TS, after the extension register the plugins?

**Comment by rumpfwerk** [comment]
Had some issues
TYPO3 9.5.0
Bootstrap Package 10.0.2

After installing and Template in and Database comparison:
Editing a "Ereignis":
1. The field "description" the RTE is not rendering (only one line input field)
2. In the Tab "Zugriff" the Words "Verbergen:" and "erfordert Admin-Rechte" and "Start" "Stopp" are missing in german Words. There ist shown nothing.

**Comment by rumpfwerk** [comment]
tried to reproduce the error of @christen90 by deinstalling "fluid styled content"
no error, independent of the position in TS-Incluge (begin, end)

**Comment by PascaleBeier** [comment]
Your second issue is an easy patch, it's just a relocation of language
files 😊

Am 11.10.2018 17:38 schrieb "rumpfwerk" <notifications@github.com>:

tried to reproduce the error of @christen90 <https://github.com/christen90>
by deinstalling "fluid styled content"
no error, independent of the position in TS-Incluge (begin, end)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/lochmueller/calendarize/issues/255#issuecomment-429002671>,
or mute the thread

**Comment by lochmueller** [comment]
Hmm... @christen90 we need more information (loading order TS, all installed extensions, etc.). the plugin is registerd in the ext_localconf.php of calendarize and there is no way arround it...

**Comment by christen90** [comment]
I could solve the problem with remove (Bootstrap Package: Content Elements ...) from the included Items.

Thank you very much.
