### ISSUE TITLE
ics imported events does not render in frontend

### ISSUE THREAD

**Issue by christen90** [lochmueller/calendarize#256]
Config group configured as external import. Example ics: https://calendar.google.com/calendar/ical/k1qup3avua092vkpq283e7tjr4%40group.calendar.google.com/public/basic.ics

Event configured as group. When pushing save the times are listed (import works)
Plugin configuration: "Calendarize Event" is ticked and PIDs are set

Plugin configuration (content):
List
Plugin Configuration is selected
Starting point is set to the sysfolder where the events, plugin config and config groups are saved.

TYPO3 Version 9.5.0
PHP Version 7.2.10
Bootstrap Package 10.0.2

**Comment by lochmueller** [comment]
This problem is fixed in current version: https://github.com/lochmueller/calendarize/commit/4565704e8a6ea6f91e36ff82c690de1f4a8697b8

The items was created on the wrong page. This is the reason, why the events are not selected in the frontend...
