### ISSUE TITLE
Plugin FlexForm TCA not fully loaded

### ISSUE THREAD

**Issue by PascaleBeier** [lochmueller/calendarize#257]
TCA on some FlexForm fields seems missing on current master as well.

![rte](https://user-images.githubusercontent.com/2736518/46788109-c9f66c00-cd39-11e8-84e1-6676774a11cc.png)
Description is expected to be an RTE field

![tca](https://user-images.githubusercontent.com/2736518/46788141-dd093c00-cd39-11e8-9421-d766b5b9c70e.png)
Missing enableRichText config key

**Comment by rumpfwerk** [comment]
Had same problem.

**Comment by lochmueller** [comment]
Hey... this bugfix solve the problem. Please upgrade EXT:autoloader to 6.0.3
https://github.com/lochmueller/autoloader/commit/51e71a6589edd35e336daa720f03e89c3c9e6a3e

Regards,
Tim

**Comment by nom10s** [comment]
The problem reappeared in my case. 
autoloader 6.0.5 
calendarize 4.1.0
Best regards
Stefan

**Comment by lochmueller** [comment]
Hmm... strange. This is not a calendarize bug it is a autoloader problem: https://github.com/lochmueller/autoloader/issues/132
