### ISSUE TITLE
Highlighting in calendar only respects start_date - not ranges defined with start_date and end_date

### ISSUE THREAD

**Issue by c2po** [lochmueller/calendarize#26]
Hi,

if there is an event that lasts more than one day I should enter a start_date and an end_date and the frequency should be none. But I also could also enter only a start_date and a till_date with frequency daily, which causes the creation of many events. The calendar highlights every day in range but list view will become unreadable (on event for every day).

Couldn't the IndexOnDayViewHelper not only test start_day but instead the range between start_date and end_date (maybe as option)?

(sorry, only looked at version 1.7.1 and actual changelog)

**Comment by lochmueller** [comment]
Hey @c2po 
I hope I got you message right ;) The VH check now the dates in the range right, so also frequency events are displayed on each day. If you do not like the "repeat" of the events in the view, than it is recommended to enable the calendar.io function in TS (experimental).
Regards,
Tim

**Comment by c2po** [comment]
Hi Tim,
thank you for the info. This feature is only available here in the master. I could see the highlighting  of a multi-day event in the calendar. The list view was correct for a selected start_date or end_date.

But selecting a day in the calender between start_date and end_date did not show up the event in the list view.
