### ISSUE TITLE
Show events from url and "internal" events doesn´t work

### ISSUE THREAD

**Issue by MichiBeck** [lochmueller/calendarize#263]
Hi, I try to show a year calendar including a group of holidays grabed from schulferien.org and own events. 

It only shows the external events and not the own I created. I tried every setting without success.
Only whean I change the plugin general config setting to take the startingpoint from my record storage it takes the onwn events but not the external. It´s a bit confusing - is this a bug or a misconfiguration?
![calendarize1](https://user-images.githubusercontent.com/15154464/47709442-86a06680-dc30-11e8-948d-76768554cb2e.png)

`TYPO3 8.7.19 | calendarize 4.0.1`

Thank you in advance! I really like this extension!!!

**Comment by lochmueller** [comment]
Does the groups display the right teim slots in the Info field in the "edit" view? If there is no info in the backend, it is a ICS fetch problem. Do you switch the order of the groups in the Event. Perhaps the problem is, that only the first group is used?!

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @MichiBeck 

there are no news at the moment, so there was no time to check this problem.
If there are any news, I will update this issue here... 👍 
Feel free to send a pull request, if you found the problem by yourself...

Regards,
Tim

**Comment by MichiBeck** [comment]
Hi again, 
it looks like if I load events over "Startingpoint" it shows only internal events (self created, all day events). 
When I choose a "Record Storage Page" it only shows my external loaded events. But never both together in the list, month or year view.

**Comment by lochmueller** [comment]
Do you handle the "internal" and "ICS events" in the same stroage folder? Sound strange... could you check the "index" table and check, if the index records are on the right PageID for your plugin? The index records are created on the same PID as the parent Event (internal and also external)...

**Comment by MichiBeck** [comment]
Yes, I handle them in the sam storage folder. Shouldn´t I?

Ah, it looks like they all have pid 0 execpt the first two:

![calendarize index table](https://user-images.githubusercontent.com/15154464/49785299-6af4a980-fd20-11e8-9752-8c7623609fd3.png)

Could this be the reason?

**Comment by lochmueller** [comment]
Yes... this could be the reason. Do you try to run the "reIndex" Scheduler task? Perhaps the task fix this problem?!
Same Storgae is fine... seems the Index location is the problem.

**Comment by lochmueller** [comment]
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/ExternalTimeTable.php#L61
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/TimeTimeTable.php#L36
Hmm... could you try to use also "$configuration->getPid()" as PID for the external class and save the records in the backend again (or use the scheduler)

**Comment by MichiBeck** [comment]
Give me a second please... 
I´ll try `$configuration->getPid()` and reindex

**Comment by lochmueller** [comment]
Fixed the problem in current master.

You get the Index and Event Model in the different views. You could override the template and add the HTML to fit your needs.

**Comment by MichiBeck** [comment]
Thanks a lot! Great!
OK, I´ll try to output the id...
