### ISSUE TITLE
BE Module for editors

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#268]
Create a BE Module for editors, based on the index records, so the events are chronologic in the right order. The links should jump to the regular edit mask of the events.

Example: EXT:news BE module

**Comment by Forestsoft-de** [comment]
oh yeah +1

**Comment by lochmueller** [comment]
First commit incl. a indexed based backend module.
Missing features:
- Disable the module by extension configuration
- Start the module on current date page

**Comment by sdesign6** [comment]
Nice! Cool missing feature!
I tried to test this feature in the new version, but I get the following error, when trying to access the new backend module: 
Oops, an error occurred!
Call to a member function findAll() on null
TYPO3 8.7.20, calendarize master, autoloader 6.0.5 (PHP Version 7.1.16)

**Comment by lochmueller** [comment]
Do you try to deleted the system cache? If "findAll" is called on a "non-object" the dependency injection on the controller is missing, that could be a problem of the reflection cache (System cache).

Regards,
Tim

**Comment by sdesign6** [comment]
I cleared the Caches in Install-Tool: "Clear all caches" and "Dump Autoload Information". After that I cleared "Frontend Caches" and "All Caches" from backend. Also login in and out serveral times.
Then I deinstalled calendarize, installed new mater, cleared all caches again - same error

**Comment by lochmueller** [comment]
Problem is fixed in the next version: https://github.com/lochmueller/calendarize/commit/b092aa0cba0f743ec15bfe15dc785eae9938d766

**Comment by blueamerican** [comment]
is there a possibility to overwrite the function findAllForBackend()
in indexRepository.php?

i need the (missing) feature:

backend list view:
show only events from today as start_date
sort by start_date
