### ISSUE TITLE
Wrong startDate and endDate in model Index

### ISSUE THREAD

**Issue by nowaythatworked** [lochmueller/calendarize#271]
When creating a new Event the startDate and endDate from the index is one day before the actual event. Also when you create repeating events, the "next 10" are wrong. If I start an event on a Saturday all other weekly events will be on friday.

**Comment by lochmueller** [comment]
Do you check the DB field values and also your timezones settings? Do you use UTC?

**Comment by nowaythatworked** [comment]
The problem came from the ddev time settings. It works fine on my server. Thanks.

**Comment by lochmueller** [comment]
ok. I will close this issue...
