### ISSUE TITLE
TYPO3 v9.5 routeEnhancers

### ISSUE THREAD

**Issue by yorickreum** [lochmueller/calendarize#274]
Good evening,

is it possible to use this extension with TYPO3 v9.5 URL Handling / RouteEnhancers?
Can't find anything on that…

Kind regards
Yorick

**Comment by lochmueller** [comment]
Hey Yorick,
it is possible, but the index -> news title logic is not part of a RouteEnhancers at the moment. The logic is in this classes and have to migrated to a RouteEnhancers:
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/Url/RealUrl.php#L151

I will check this and add it in the next days/weeks...

Regards,
Tim

**Comment by yorickreum** [comment]
Thanks for your reply! Anything new here? Can't get calendarized news to work with pretty URLs…

**Comment by lochmueller** [comment]
No... no news at the moment. I think I will start this topic in the next year...

**Comment by lochmueller** [comment]
Added a aspect to convert ID into speaking path:
https://github.com/lochmueller/calendarize/blob/master/Documentation/AdministratorManual/UrlRewrite/Index.rst (bottom)
