### ISSUE TITLE
Pagination in week and month view

### ISSUE THREAD

**Issue by Stra2** [lochmueller/calendarize#285]
Idea: Seems it would be easy to include pagination in month and week views in the front end, since the controllers already support it. Perhaps as an option / with a constant in TS (similar to the list pagination setting).

**Comment by lochmueller** [comment]
Hey @Stra2 

the view support pagination also. You have to set "weekPid" for the week view ( https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/Week.html#L8 ) to get the pagination or set the "monthPid" for the month view ( https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Month.html#L7 ).

I close this issue...

Regards,
Tim
