### ISSUE TITLE
Calendarize Event with RealUrl Service creates equal URLs for different detail links

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#288]
While using the RealUrl Service from calendarize in TYPO3 8.7 with calendarize 4.1.0, calendarize generates URLs for detail links to an event that are not unique:
**For example:**
Event called "exampleevent" from sys_category A on Saturday, 19.01.2019 - 5:30 - 6:30 
**URL:** 
https://www.tld.com/event/exampleevent-2019-01-19-05-30/

generates the same URL as

Event called "exampleevent" from sys_category B on Saturday, 19.01.2019 - 5:30 - 6:30 generates the **--> same URL:**
https://www.tld.com/event/exampleevent-2019-01-19-05-30/

Is there a workaround? I thought with RealUrl, the URLs are generated uniqe, for example:
Event 1 (same day, same time)
https://www.tld.com/event/exampleevent-2019-01-19-05-30/
Event 2 (same day, same time)
https://www.tld.com/event/exampleevent-2019-01-19-05-30-1/

**Comment by lochmueller** [comment]
There is a collision detection in this class:
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/Url/RealUrl.php#L165
Please check why the one URL is not found via "aliasAlreadyExists"?!

**Comment by lochmueller** [comment]
Hey @sdesign6 
other question. It is the same event with two categories and one link is from categry A list view and one from category B list view? If this is the case, then both links are correct. There are no additional information in the link like (backPid, source category etc.), so it is ok, that the links are the same if you select the same detail page. if you really want to create multiple URLs for the same event, you could create seprat detail pages. But please keep in mind, that you create duplicate content...
Regards,
Tim

**Comment by sdesign6** [comment]
thanks for your reply. It's not the same event. There are two different events (and IDs) with the same title at the same date and time.

**Comment by lochmueller** [comment]
Then you have to debug and check this function: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/Url/RealUrl.php#L165
This is the collision detection and this function should avoid this problem...

**Comment by lochmueller** [comment]
I close this issue. There is no more feedback... feel free to reopen the issue with more debug information.
