### ISSUE TITLE
Flexform: Field «description»

### ISSUE THREAD

**Issue by marcelbirrer** [lochmueller/calendarize#289]
after the latest update, field «description» is a plain text field - please add RTE functionality again

**Comment by lochmueller** [comment]
@marcelbirrer Which EXT:autoloader version do you use?

**Comment by marcelbirrer** [comment]
the latest: 6.0.5

**Comment by lochmueller** [comment]
Please upgrade to 6.0.6. This should solve this problem.... 👍

**Comment by marcelbirrer** [comment]
works! thanks for the quick fix!
