### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by VladZadorozhnyy** [lochmueller/calendarize#292]
1: Localization failed; "languageField" and "transOrigPointerField" must be defined for the table tx_calendarize_domain_model_configuration

typo3 v9.5.3

how to fix the error please help!!!

**Comment by VladZadorozhnyy** [comment]
localization does not work at all

**Comment by lochmueller** [comment]
Do you have some usefull information? "localization does not work at all" is very generic.... I need configuration of TS related to sys_language_* other language related information. Output format (please test the month view to check if there are empty elements. I will check this in the next days...

**Comment by VladZadorozhnyy** [comment]
**config.yaml**

`
rootPageId: 1
base: 'http://***'
languages:
  -
    languageId: '0'
    title: Русский
    navigationTitle: Русский
    base: /
    locale: ru_RU.UTF8
    iso-639-1: ru
    hreflang: ru-RU
    direction: ''
    typo3Language: ru
    flag: ru
  -
    languageId: '1'
    title: English
    navigationTitle: English
    base: /en/
    locale: en_US.UTF8
    htmlTag_langKey: en
    iso-639-1: en
    hreflang: en-US
    direction: ''
    typo3Language: default
    flag: us
    fallbackType: strict
  -
    title: Кыргызча
    enabled: true
    languageId: '2'
    base: /ky/
    typo3Language: ru
    locale: ru_RU.UTF8
    iso-639-1: ky
    navigationTitle: Киргизский
    hreflang: kg-KG
    direction: ''
    fallbackType: strict
    flag: kg
`

Looked at the conclusion in the months is empty! 
![1](https://user-images.githubusercontent.com/24506959/52468869-24062180-2bb4-11e9-8cf1-e16073342a9b.JPG)
![2](https://user-images.githubusercontent.com/24506959/52468964-6c254400-2bb4-11e9-9e22-89c477ff017a.JPG)

I hope gave more information!

**Comment by lochmueller** [comment]
Hey @VladZadorozhnyy,
we refactor the index process to create real l10n_parent relations in the index table. We test strict and also content_fallback via the TS configuration and both works well. We will check TYPO3 9 installations shortly to avoid further problems.
Regards,
Tim
