### ISSUE TITLE
Call to a member function format() on null

### ISSUE THREAD

**Issue by SirCotare** [lochmueller/calendarize#294]
![screenshot 2019-02-22 at 14 14 44](https://user-images.githubusercontent.com/906924/53244818-3dc36080-36ac-11e9-9f7e-750545fd2c2b.png)

When editing an event:
This error happens when forcing the form to reload (eg. by changing the frequency dropdown selection) while the start_date of the event has not yet been set (empty input field).

The start_date becoming null this way also may produce the following error:
![screenshot 2019-02-22 at 14 17 58](https://user-images.githubusercontent.com/906924/53245014-d4901d00-36ac-11e9-97ff-5ed26a9b29df.png)

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master.
