### ISSUE TITLE
start_date vs. end_date

### ISSUE THREAD

**Issue by hirnschmalz** [lochmueller/calendarize#3]
In the `IndexRepository` the `start_date` is used to filter relevant entries. From my point of view it would be better to use the `end_date`.

If there is an event for more than one day, the event could also be interesting for some people (even if it's already in progress).

At least an option to select wich date is relevant would be nice.

Markus

**Comment by lochmueller** [comment]
You are right... there is also the "addTimeFrameConstraints" that solve this issue in the other IndexRepository functions. A proper solution for "findList" is still missing...

We should check both: start_date in feature or (start_date in the past and end_date in feature)
