### ISSUE TITLE
Database Error when inserting first calenderize plugin 

### ISSUE THREAD

**Issue by zzzooorrrx** [lochmueller/calendarize#300]
Hi,

just installed the extension first time.
Installed form TER
Setting up sys folder and pages

When inserting first plugin the following error came up 

> Datenbank-Fehler
> 
> Unknown column 'tx_calendarize_domain_model_pluginconfiguration.uid' in 'field list'. Es ist ein SQL-Fehler aufgetreten. Dies kann auf eine Schema-Abweichung zwischen TCA und der Datenbank hindeuten. Versuchen Sie im Install Tool einen Datenbank-Vergleich durchzuführen.

Then made database compare
A lot calenderize-stuff was there. Did the compare

Some issues left:
ALTER TABLE `tx_calendarize_domain_model_event` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_event` ADD PRIMARY KEY (uid)
ALTER TABLE `tx_calendarize_domain_model_index` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_index` ADD PRIMARY KEY (uid)
ALTER TABLE `tx_calendarize_domain_model_pluginconfiguration` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_pluginconfiguration` ADD PRIMARY KEY (uid) 

Errors occured:

Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table
Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table
Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table

Uninstalled calenderize and reinstalled it again.
No change there
the tables exist

Any idea?

Related: https://github.com/lochmueller/calendarize/issues/239

**Comment by zzzooorrrx** [comment]
Typo3 8.7.24
calenderize 4.1.3
autoload 6.0.6
PHP 7.2.14
MySQL 5.5.5

**Comment by lochmueller** [comment]
Hey @zzzooorrrx 
Could you uninstall the extension, drop the tx_calendarize_* tables and install the extension again.
Regards,
Tim

**Comment by zzzooorrrx** [comment]
Thx a lot!
Seems to be ok now.
Regards,
Wolfgang
