### ISSUE TITLE
Day end calculation fails on day light saving time change dates

### ISSUE THREAD

**Issue by Gregor-Agnes** [lochmueller/calendarize#310]
The calculation of the end of a day fails if it is done by adding a fixed amount of seconds or minutes or hours: Because at the dates of changing to or from day light saving time the days are an hour shorter and later respectively.

**Comment by Gregor-Agnes** [comment]
Maybe we can use https://github.com/briannesbitt/carbon to do this?

**Comment by lochmueller** [comment]
Nice lib. But stressful for none-composer installations and TER releases :-/

**Comment by lochmueller** [comment]
Hey @Gregor-Agnes 
I fixed the calculation for week and day view.
I will switch to external Libs as soon the extension is for "composer only".
Regards,
Tim
