### ISSUE TITLE
configuration trouble with year view

### ISSUE THREAD

**Issue by zzzooorrrx** [lochmueller/calendarize#311]
In my year view the header output of month is really strange.
Dezember 2018
Januar 2019
Februar 2019
April 2019
...
Oktober 2019
Oktober 2019
November 2019

So Dezember is wrong, März is missing and Oktober doubled!?
Same in previous year and following years...

The output of week and days in the year view is fine.

`<thead>
		<tr>
			<th colspan="7">
				<f:format.date format="%B %Y">{date}</f:format.date>
			</th>
		</tr>
	</thead>`

MomentFullCalendarIo not used

Any idea how to fix this?

------
Typo3 8.7.24
calenderize 4.1.3
autoload 6.0.6
PHP 7.2.14
MySQL 5.5.5

**Comment by lochmueller** [comment]
Hey @zzzooorrrx 
seams to be a problem of the "daylight saving" calculation. March an october are the months of the daylight saving switch in non-UTC environments. I will check this in the next week(s)
Regards,
Tim

**Comment by j4k3** [comment]
Same problem here.

**Comment by lochmueller** [comment]
Hmm... try to rebuild the problem. Works well... could you send me your PHP date configurations (timezones etc.)
![Bildschirmfoto 2019-05-06 um 22 01 04](https://user-images.githubusercontent.com/3907126/57251605-83a48980-704a-11e9-8854-12f5664ac51c.png)

**Comment by lochmueller** [comment]
Could you check the date of the init element.
Output <f:debug>{date}</f:debug> in the beginning of the template: https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/Year.html#L8

**Comment by zzzooorrrx** [comment]
PHP Date configuraion:
date/time support | enabled
-- | --
timelib version | 2016.05
"Olson" Timezone Database Version | 2018.7
Timezone Database | internal
Default timezone | Europe/Berlin

//

Extbase Variable Dump
DateTimeprototypeobject (2019-01-01T00:00:00+02:00, 1546293600)

**Comment by thpa** [comment]
Hi ... have a similar problem here using the month view.

November is starting at 31.10.2019 
Dezember is 30.11.2019
...
1.4.2020 is the first date which is shown correctly.

Is there any wrong config on the server (php settings)?

Thanks in Advance

**Comment by thpa** [comment]
Seems to be a problem using a specific type of php 7.2.x version.
If i change to 7.3 all works fine.

**Comment by zzzooorrrx** [comment]
Hi,
sadly update to php 7.3. doesn't help for my project. 
Still the same error.

**Comment by ibrase** [comment]
Hi,
I resolved the problem by changing line 14 in Resources/Private/Partials/Month.html:
old: <f:format.date format="%B %Y">{date}</f:format.date>
new: <f:format.date format="%B %Y" base="{date}">+ 1 week</f:format.date>

Regards
Inge

**Comment by zzzooorrrx** [comment]
Thx a lot ibrase, that's working!

Regards
Wolfgang
