### ISSUE TITLE
IndexerService->getIndexCount: TypeError

### ISSUE THREAD

**Issue by plueschtier** [lochmueller/calendarize#312]
Hi,

I'm using the calendarize extension based on the master branch of this git (manually updated). The reason I'm using this version is because of using the new router-enhancer.
I do have following issue:

If I try to create a new Event a TypeError is thrown.

Issue in class HDNET\Calendarize\Service\IndexerService

getIndexCount expects a string and a uid(int). (since commit f2b73166a9b8d42819cafb069958ee5b5fb8ad57)

However in my case the function is called with following arguments (both strings):
HDNET\Calendarize\Service\IndexerService->getIndexCount('tx_calendarize_domain_model_event', 'NEW5cbb7280bf359174377176')

DirtyFix for me is currently to return 0 if a string beginning with "NEW" is given for uid.

Updating already created events is possible without any errors.

If you need further information, please let me know.

Thanks,
Andre

**Comment by lochmueller** [comment]
Hey @plueschtier 
thanks for the note. I fixed this problem in the current master.
Regards,
Tim
