### ISSUE TITLE
Error "An exception occurred while executing 'SELECT * FROM" after installing

### ISSUE THREAD

**Issue by blueamerican** [lochmueller/calendarize#313]
After installing calendarize 4.1.3 on TYPO3 8.7.24
i geht the following error in the backend when clicking on the calendarize module:

> An exception occurred while executing 'SELECT * FROM `tx_calendarize_domain_model_pluginconfiguration` WHERE (`uid` = ?) AND ((`tx_calendarize_domain_model_pluginconfiguration`.`deleted` = 0) AND (`tx_calendarize_domain_model_pluginconfiguration`.`hidden` = 0) AND (`tx_calendarize_domain_model_pluginconfiguration`.`starttime` <= 1555871340) AND ((`tx_calendarize_domain_model_pluginconfiguration`.`endtime` = 0) OR (`tx_calendarize_domain_model_pluginconfiguration`.`endtime` > 1555871340)))' with params [0]: Unknown column 'uid' in 'where clause'

**Comment by lochmueller** [comment]
Please uninstall & install the extension again and/or run DB compare.
The tables or some fields are missing. I will close this issue...

**Comment by iunctim** [comment]
When trying to fix the tables with the compare db function in the install tool like this:
```
ALTER TABLE `tx_calendarize_domain_model_event` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_event` ADD PRIMARY KEY (uid)
ALTER TABLE `tx_calendarize_domain_model_index` ADD `uid` INT AUTO_INCREMENT NOT NULL
ALTER TABLE `tx_calendarize_domain_model_index` ADD PRIMARY KEY (uid) 
```
we're getting the error "there must be only one auto_increment column and it must have a primary key"

We were able to fix this with these two queries:
```
ALTER TABLE `tx_calendarize_domain_model_event` ADD `uid` INT NOT NULL AUTO_INCREMENT primary key;
ALTER TABLE `tx_calendarize_domain_model_index` ADD `uid` INT NOT NULL AUTO_INCREMENT primary key;
```
It is a little annoying that there is no ext_tables.sql file or am I missing something?

**Comment by lochmueller** [comment]
> It is a little annoying that there is no ext_tables.sql file or am I missing something?

This is right. It is based on EXT:autoloader.
