### ISSUE TITLE
event-title in breadcrumb

### ISSUE THREAD

**Issue by morange** [lochmueller/calendarize#317]
Hello,

i would like to use the event-title in the breadcrumbs with this code in TYPO3 v9 and Calendarize 4.1.3:

`[globalVar = GP:tx_calendarize_calendar|index > 0]
lib.breadCrumbs.10.1.NO.doNotLinkIt = 0
lib.breadCrumbs.10.1.NO.allWrap = <li>|</li>

lib.breadCrumbs.20 = RECORDS
lib.breadCrumbs.20 {
  dontCheckPid = 1
  tables = tx_calendarize_domain_model_index
  source.data = GP:tx_calendarize_calendar|index
  source.intval = 1
  conf.tx_calendarize_domain_model_event = TEXT
  conf.tx_calendarize_domain_model_event.field = title
  conf.tx_calendarize_domain_model_event.htmlSpecialChars = 1
  wrap = <li>|</li>
}
[end]`

It would be great, if you include an simlar option.

Many thanks, Steffen

**Comment by lochmueller** [comment]
Hey @morange 
I added the breadcrumb support for the next release.
Check out the documentation: https://raw.githubusercontent.com/lochmueller/calendarize/master/Documentation/AdministratorManual/Configuration/Index.rst
Regards,
Tim

**Comment by morange** [comment]
Hi TIm,
thx for your support.

Many thx, Steffen
