### ISSUE TITLE
Wrong encoded title for JS calendar

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#318]
![Bildschirmfoto 2019-06-12 um 22 23 02](https://user-images.githubusercontent.com/3907126/59383681-ba17a780-8d60-11e9-9178-e911b2d868b7.png)
https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Month.html#L80

**Comment by hweckhardt** [comment]
Is this the right pathname for the partial Month.html? I have renamed this file, but the Console still shows the same error, and the fullcalender is not displayed.

**Comment by lochmueller** [comment]
Do you rename your Partial file? Then the partial of the extension will rendered and the problem is also part of the extension template.

**Comment by hweckhardt** [comment]
First, I changed the line 80 in partial Month.html (...Resources/Private/Partials/) as a comment. I wanted to see, whether the rest of the script was loaded without error. But the error message remained the same, and as a second step I renamed that partial to Month.html_ori, in the same path. I expected another error message (... partial could not be found ... or similar), but the behavior was the same, the same error message and the fullcalendar is not loaded. Therefore my guess was that the partial Month.html is located in another path. I also deleted all the caches (for compressed scripts as well).

**Comment by lochmueller** [comment]
Hey @hweckhardt I cannot follow your thoughts. I will check this in the next days and will remove the JS error. I will rbuild this in my test system. Regards, Tim

**Comment by hweckhardt** [comment]
Ok, thank you for your support. Regards, Horst-Walter

**Comment by hweckhardt** [comment]
Hey Tim, Is this issue fixed in the extension release 4.2.1? Regards, Horst-Walter

**Comment by lochmueller** [comment]
No.... the issue is still open.

**Comment by hweckhardt** [comment]
Hey Tim, is there a chance that this issue wil be fixed? Many thanks in advance and best regards, Horst-Walter

**Comment by hweckhardt** [comment]
I think i found the problem. As i installed the extension "calendarize_news" the last partials which were loaded are from this extension. It also has a partial "Month.html" and there the tmp.title is encoded wrong. I have disabled the extension "calendarize_news" and now the Fullcalender is working. I am only looking for the options the enable the buttons in the header and especially to get the possibility to switch the month's. But this is a different aspect. I think, this issue #318 can be closed, and the related partial in "calendarize_news" must be modified.

**Comment by lochmueller** [comment]
Thanks for finding this issue. I fixed the template of EXT:calendarize_news a few seconds ago:
https://github.com/lochmueller/calendarize_news/commit/d9317eb79b6adcbd85480f7f00c182263848dc68
