### ISSUE TITLE
 table, tx_calendarize_domain_model_configuration, is not allowed on this page

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#32]
Hi,

I'm using TYPO3 7.6.2 with the newest versiond of news, calendarize_news, calendarize and autoloader. I included When I try to insert a Date for a news I get the error message above on saving. 
I included the four templates and checked the table. Everything looks fine. Did I miss any configuration?

Thx for any help.

**Comment by lochmueller** [comment]
Hey @Hobokens 
You try to create a news record on a regular page (not in a storage folder), right?
I will fix this shortly...
Regards,
Tim

**Comment by Hobokens** [comment]
thanks a lot!
Regards
Hobokens
