### ISSUE TITLE
ICS Import

### ISSUE THREAD

**Issue by florianwallner** [lochmueller/calendarize#328]
The ICS import does not work in the current branch. The ICS parser is no longer included since version 4.2.0 and with manual integration the following error occurs when executing the task: 
`The object of type "HDNET\Calendarize\Domain\Model\Event" given to update must be persisted already, but is new. `

Changing "update" to "add" on [EventImport#L65](https://github.com/lochmueller/calendarize/blob/master/Classes/Slots/EventImport.php#L65],) the import works but it won´t check for duplicates with each import.

**Comment by lochmueller** [comment]
Thanks. I merged your branch and fix the event detection. Update works again.
