### ISSUE TITLE
Midnight as end time

### ISSUE THREAD

**Issue by markusa86** [lochmueller/calendarize#329]
Hi,
at the moment it is not possible to choose midnight instead of "open end" as end time.
Example: Event 20:00 - 00:00.
Problem: TYPO3 saves 00:00 as 0. 
Maybe empty could be 0 and 86400 is 00:00. And a Checkbox like whole day for open end.

Regards,
Markus

**Comment by j4k3** [comment]
Totally agreed. The current implementation is conceptionally weak, mostly because checking if the time part of DateTime isn't at all tivial.

**Comment by lochmueller** [comment]
First steps are done: https://github.com/lochmueller/calendarize/commit/ca682871eefeccb528ef9425a74375273b281121

Open:
- Update Indexer
- Adapt calendarize/Resources/Private/Partials/Date/Moment.html
- Adapt calendarize/Resources/Private/Partials/Date/Static.html
- Check, Check, Check :)
