### ISSUE TITLE
2 Installation Problems

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#33]
Hi Tim,

sorry, it's me again. I have two strange installtion problems:

1) Although I can see the js-files and the css-files in the TSOB they are not included in the page (take a look at the screnenshots)
![installation_tsob](https://cloud.githubusercontent.com/assets/6764582/12041767/eebd558a-ae74-11e5-9d3a-08fa87288236.png)
![installation_year_view](https://cloud.githubusercontent.com/assets/6764582/12041768/eec1f36a-ae74-11e5-8582-b15ee6e18015.png)

2) The more link and the title link in listview link to the list view (id=135) instead to detail view although i've configured the plugin correctly (detail view id=134). I have the same problem with the day view.

Regards and thanks for your great extensions!
Hobokens

**Comment by lochmueller** [comment]
Hey @Hobokens 
Please open two issues next time, if you have two different problems!

1.) I can not rebuild to problem. Do you check the object browser directly on the page where the calendarize plugin is used? Calendarize don't do any kind of "magic". If the CSS/JS is added to "page" (I hope you primary PAGE object is called "page") it is TYPO3s responsibility to add the files to the output. I need more detail debugging information...

2.) It is a "normal" calendarize Event, a calendarize_news event or a custom event of your own structure? I also can't rebuild this bug at the moment.

Please add: TYPO3 Version, PHP Version, Extension Versions and more details...

Regards,
Tim

**Comment by Hobokens** [comment]
Hi@Tim,
sorry i forgot to mention again my configuration: I use the newest version of TYPO3 7.6.2 and of all extension. 
1) I included all templates but there is no CSS/JS. I checked the object browser on root page and on the page with list view.
2) With a calendarize_news event the detail link has the same PID as the list view. With a custom event everything is fine.
If you want to I can give you a login by PM.

Regards and a happy new year - a little bit late
Hobokens.

**Comment by lochmueller** [comment]
Hey @Hobokens 

1.) Are you include the News TS also? There are "detailPidDetermination" (with "default" mode) and "defaultDetailPid" settings that determinate the Single PID. It seams, that your news configuration is wrong, because the calendarize_news Template build the Link with the News internal ViewHelper. So it should by a news configuration issue...
2.) Please send me a admin login via PM. I think it is a TYPO3 configuration issue (e.g. "Reset rootline" or "include Static before Template" in the TS template)

Regards,
Tim

**Comment by lochmueller** [comment]
Thanks for the PM. Details are sent via E-Mail... close this issue

**Comment by r4fx** [comment]
Guys, what was the problem with links to Detail view in news events? I have the same situation...

**Comment by lochmueller** [comment]
Please describe the problem and create a new issue... this one is already closed!
