### ISSUE TITLE
Import script / modul

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#330]
Does there any import script for cal exist?
It's mentioned as planned in [this old article](https://www.typo3.net/artikel/typo3-calendarize-moderne-extbasefluid-struktur-und-flexible-datenhaltung/), so I've the hope it was already realized.

**Comment by lochmueller** [comment]
There is a EX:cal -> EXT:calendarize Migration. But you have to test it by your own: https://github.com/lochmueller/calendarize/blob/master/Classes/Updates/CalMigrationUpdate.php

Feel free to create issues, if you found problems or directly contribute...

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Thanks!
