### ISSUE TITLE
Filter by categories

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#331]
I never found out to Filter by categories, I saw some issue about it and think it might be included.
If so, how to use it?

**Comment by lochmueller** [comment]
I will check this in the future. At the moment there are many tasks on my desk so it will take several weeks...

**Comment by DavidBruchmann** [comment]
Ok, thanks  for the feedback, so I know that it's not worth it spending time on it now to search some options or configuration.
For the moment I use a workaround with different folders for the event records.

**Comment by lochmueller** [comment]
Hey @DavidBruchmann 
I checked this on my local system. You can select the categories in the "Plugin Configuration"-record (last Tab) or in the Plugin (tt_content) itself (also the default category tab of the content element). Both places are checked by this Slot: https://github.com/lochmueller/calendarize/blob/master/Classes/Slots/EventSearch.php#L83
If there are any special problems, please describe your usecase..
Regards,
Tim
