### ISSUE TITLE
error after installation in typo3

### ISSUE THREAD

**Issue by ajackson3** [lochmueller/calendarize#332]
Hello,
sorry, i don't know, if i do right to post this issue here....

I have the problem, that after installation of the calendarize extension i got a error message (see attached file)
I tried to solve the problem by making a database analyzing within install tool, but without success.
What could be the reason for that?
![calendarize-fehler](https://user-images.githubusercontent.com/55637412/65456353-67628700-de49-11e9-85f8-9b281955f898.JPG)

![database analyzer](https://user-images.githubusercontent.com/55637412/65456311-5154c680-de49-11e9-8a0d-4957024415ad.JPG)

Anyone who can give me a tip?
I have typo3 8.7.24

Thanks 
Andreas

**Comment by lochmueller** [comment]
Hey andreas... drop the table and rund DB compare. This should fix the issue....

**Comment by ajackson3** [comment]
Thank you, that solved my problem.....
