### ISSUE TITLE
Where are the CSS classes defined?

### ISSUE THREAD

**Issue by ajackson3** [lochmueller/calendarize#333]
Hello Tim,
sorry, i cant find it.
Where are the CSS classes defined?
Can you help me?

Thanks
Andreas

**Comment by lochmueller** [comment]
Hey @ajackson3 
I do not understand the questions? Do you mean the templates?
Regards,
Tim

**Comment by ajackson3** [comment]
For example I am searching for the fontsize of the headline h2 in the List view.
Class "media-body".
Is there a css file loaded or where is that fontsize configuerd?

Thanks
Andreas

**Comment by lochmueller** [comment]
Hey @ajackson3 
no. There is no CSS file in the extension. Please check the web developer tools in your browser to get the source of the definition. Perhaps it is the FullCalendar.io CSS?
Regards,
Tim
