### ISSUE TITLE
Url encoding wrong for Event occurences after 12:00AM

### ISSUE THREAD

**Issue by j4k3** [lochmueller/calendarize#334]
The generation of URLs fails for me for every event that starts after 12:00AM. The URLs instead treat the time as if it were a 12 hour format with no indication of which meridian is being refered to, e.g.

What should be:
`/termine/termine/event/herzliche-einladung-zum-REDACTED-2020-02-26-16-00/`
instead is:
`/termine/termine/event/herzliche-einladung-zum-REDACTED-2020-02-26-04-00/`

I've successfully corrected this in my installation the calendarize/Classes/Service/Url/AbstractUrl.php file, where in the function getIndexBase() the date format `'Y-m-d-h-i'` is used. This should be `'Y-m-d-H-i'`.
Changing this line and flushing the realurl tables and frontend cache fixed this.

I can't provide a pull request right now, shall I do so later?

**Comment by lochmueller** [comment]
Hey @j4k3 
thanks for the fix. Please send a pull request later. I will merge this change...
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @j4k3 
Is added to the current master. `$GLOBALS['TYPO3_CONF_VARS']['SYS']['hhmm']` is used now and all "non numbers" are replaced by "-".
Regards,
Tim
