### ISSUE TITLE
EventMapper causes Exception: #1472074485: Table 'db.tx_extbase_domain_model_filereference' doesn't exist

### ISSUE THREAD

**Issue by svewap** [lochmueller/calendarize#335]
Using the EventMapper will cause an exception if the cache has been cleared and the cf_extbase_datamapfactory_datamap table is empty. By calling a detail URL (ex. "/event/vortrag-dav-2019-11-08-06-00-3476/") the EventMapper tries to initialize the event object and resolves FileReference attributes. At this point TYPO3 does not yet have a TypoScript template available, which loads the wrong table.

Solution:
To give both 'images' and 'downloads' an `@lazy`.

**Comment by Bjoelin** [comment]
I can second the solution by @svewap works perfectly.

**Comment by svewap** [comment]
Thank you!
