### ISSUE TITLE
Loading Month Views over Ajax

### ISSUE THREAD

**Issue by Wingmk** [lochmueller/calendarize#337]
Hi,

I use the month calendar on a couple of websites and the current behaviour is not what I originally expected.
Loading and updating the calendar asynchronous over ajax should be available.
This can also be implemented with the current model and url configuration.

The steps necessary as far as I went on my analysis are:
 - Design TypoScript Configuration for an additional page type which only loads the plugin
 - Updating the months Link so they keep the typoscript page type
 - Add a TypoScript configuration for activating the ajax reload
 - Write a small script that reloads the url via ajax and updates the calendar accordingly

Do you plan on implementing something like this or do you want support on this feature?

**Comment by lochmueller** [comment]
Hey @TimoWinkler ,
it is not planed at the moment. As first idea: with jQuery load you can enable this by using 1-2 lines of JS without adapting the PHP logic: https://api.jquery.com/load/
You can bind the load to the pagination of the month view, load the target page via AJAX and include the month view in the position of the original month-view.

More complex option would be to provide a API to access events and deate structures via JSON. But this is not in the plan at the moment.
Regards,
Tim

**Comment by lochmueller** [comment]
I drop this isse. No progess since a year. Feel free to push pull requests, if there are finished integrations of this feature.
