### ISSUE TITLE
Old events in all Lists after upgrading Typo3 to version 9.5

### ISSUE THREAD

**Issue by strubbisch** [lochmueller/calendarize#338]
After the upgrade of Typo3 to version 9.5, old events are shown in all lists (latest, list).

Is there a configuration option, which i don't see?

Frank

**Comment by lochmueller** [comment]
Do you use the `useRelativeDate` configuration?

**Comment by strubbisch** [comment]
I don't know. Where can I configurate this?

**Comment by lochmueller** [comment]
So... do you have some more information:
- Calendarize version?
- Do you run the reindex scheduler Task?
- Do you try to set "overrideStartdate" vie Plugin configuration?
- Which plugin view do you use?
- Are all old events a visible or is there a special schema?

Regards,
Tim

**Comment by strubbisch** [comment]
I use the newest version 4.3.0.

I've found that the data updates only once a day and therefore old events still appear in the views. Thus, my problem has actually done, except for the fact that changed data also does not change immediately, but only changed once a day.

Thx,
Frank

**Comment by lochmueller** [comment]
Hmm... also if you clear the cache?
Do you check this property: https://github.com/lochmueller/calendarize/blob/master/Configuration/TypoScript/constants.txt#L25 ?!?!
Regards,
Tim

**Comment by strubbisch** [comment]
When i clear the cache, then the events are changed.

The property is set to 0. Is this correct?

Frank

**Comment by lochmueller** [comment]
Yes. If you clear the cache, then there are missing clearCacheCmd configurations in your TYPO3 installation. It is not related to EXT:calendarize. Please you configuration like this: https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceMain.html#clearcachecmd
