### ISSUE TITLE
Display running events

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#344]
We'd like to display events that are already happening.  
How is it possible to adjust the time for display accordingly?

**Comment by lochmueller** [comment]
Hey @DavidBruchmann 
there is a Past view in the plugin you can use.
Do you means this?
Regards,
Tim

**Comment by DavidBruchmann** [comment]
No in the list for upcoming events those that are already running shall be listed too.
Can be according to the current time, or just for the current day.

**Comment by lochmueller** [comment]
Hey @DavidBruchmann ,
do you mean the `listStartTime` option? Do you try to set this to now:
https://github.com/lochmueller/calendarize/blob/master/Configuration/TypoScript/constants.txt#L26

So you get at 14:00 also a event, that start at 8:00 and end at 11:00.

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Hi Tim,

thanks for the answer.
I tried it just now and it doesn't work like that,
This setting should show the event, the event is still running but it's not shown

![image](https://user-images.githubusercontent.com/999146/70843207-eff92e00-1e60-11ea-956e-eb8650b2cbb8.png)

**Comment by lochmueller** [comment]
Hey @DavidBruchmann 
it is independant of the event time configuration. `listStartTime` ist a display option in the plugin/typoscript.
Or do you mean with `We'd like to display events that are already happening.` in the backend? Because in the backend (under the time configuration) there are only feature events...
Regards,
Tim

**Comment by DavidBruchmann** [comment]
Thanks Tim,

the screenshot might be a bit misleading, I did set set the variable `listStartTime` to `Now`, I remarked it's an option I can chose and never had to be filled by text. So the impact of the option is not like intended as it's for me displaying only events in the future in frontend.

**Comment by dev-for-web** [comment]
Same issue here.
Even if I set an end date. For example an event starting yesterday and ends next week. The event is not shown. I also do not find any repository method to solve the problem in my own controller.

Is there any possibility to get this done?

**Comment by timkarliczek** [comment]
This should work:
- enable **Respect times in time frame constraints** in the extension configuration
- inside the plugin enable the option **Use relative Date ( 'now' or '+1 year')**
- enter **now** inside the fields **Override startdate (relative)** and **Override enddate (relative)**

You might get some trouble with timezones. In my local dev environment the server timezone and the phptimezone is UTC. It is working there with the above settings. In another project with server and phptimezone set to Europe/Berlin TYPO3 stores "localized" timestamps in the database. This causes some trouble with the where clauses. Im not sure if i configured something wrong or if the where clauses in the `IndexRepository` must be fixed for that.

**Comment by dev-for-web** [comment]
Thanks @timkarliczek. With this settings I was able to get my extension working.
Unfortunetly I had to make custom changes in the calendarize extension due to an error in the configuration **respectTimesInTimeFrameConstraints ** with v9 ( #402)

**Comment by lochmueller** [comment]
Great. So it is a configuration problem and *Respect times in time frame constraints* solve this. Thanks for the hint @timkarliczek 
I close this issue. If there are any other problems, feel free to create a new issue.
