### ISSUE TITLE
ICS Import -> Datum/Zeit kein Index-Eintrag

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#349]
Hallo,
leider bleibt noch ein Fehler beim ICS-Import eines Kalenders: die Kalendereinträge werden nicht im FE angezeigt!
- der ICS-Import funktioniert
- die einzelnen Kalendereinträge werden richtig angelegt
- das Datum und die Uhrzeit werden zwar auch übernommen und werden im Reiter "Datum Optionen" angezeigt, allerdings wird scheinbar kein Eintrag im Index erzeugt.
- im Reiter "Datum Optionen" den Eintrags erscheint unten diese Meldung:
_Calendarize (Informationen - Speichern um zu aktualisieren...)
Es gibt 0 Eintrag/Einträge im Index des aktuellen Datensatzes. Die nächsten 10 Ereignisse (inkl. heute) sind (ignoriert "enable columns")...

    Keine Ereignisse_
- erst wenn man den Kalendereintrag ohne Veränderungen speichert (siehe Meldung), wird das Datum/Zeit im Index angelegt und der Eintrag erscheint im FE.
_Es gibt 1 Eintrag/Einträge im Index des aktuellen Datensatzes. Die nächsten 10 Ereignisse (inkl. heute) sind (ignoriert "enable columns")...

    Tue 02.06.2020 - Wed 03.06.2020_

Gruß, Sascha

**Comment by lochmueller** [comment]
Hey Sascha,
the "reindex" was missing. You can execute the reindex via a command controller but I also add the reindex in the Import process. So the items are found in the frontend views.
Regards,
Tim
