### ISSUE TITLE
Links in Listenansich

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#351]
In der reinen Listenansicht werden die einzelnen Einträge wie beim Modus "Liste + Detail" als Link angezeigt. Beim Anklicken des Eintrags wird dann allerdings nur die Seite neu geladen. Im Modus "Liste" würde die Entfernung des Links für die einzelnen Einträge Sinn machen.

**Comment by lochmueller** [comment]
Hey @GitCybers dann hast du keine DetailPid im Plugin hinterlegt. Kann das sein? Grüße, Tim

**Comment by GitCybers** [comment]
Hallo Tim,
die DetailPID ist die gleiche wie die ListenPID und ist eingetragen. Aber ich will die Detailfunktion auch gar nicht nutzen. Ich habe im Plugin bei Modus nur "Liste" ausgewählt. Dennoch erscheint in der Liste der Eintrag als Link und auch der "Button" "mehr".  Beim Anklicken erscheint dann nicht die Detailseite (soll ja auch nicht weil ja Modus "Liste) sondern erneut die Liste -> das ist ja jetzt nicht schlimm, aber die Verlinkung der Einträge und der "mehr-Button" sind doch in der reinen Listenansicht vollkommen unnütz und unschön...
Im Modus "Liste + Detail" funktioniert alles wie es soll. Erst die Listenansicht und beim Klick auf "mehr" oder den Eintrag bekomme ich nur den Eintrag mit den entsprechenden Details.

Gruß, Sascha

**Comment by lochmueller** [comment]
Achso... das "nur Liste" bezieht sich darauf, dass das Plugin nicht in den Detail Context wechseln kann. Es bezieht sich nicht darauf, dass es keine Detail-Ansicht gibt. Interessante idee.. makiere das Issue mal als Feature.
PS: In der Zukunft bitte auf Englisch schreiben, sodass die Infos alle verstehen 👍 
Grüße,
Tim
