### ISSUE TITLE
field calendarize_info not found

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/calendarize#354]
The field `calendarize_info` is shown in the display options in backend, but selecting the field throws an error.

**Comment by lochmueller** [comment]
Hey @DavidBruchmann ,

TYPO3 Version? Calendarize Version? Autoloader Version?
Do you try to run DB compare oder uninstall/install the extension?

Regards,
Tim

**Comment by DavidBruchmann** [comment]
I installed calendarize-4.2.1 by composer in TYPO3 9.5.11.
Autoloader has version 6.2.1.

I deactivated now short calendarzie in ExtenManager and installed again, that doesn't change anything. Also DB compare is not listing the missing field.

And this is the error-message:
![image](https://user-images.githubusercontent.com/999146/70853339-2b3a4200-1edf-11ea-8fb2-aa8eb2f18e12.png)

**Comment by lochmueller** [comment]
if both extensions are installed, go to install-tool, remove all caches and check db-compare? Are there any modifications in the DB compare or the the structure ok?

**Comment by DavidBruchmann** [comment]
In DB compare the field `calendarize_info` is just not listed.

**Comment by DavidBruchmann** [comment]
DB compare takes `ext_tables.sql` as base, but I don't see it in the extension. So you must have included something nifty (I saw the Registry-class) but that doesn't work like intended.

**Comment by lochmueller** [comment]
`ext_tables.sql` is not needed, because of the EXT:autoloader. I will check this...

**Comment by DavidBruchmann** [comment]
great, thank you!

**Comment by wakoch** [comment]
I have the same problem. How was it fixed?
TYPO3 9.5.21
calendarize  6.0.0
autoloader 6.2.1

**Comment by lochmueller** [comment]
Hey @wakoch 
Do you try to clear all caches (via install tool) and run DB compare?
Note: Your are using old versions of autoloader, calendarize and TYPO3.
Perhaps this is already fixed in current versions...

Regards;
Tim

**Comment by wakoch** [comment]
Yes, cleared all caches (via Install Tool) and run DB compare. The field is not added.

In this project I'm using TYPO3 9.5 LTS (which has ELTS: 2024-09-01) . Your newer versions of autoloader an calendarize are for 10.4 only.

**Comment by lochmueller** [comment]
Hey @wakoch You are right... TYPO3 has ELTS, but my extensions have no ELTS support ;)
There will be no new releases (except security related) for old extension versions. Sorry.
