### ISSUE TITLE
Version 5: reindex

### ISSUE THREAD

**Issue by blueamerican** [lochmueller/calendarize#355]
What do you mean exactly by reindex:
- Add openEndTime option (require DB compare and reindex)

DB Überpüfung > Referenzindex?

**Comment by lochmueller** [comment]
Hey @blueamerican 
There is a scheduler symfony task "Calendarize->reindex" that check the index and rebuild it. Just execute it once.
Regards,
Tim

**Comment by blueamerican** [comment]
where do i find this task?
in the scheduler i do not have it.
TYPO3 8.7.27
calendarize 5.0.0

**Comment by blueamerican** [comment]
i found it
