### ISSUE TITLE
Cal Migration Update doesn' work in TYPO3 9.5

### ISSUE THREAD

**Issue by claude27** [lochmueller/calendarize#356]
I tried to solve it myself, but it was too complicated for me. There are several issues, probably some of them related to PHP7.

**Comment by lochmueller** [comment]
Do you have any concrete error message or problem situation? Your description is very generic ;)

**Comment by claude27** [comment]
thank you for your quick answer. I got the following errors. Each after solving (not sure if it was always the right solution) the one before :
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT * FROM `sys_category` WHERE (`import_id` <> ) AND ((`sys_category`.`deleted` = 0) AND (`sys_category`.`hidden` = 0) AND (`sys_category`.`starttime` <= 1576853340) AND ((`sys_category`.`endtime` = 0) OR (`sys_category`.`endtime` > 1576853340)))': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND ((`sys_category`.`deleted` = 0) AND (`sys_category`.`hidden` = 0) AND (`sy' at line 1 | Doctrine\DBAL\Exception\SyntaxErrorException thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 79. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
-> I changed in line 782:
$q->expr()->neq('import_id', '') to $q->expr()->neq('import_id', 'NULL')

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function HDNET\Calendarize\Updates\CalMigrationUpdate::getExceptionConfigurationForExceptionGroup(), 1 passed in /var/www/html/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php on line 222 and at least 2 expected | ArgumentCountError thrown in file /var/www/html/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php in line 614. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
-> I changed in line 614:
protected function getExceptionConfigurationForExceptionGroup($groupId, &$dbQueries, &$customMessages)
to
 protected function getExceptionConfigurationForExceptionGroup($groupId, &$dbQueries = NULL, &$customMessages = NULL)

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT * FROM ` tx_cal_exception_event_group_mm` WHERE (uid_local) AND (?)' with params [1]: Table 'db. tx_cal_exception_event_group_mm' doesn't exist | Doctrine\DBAL\Exception\TableNotFoundException thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 42. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
-> I changed in line 618
  'table' => ' tx_cal_exception_event_group_mm',
to
 'table' => 'tx_cal_exception_event_group_mm',
              
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT * FROM ` tx_cal_exception_event` WHERE `uid` = ?' with params [50]: Table 'db. tx_cal_exception_event' doesn't exist | Doctrine\DBAL\Exception\TableNotFoundException thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 42. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
-> I changed in line 634
 'table' => ' tx_cal_exception_event',
to
'table' => 'tx_cal_exception_event',

Core: Exception handler (WEB): Uncaught TYPO3 Exception: DateTime::__construct() expects parameter 1 to be string, integer given | TypeError thrown in file /var/www/html/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php in line 978. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
->I changed in line 978
 $date = new \DateTime($oldFormat);
to 
$date = new \DateTime(strval($oldFormat));

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT * FROM `sys_file_reference` WHERE (`tablenames` = tx_cal_event) AND (`uid_foreign` = ?) AND ((`sys_file_reference`.`deleted` = 0) AND (`sys_file_reference`.`hidden` = 0))' with params [2213]: Unknown column 'tx_cal_event' in 'where clause' | Doctrine\DBAL\Exception\InvalidFieldNameException thrown in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 60. Requested URL: https://www.xxx.ddev.site/typo3/install.php?install[controller]=upgrade&install[context]=backend 
-> Here I didn't manage to solve this probleme, the ' are obviously allways removed before executing the sql query.

Here is my ddev yaml configuration (I didn' test it on the live server, which runs with mysql 5.6):
APIVersion: v1.12.0
name: xxx
type: typo3
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
- www.xxx

additional_fqdns: []
provider: default
mariadb_version: 10.1

hooks:
    post-start:
      - exec: "phpdismod xdebug"

Thank you very much!!!

**Comment by lochmueller** [comment]
Hey @claude27 
I fixed your problems in current master.
Could you rerun the proess or attach a dump of the cal tables so I can rebuild your case?
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @claude27 
found also the last problem of your list.
If there are still problems, please open a new issue.
Regards,
Tim
