### ISSUE TITLE
Slash in Event Title breaks List view

### ISSUE THREAD

**Issue by claude27** [lochmueller/calendarize#357]
a slash in the event title breaks the list view page, when the following routing configuration is set (TYPO3 9.5.13):

> CalendarizePlugin:
>     type: Extbase
>     extension: Calendarize
>     plugin: Calendar
>     routes:
>       - { routePath: '/{event_title}', _controller: 'Calendarize::detail', _arguments: {'event_title': 'index'} }
>     defaultController: 'Calendarize::detail'
>     aspects:
>       event_title:
>         type: EventMapper

In the log the following error is listed:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Parameter "tx_calendarize_calendar__index" for route "tx_calendarize_calendar_0" must match "[^/]++" ("winter-fitness-xxx-2019/2020-2020-01-11-13-00-32319" given) to generate a corresponding URL. | Symfony\Component\Routing\Exception\InvalidParameterException thrown in file /xxx/vendor/symfony/routing/Generator/UrlGenerator.php in line 183. Requested URL: https://www.xxx.de/kalender/

**Comment by lochmueller** [comment]
Fixed in current master.
