### ISSUE TITLE
[FEATURE] Add cacheTag zu listAction

### ISSUE THREAD

**Issue by claude27** [lochmueller/calendarize#358]
It would be fine if you could add a cacheTag zu listAction in CalenderController.php.
Simply add for example this line:
$GLOBALS['TSFE']->addCacheTags(['event']);
 
like described in this example:
[https://gist.github.com/einpraegsam/d8f567bdebd443bce1cea689f9ca602b](url)

Thank you!

**Comment by lochmueller** [comment]
Good Point. I will add cache tags next year. For different views and also for single events. Regards Tim

**Comment by claude27** [comment]
Thank you!

**Comment by lochmueller** [comment]
Added this tags to current master:
- "calendarize" (for all views)
- "calendarize_xxx" (for all views like week, list, latest...)
- "calendarize_index_xxx" (for direct index access)
- "calendarize_event_xxx" (for direct event access)

**Comment by bavarianbytes** [comment]
Can i use `TCEMAIN.clearCacheCmd = cacheTag:calendarize` in the page TS config of sysfolder where the events are stored to clear the cache of all pages that contain a calendarize plugin?

**Comment by lochmueller** [comment]
Hey @bavarianbytes 

yes.
