### ISSUE TITLE
Time only / Date only

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#359]
With this code `<f:render partial="DateInformation" arguments="{index: index}"/>` in ListItem.html I get for example "15.01.2020 08:15 - 09:45". I want to seperate the date and the time and I want to display time and date in different table elements. Ist there an own variable for the Date without the time? Respectively is there an own variable for the Time?
Thanks, Sascha

**Comment by lochmueller** [comment]
Hey @GitCybers 
You could split up the template into to two partials. In the first you output only the date information and in the other only the time information. As result you could use the date and time in different places standalone. Please use the same structure as in the DateInformation Partial (e.g. check for allDay).
I close this issue. Feel free to ask questions in Slack so we can easily discuss such questions in lager groups.
Regards,
Tim

**Comment by GitCybers** [comment]
I really don`t know what I have to do. It sounds very strange for me...

**Comment by lochmueller** [comment]
Hey @GitCybers Hmm... DateInformation output the date and the time. If you need only on information (the Date or  only the time) just create new Partial Templates that output only the Date or only the time and use your new Partials instead of DateInformation. Could you explain your problem with more details? At the moment I think it is more related to Patial&Fluid structures than to a EXT:calendarize specific problem?

**Comment by GitCybers** [comment]
Ich muß dann doch mal auf deutsch weiter machen:
Ich möchte folgende Darstellung:
Datum   |  Kalendereintrag
-------------------------------------------------
Uhrzeit  |   ggf. Details zum Kalendereintrag 

Mit dem Thema Partials und Fluid bin ich (noch) nicht so bewandert. Versuche mich aber da reinzuarbeiten... aber ich habe auch in den Partials nichts von Time gefunden.... ich bastel mal weiter...

**Comment by lochmueller** [comment]
OK... dann gerne nochmals auf Deutsch 👍 
Das "DateInformation" ist teil von EXT:calendarize und liegt im Partial Ordner der Extension. Den Partial Pfad überschreibst du ja zu deinen Templates. Neben das eigentliche "DateInformation" Partial legst du (eigene! sind nicht in der Extension!) einfach "DateOnlyInformation" und "TimeOnlyInformation" und gibst in dem Template entsprechend nur die Datum Information bzw nur die Zeit Information aus (wie dies geschieht bzw. was geprüft werden muss: siehe "DateInformation"). Dann benutzt du in deinen Templates (z.B. ListItem oder Detail) einfach "DateOnlyInformation" und "TimeOnlyInformation" wie du es brauchst und benutzt NICHT "DateInformation". So kannst du es am besten aussteuern...

**Comment by lochmueller** [comment]
PS: Fragen gerne im Slack fragen... GitHub ist mehr für Feature Requests und Bug Requests.
