### ISSUE TITLE
Setting an interval in combination with a monthly recurrence, e.g. every 2nd month and every third wednesday of a month, is not working

### ISSUE THREAD

**Issue by claude27** [lochmueller/calendarize#364]
I have recognized that setting an interval in combination with a monthly recurrence, e.g. every 2nd month and every third wednesday of a month, is not working. 
I need this for an event where the location is alternating between 2 different locations and so I created 2 events, one for each location.

![image](https://user-images.githubusercontent.com/4347809/72730403-9e477000-3b91-11ea-9d0e-436df4d32999.png)

**Comment by lochmueller** [comment]
Hey @claude27 
this problem is fixed in current master.
Regards,
Tim

**Comment by claude27** [comment]
Hey @lochmueller Thank you for your fast bugfix!
