### ISSUE TITLE
Error after importing external events -> Undefined class constant 'DAY_END'

### ISSUE THREAD

**Issue by MichiBeck** [lochmueller/calendarize#365]
Hi Tim,
I have a error after create an external event by an url: Undefined class constant 'DAY_END'

TYPO3 8.7.30
calendarize 5.0.1
PHP 7.2.24

Any Idea what the problem could be? Thank a lot!

**Comment by lochmueller** [comment]
Already fixed in current master: https://github.com/lochmueller/calendarize/commit/7359275c07f338fa404e06e7dc56d4c61bad4e94 will be part of the next release.
