### ISSUE TITLE
Need help with pagination by months

### ISSUE THREAD

**Issue by shm-sl** [lochmueller/calendarize#367]
I tried to use the monthsInYear viewhelper but it's a loop and renders 12 pagination menus per page and the pagination doesn't work. Is there a better way to do it?
```html
<c:loop.monthsInYear date="{date}" iteration="year">
  <f:widget.paginate objects="{year}" as="paginatedIndices" configuration="{itemsPerPage: 1, insertAbove: 0, insertBelow: 1, maximumNumberOfLinks: 5}">
    <f:render partial="Month" arguments="{date: year.calendar.date, indices:indices}" />
  </f:widget.paginate>
</c:loop.monthsInYear>
```
(I already changed the Month partial to look like a list view.)

**Comment by lochmueller** [comment]
Hmm.... I think a paginate arround a month make no sense (if you display the month in a "month" style). I you want to "list" items, why your are not using one of the list views?

**Comment by shm-sl** [comment]
> (I already changed the Month partial to look like a list view.)
But it's not really about the list view, it's about the pagination by months. So i changed the title.

But if you wonder what happens inside my Month partial, here the same code with hardcoded partial:
```html
<c:loop.monthsInYear date="{date}" iteration="year">
  <f:widget.paginate objects="{year}" as="paginatedIndices" configuration="{itemsPerPage: 1, insertAbove: 1, insertBelow: 1, maximumNumberOfLinks: 5}">

    <c:loop.daysInMonth date="{year.calendar.date}" iteration="day">
      <f:if condition="{c:dateTime.indexOnDay(indices: indices, day:day.calendar.date)}">
        <f:for each="{indices}" as="index">
          <f:if condition="{c:dateTime.indexOnDay(index: index, day:day.calendar.date)}">
            <f:render partial="{index.configuration.partialIdentifier}/ListItem" arguments="{index: index}" />
          </f:if>
        </f:for>
      </f:if>
    </c:loop.daysInMonth>

  </f:widget.paginate>
</c:loop.monthsInYear>
```

**Comment by lochmueller** [comment]
@shm-sl You cannot just use "widget.paginate" on the "years". Paginate just limit the resultset. This "pagination" will never allow the user switch to the next or prevoius year. That is the reason, why there are special views for it.

Could you describe your requirement without fluid code (use case/business value)?

I think you should use the regular month view (with a few adaptions) but without loop.* ViewHelper and also without pagination.

Regards,
Tim

**Comment by shm-sl** [comment]
Basically this: https://web.archive.org/web/20190925073131/https://www.taufkirchen.de/termine/

1 page = all items of 1 month
next page = next month

**Comment by lochmueller** [comment]
OK. If you use the month view, you get exactly the "1 month" selection. You don't need any pagination or loop viewhelper: https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/Month.html You can render the events as list and link to the next/prev month like in the month-Partial (the thead part): https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Partials/Month.html

Should we close this issue?

**Comment by lochmueller** [comment]
Hey @shm-sl 
I close this issue. If there are more open questions related to templating problems, please ask in TYPO3 Slack in the #ext-calendarize channel. There are much more people that could help with such questions.
Regards, Tim
