### ISSUE TITLE
wrong links in extension.typo3.org

### ISSUE THREAD

**Issue by franzholz** [lochmueller/calendarize#368]
Some links shown on the page
https://extensions.typo3.org/extension/calendarize
do not work.

Documentation is wrong.

Only this seems to be available:
https://docs.typo3.org/p/lochmueller/calendarize/4.2/en-us/

Found an issue?
This leads to forge.typo3.org where nothing is available.
It should have been this page.

**Comment by lochmueller** [comment]
Hey @franzholz 
Thanks for the info. Fixed both links and i will check, why the 5.x documentation is not generated anymore.
Regards,
Tim
