### ISSUE TITLE
Slug "EventMapper" blows up DataMapFactory's / Extbase Tablemapping

### ISSUE THREAD

**Issue by Schweriner** [lochmueller/calendarize#377]
TYPO3 9.5.14 / PHP 7.2.

I'm currently fighting with an issue regarding the related categories of an event and displaying their name in the detail view.
It looks like there is an problem with the DataMapFactory of Extbase. To reproduce the problem you have to clear all caches - especially the DataMapFactory which stores the informations about the Models tables (Extbase-Category => sys_category).

At first: Setup the sites config routing to make usage of the extensions EventMapper-Aspect.
Clear all caches and call the list view of your events: Everything will be fine the category-names can be displayed. Now move to the detail view of an event / index and the category still shows up.
NOW: Clear all the caches again and directly call the detail view by its "speaking url": Category-Names are gone - EVERYWHERE in the frontend including the list views. If you look at the DataMapFactories cache now, you will see that it is now looking for an tx_extbase_domain_model_category table for the SysCategories which of course does not exist.

There is a forge issue about this problem: https://forge.typo3.org/issues/75399
I think the problem source of the EventMapper is using the Extbase Repositories in calendarize/Classes/Service/Url/AbstractUrl.php:39 - I think this routing is called before any Typoscript setup like config.tx_extbase is loaded so we cannot use it here.

**Comment by lochmueller** [comment]
Hey @Schweriner 
sorry for my late answer. We will drop the AbstractUrl logic shortly, because there will be a slug field in the index table, so there will be no "path lookups and build process" in URL decode/encode workflow anymore: https://github.com/lochmueller/calendarize/issues/405

I will close this issue, because it is gone after the slug field migration.

Regards,
Tim
