### ISSUE TITLE
404 error after changing an event record

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#379]
If saving an indexed event again (tstamp changes), the link to the detail view causes an 404 error.
Reindexing in scheduler generates a different URL for all events with a new index uid.
After that all previous detail URLs are no longer accessible.

Editors are constantly changing records.

TYPO3 9.5.14 , calendarize 5.0.1, RouteEnhancers.yaml

**Comment by lochmueller** [comment]
The Index Ids should change, if the date configuration is changed. Every change in the date configuration that result in outher time slots, result in a different URI. This is the basic concept of the extension.
Question: If you only change the title (a field of the event and not of the time configuration) of the event and save the record, are all links are invalid too?

**Comment by lochmueller** [comment]
No feedback. I will close this issue. It is a "normal behaviour" in the concept of the EXT.calendarize. If there are any solutions, please create a new issue incl. the solution.
