### ISSUE TITLE
InvalidFieldNameException after updating to 5.0.0+

### ISSUE THREAD

**Issue by shm-sl** [lochmueller/calendarize#380]
After updating from 4.3.0 to 5.0.0 or 5.1.0 this red popup appears:

> Missing "type" in TCA of field "['tx_calendarize_domain_model_configuration']['open_end_time']['config']".

And when saving an event record this exception appears:

>(1/2) Doctrine\DBAL\Exception\InvalidFieldNameException
>
> An exception occurred while executing 'INSERT INTO `tx_calendarize_domain_model_index` (`pid`, `start_date`, `end_date`, `start_time`, `end_time`, `all_day`, `open_end_time`, `state`, `foreign_table`, `foreign_uid`, `unique_register_key`, `hidden`, `starttime`, `endtime`, `fe_group`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [413, 1549843200, 1549843200, 70200, 0, 0, 0, "default", "tx_calendarize_domain_model_event", 5173, "Event", 0, 0, 0, ""]: Unknown column 'open_end_time' in 'field list'

**Comment by lochmueller** [comment]
Hey @shm-sl 
Major updates means: There are breaking changes or more than just downloading the new version.
You have to run DB compare to solve this problem.
I will close this issue...
Regards,
Tim
