### ISSUE TITLE
Importer: Missing DTEND throws exception

### ISSUE THREAD

**Issue by cnpartist** [lochmueller/calendarize#382]
When I try to import an ICS-file which doesn´t have a DTEND, the following error shows up:

DateTime::__construct() expects parameter 1 to be string, null given in Classes/Command/ImportCommandController.php line 88

Acoording to RFC 5545 as far as I understand it, the DTEND is optional. In my specific case, the events have a duration set instead.

**Comment by lochmueller** [comment]
This is already old. There is a complete new ICS Import process in the current version. If this problem still exists, please create a new issue.
