### ISSUE TITLE
Minor display issue in Calendarze module on hidden entries

### ISSUE THREAD

**Issue by Moongazer** [lochmueller/calendarize#389]
This is not a real problem, just a hint to a tiny issue which occurs if calendar records are set to "hidden". In this case the Calendarize module shows no title label anymore (in list module everything is working fine). I found #336 which had also issues with hidden records, but a bit different, thats why I opened a new one.

TYPO3 v9.5.15
Calendarize v5.0.1

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in the next release: https://github.com/lochmueller/calendarize/issues/426
