### ISSUE TITLE
Documentation link broken on extensions.typo3.org

### ISSUE THREAD

**Issue by nws-jstorm** [lochmueller/calendarize#391]
When using the "Extension Manual" button on https://extensions.typo3.org/extension/calendarize, we get a 404 not found exception? (Link targets https://docs.typo3.org/p/lochmueller/calendarize/4.2/en-us/Index.html)

**Comment by nws-jstorm** [comment]
I compiled the documentation myself, for this i had to rename the Includes.rst to Includes.txt, could that be a thing?

**Comment by lochmueller** [comment]
I will check this in the future. Feel free to use the documentation directly in the git: https://github.com/lochmueller/calendarize/tree/master/Documentation

**Comment by lochmueller** [comment]
I set the documentation link to Github. Thanks for the information.
