### ISSUE TITLE
Cache doesnt work for recurring Events and List View

### ISSUE THREAD

**Issue by mightynico** [lochmueller/calendarize#392]
There is a failure with clear cache and recurring Events. 
I clear the cache for normal users with "TCEMAIN.clearCacheCmd = cacheTag:calendarize_list, calendarize_detail". That works für single Events at List View Page but not for recurring Events. 
I try to change the Headline of a recurring Event, but nothings happend. The new Headline is available only at Detail-View. 
It seams there is a problem with clear Cache for List-View and recurring Events. 

I also try globally "TCEMAIN.clearCacheCmd = cacheTag:calendarize" but it is not working for me. 

Calendarize Version: 5.0.1
Typo3: 8.7.8.30 composer

thanks

**Comment by lochmueller** [comment]
Note: The "clearCacheCmd" is exploded by "," first. That means your line should be:
"TCEMAIN.clearCacheCmd = cacheTag:calendarize_list, cacheTag:calendarize_detail" (there was a missing "cacheTag:")

I Checked the integration and changes two cache tags (so other event models get other cache tags). But this is not the reason. Do you check the cache tables (tag tables), if the tags are part of the cache entries?

**Comment by lochmueller** [comment]
I close this issue (no feedback since 3 weeks). If you have more detail information, feel free to reopen this issue.
