### ISSUE TITLE
ICS Import ignores location field

### ISSUE THREAD

**Issue by nws-jstorm** [lochmueller/calendarize#393]
When importing a ICS-file, we noticed that the location field does not get recognized.
You can test it with this sample file: https://ploen.fox112-4.de/ICS/20500-FF_Laboe-2020-1.ics

**Comment by lochmueller** [comment]
Hmm... perhals just adding LOCATION here... https://github.com/lochmueller/calendarize/blob/master/Classes/Command/ImportCommandController.php#L108 ... I will check this in the near future.

**Comment by nws-jstorm** [comment]
Can you provide an update (e.g. 6.0.1) including this bugfix? So we can install the update via composer in our TYPO3-9.5 installation?

**Comment by lochmueller** [comment]
No. There will no future releases for TYPO3 versions lower than 10. The current master is already for TYPO3 10v only. So you have to patch this or fork the repository.
