### ISSUE TITLE
Caching problem in v.6.0.0 and TYPO3 9.5.18

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#394]
I have updatet to calendarize v. 6.0.0 and TYPO3 9.5.18.
Now I get "oops an error occured! Table tx_extbase_domain_model_filereference doesn't exist" if an editor cleares the cache.
Flush cache + delete typo3temp seems to resolve the problem for a time.

**Comment by lochmueller** [comment]
Hey @birgitberlin 
This error is the result of missing mapping for Extbase models. This was changed in TYPO3 v9. I added the configurattion for the next release.
Regards,
Tim
