### ISSUE TITLE
monthly entries in month of start date

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#40]
It seems that monthly schedules are incorrect for the month of the start date. Samples:
- **setup:**
- start: 01.01.2016, 08:00
- monthly / last / thursday
- **result: first shown schedule is 25.02. (expected: 28.01.)**

- **setup:**
- start: 28.01.2016, 08:00
- monthly / last / thursday
- start: 28.01.2016, 08:00
- monthly / first / thursday
- **result: first shown schedules are 28.01., 28.01. (expected: 28.01., 04.02.)**

- **setup:**
- start: 02.02.2016, 08:00
- monthly / last / thursday
- start: 02.02.2016, 08:00
- monthly / first / thursday
- **result: first shown schedules are 02.02., 02.02. (expected: 04.02., 25.02.)**

Your extension is very helpful – thank you for sharing!

**Comment by lochmueller** [comment]
Hey @saneinsane 
This is based on the structure, that the first entry is actually the manually created one. This is the same as in outlook. If you want to create a event for every x days, you have to create the event at the first event position and the repeated entries start in the next week/month etc. Or it is possible to create an Outlook event on "01.01.2016" that should appear every "monthly / last / thursday"?

Perhaps we can introduce a configuration for that behavior, with two different modes?:
- First Event is displayed, start frequence/recurrence in next integration (next month/week/day)
- First Event is base date (not displayed), start frequence/recurrence directly after the base date

Please give me same feedback...

Regards,
Tim

**Comment by saneinsane** [comment]
That makes lots of sense now. 
My suggestion: keep the functionality as it is but show an info when the start date doesn’t match the frequency settings. This way it is clearly communicated what is happening and its up to the user to change the start date if this is not what he desired.

**Comment by lochmueller** [comment]
This is hard to check. The implementation of my idea is easier ;) I will check this in the next days/weeks...

Technical information:
- Base entry: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/TimeTimeTable.php#L42
- Frequency building: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/TimeTimeTable.php#L54
- Recurrence building: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/TimeTimeTable.php#L140

**Comment by lochmueller** [comment]
It is hard to integrate. Short solution: I add context sensitive help information to the frequency field.

**Comment by saneinsane** [comment]
This is a good solution since this is more of a comprehension issue!
