### ISSUE TITLE
Check "dateLimitBrowserNext" & "dateLimitBrowserPrev" for month (respect limit in Controller)

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#400]
- Check the condition ViewHelper
- Throw a 404 page, it the Limit do not fit in the Controller

**Comment by okmiim** [comment]
> - Check the condition ViewHelper

Should be fixed in #471 / f436537e83588cafa087ad6794d3142ddf8f8366

**Comment by lochmueller** [comment]
Hey @okmiim 
No... we have to check the settings in the controller also. So it is not possible to build manually a route to a date after dateLimitBrowserNext and before dateLimitBrowserPrev.
Regards,
Tim

**Comment by okmiim** [comment]
You are right.
I was only referring to the first bullet point "Check the condition ViewHelper". 
condition ViewHelper = IfDate...ViewHelper

**Comment by lochmueller** [comment]
Fixed in current master: https://github.com/lochmueller/calendarize/commit/bef2f6d2a1f8431ba2c81a1ca46834feec59cfed
