### ISSUE TITLE
Documentation over docs.typo3.org

### ISSUE THREAD

**Issue by instruccionesaldorso** [lochmueller/calendarize#401]
Could you publish the manual under docs.typo3.org?
It's quite tricky to read it from here as .rst files.

**Comment by leofuehringer** [comment]
How is it possible to build the documentation with Sphynx in ubuntu?
`sphinx-build -c Settings.yml Index.rst` throws many errors... thanks!

**Comment by lochmueller** [comment]
Hey @leofuehringer 
I don't know. But if the base configuration is fixed, the docs on typo3.org are up-2-date again.
I will check this...
Regards,
Tim
