### ISSUE TITLE
Exception when using the option respectTimesInTimeFrameConstraints

### ISSUE THREAD

**Issue by timkarliczek** [lochmueller/calendarize#402]
When `respectTimesInTimeFrameConstraints` is enabled in the extension configuration i get the following Exception:

`Call to undefined method TYPO3\CMS\Extbase\Persistence\Generic\Query::createNamedParameter() in /var/www/html/private/typo3conf/ext/calendarize/Classes/Domain/Repository/IndexRepository.php line 649`

`createNamedParameter` is used there, but these are Extbase Repository Queries and not QueryBuilder Queries. So the use of `createNamedParameter` can be removed.

I can provide a pull request this weekend.

**Comment by timkarliczek** [comment]
Is there any chance to bring this fix into a calendarize 6.x version, that can work with TYPO3 9.x?

**Comment by lochmueller** [comment]
Hey @timkarliczek 
Sorry... but the next release is a v10 only release, because of all the annotation changes of EXT:autoloader.
I always try to create releases that match two major versions, but this time it is not possible :-/ 
Regards,
Tim
