### ISSUE TITLE
Plugin mode in Backend

### ISSUE THREAD

**Issue by hweckhardt** [lochmueller/calendarize#404]
In earlier versions (i.e. 5.0.1), it was possible to select the plugin mode in "main configuration" (for example "list only", "detail only".

After updating (Typo3 10.4.4 and calendarize 6.0.0 - download from Github) an error message occurs under "main configuration" / mode:

**Unknown type: select, render type: select**

Anything what i can do to correct this?

**Comment by lochmueller** [comment]
hey @hweckhardt ,
this problem is already fixed for the next 7.0.0 release.
I close this issue...
Regards,
Tim
