### ISSUE TITLE
Slug - news title

### ISSUE THREAD

**Issue by p380** [lochmueller/calendarize#405]
I use the news module for calendar entries.
Is there a configuration for routes where the news title would be displayed instead of the event id. Currently showing:
ex. / event / idx-38 /

I would like to do as an example:
/ event / example-event /

where the news headline is "Example event"

**Comment by lochmueller** [comment]
Good ideas are welcome. Currently this interface control the URL generation: https://github.com/lochmueller/calendarize/blob/master/Classes/Features/SpeakingUrlInterface.php

**Comment by lochmueller** [comment]
Info: See TYPOO3 Slack `Create a slug field for index is a good solution. But we need a provider logic to fill this field (default idx-ID incl. a provider for calendarize events. Then EXT:calendarize_news should provide a own provider that implement the slug logic for news records)`

**Comment by birgitberlin** [comment]
News Title + idx:
<c:link.index index="{index}" additonalParams="&news={index.originalObject.uid}">
in yaml:
- routePath: '/{event-title}/{event-index}'
   _arguments:
          event-title: 'news'
aspects:
      event-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment

If you need an url without idx, you have to switch to a NewsController action.

What I did for special needs:
extended EXT:news and use the showEvent action in my NewsController

in Fluid Partial ListItem:
<f:link.action 
absolute="1" 
pageUid="{settings.detailPid}" 
target="_top"  
title="{newsItem.title}" 
extensionName="myextension" 
pluginName="myplugin" 
controller="News" 
action="showEvent" 
arguments="{news: newsItem}" 
>{newsItem.title}</f:link.action>

**Comment by lochmueller** [comment]
I close this issue. There is great progress from @okmiim in this issue: https://github.com/lochmueller/calendarize/issues/540
Will be part of the next major release.
