### ISSUE TITLE
Editor can not add events (Admin can)

### ISSUE THREAD

**Issue by Archimedes288** [lochmueller/calendarize#406]
An editor without admin rights can not edit or create Events. All calendarize rights are given (via BE-Group). The "pulldown menu" does not open and the editor can not edit the event details.
<img width="434" alt="cal event" src="https://user-images.githubusercontent.com/50394941/87166321-b50e8a00-c2cb-11ea-8972-c39890a2163f.png">
With admin rights everything is okay.
Typo3 9.5.19
Calendarize-ext 6.0.0
Are there any hints to solve this?
Thanks!

**Comment by lochmueller** [comment]
Hey @Archimedes288 
I close this issue. Please check the User rights for the given user. He need write rights on the event table AND the configuration table (perhaps also configuration groups). There are no special configurations in the Extension. The access is controlled via be_groups only.
Regards,
Tim

**Comment by Archimedes288** [comment]
Hey Tim, thank you very much, I was able to check this again and everything is working now.
Regards, Archimedes288
