### ISSUE TITLE
Restrict registration to certain types

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#41]
It would be nice to enable cType restriction in the Register:extTables() to add the calendarize fields only to certain types. In Register:createTcaConfiguration() the method ExtensionManagementUtility::addToAllTCAtypes is called, which supports a typelist as third parameter.
(not sure whether this interferes with "required" configuration)

**Comment by lochmueller** [comment]
Hey, I add the feature. There is no problem with the "required" option, because if the field is not rendered by FormEngine it is irrelevant if the field is required at all. Thanks for the idea...
