### ISSUE TITLE
Update wizard for migration to native date fields in v6

### ISSUE THREAD

**Issue by dahaupt** [lochmueller/calendarize#411]
(As already mentioned in v6.0.0 release notes:)

Would be great to provide an update wizard to convert the database to the new structure. Patch 0db3fc886fe21c763aae7b17081073d5ac1a251c changed the db structure to real date fields (previously timestamps using integers).

**Comment by lochmueller** [comment]
hey @dahaupt 
There is already a issue for this topic: https://github.com/lochmueller/calendarize/issues/383
Regards,
Tim
