### ISSUE TITLE
Take care that the right day is selected in the loop views

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#414]
https://github.com/lochmueller/calendarize/blob/master/Resources/Private/Templates/Calendar/Year.html#L37

e.g. in Year view, always the first day is "selected"

**Comment by webian** [comment]
Probably related: in month view, `selectedDay` class is added also if month is not current.
Eg: today is 16th August, displayed month is September and `selectedDay` class is wrongly added to the 16th of September.

**Comment by lochmueller** [comment]
Fixed in current mast
