### ISSUE TITLE
Wrong months names in year view

### ISSUE THREAD

**Issue by webian** [lochmueller/calendarize#415]
Year view displays the month days right but the relative month names are wrong.
1st month is 'december' but should be 'january' and so on. It skips March name.

**Comment by lochmueller** [comment]
Could you check the result of this function: https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/Loop/MonthsInYearViewHelper.php#L22
Do you use the current master or version 6.x?

**Comment by webian** [comment]
I use 6.0.0, more precisely I'm here https://github.com/lochmueller/calendarize/commit/c38f18225a2cf131dd3a9b02544cdb23e8d0cd4a

This is the value of $months here https://github.com/lochmueller/calendarize/blob/b269622101256df71e2c067afa5fa68684b0684b/Classes/ViewHelpers/Loop/MonthsInYearViewHelper.php#L40
```
Array
(
    [1] => Array
        (
            [week] => 1
            [date] => DateTime Object
                (
                    [date] => 2020-01-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 1
            [break4] => 1
        )

    [2] => Array
        (
            [week] => 2
            [date] => DateTime Object
                (
                    [date] => 2020-02-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 2
            [break4] => 2
        )

    [3] => Array
        (
            [week] => 3
            [date] => DateTime Object
                (
                    [date] => 2020-03-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 0
            [break4] => 3
        )

    [4] => Array
        (
            [week] => 4
            [date] => DateTime Object
                (
                    [date] => 2020-04-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 1
            [break4] => 0
        )

    [5] => Array
        (
            [week] => 5
            [date] => DateTime Object
                (
                    [date] => 2020-05-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 2
            [break4] => 1
        )

    [6] => Array
        (
            [week] => 6
            [date] => DateTime Object
                (
                    [date] => 2020-06-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 0
            [break4] => 2
        )

    [7] => Array
        (
            [week] => 7
            [date] => DateTime Object
                (
                    [date] => 2020-07-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 1
            [break4] => 3
        )

    [8] => Array
        (
            [week] => 8
            [date] => DateTime Object
                (
                    [date] => 2020-08-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 2
            [break4] => 0
        )

    [9] => Array
        (
            [week] => 9
            [date] => DateTime Object
                (
                    [date] => 2020-09-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 0
            [break4] => 1
        )

    [10] => Array
        (
            [week] => 10
            [date] => DateTime Object
                (
                    [date] => 2020-10-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 1
            [break4] => 2
        )

    [11] => Array
        (
            [week] => 11
            [date] => DateTime Object
                (
                    [date] => 2020-11-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 2
            [break4] => 3
        )

    [12] => Array
        (
            [week] => 12
            [date] => DateTime Object
                (
                    [date] => 2020-12-01 00:00:00.000000
                    [timezone_type] => 1
                    [timezone] => +02:00
                )

            [break3] => 0
            [break4] => 0
        )

)
```

**Comment by webian** [comment]
@lochmueller does this bug happens to you too?
If not, then don't waste your time, I'll debug it later and I'll find where's the problem.

**Comment by webian** [comment]
I just added `<f:debug>{date}</f:debug>` to `Partials/Month.html` this is the result:
2020-01-01T00:00:00+02:00, 1577829600
2020-02-01T00:00:00+02:00, 1580508000
2020-03-01T00:00:00+02:00, 1583013600
2020-04-01T00:00:00+02:00, 1585692000
2020-05-01T00:00:00+02:00, 1588284000
2020-06-01T00:00:00+02:00, 1590962400
2020-07-01T00:00:00+02:00, 1593554400
2020-08-01T00:00:00+02:00, 1596232800
2020-09-01T00:00:00+02:00, 1598911200
2020-10-01T00:00:00+02:00, 1601503200
2020-11-01T00:00:00+02:00, 1604181600
2020-12-01T00:00:00+02:00, 1606773600

It looks right, so maybe there's a problem in the `<f:format.date format="%B %Y">{date}</f:format.date>` Fluid viewhelper.
Or maybe something regarding the time zone that I can't understand.

**Comment by webian** [comment]
Debugging `f:format.date` Fluid viewhelper for January, here: https://github.com/TYPO3/TYPO3.CMS/blob/383622db19d67eb74ccbac4fa9aa24319db3ef59/typo3/sysext/fluid/Classes/ViewHelpers/Format/DateViewHelper.php#L167
$date is:
```
DateTime Object
(
    [date] => 2020-01-01 00:00:00.000000
    [timezone_type] => 1
    [timezone] => +02:00
)
```
`$date->format('U')` equals 1577829600 that Is equivalent to 12/31/2019 @ 10:00pm (UTC)
And I think that this is the reason why it prints the localized month name of December instead of January. Because that line `return strftime($format, $date->format('U'));` doesn't consider time zone.

**Comment by webian** [comment]
I opened this issue in Forge https://forge.typo3.org/issues/92050

**Comment by lochmueller** [comment]
I checked this. The problem could also solved by EXT:calendarize, if we change alle "out and calculcation relevant dates" to UTC timezone. So there is no +2h shift in the generation anymore. I commit a change (as comment in the code). Could you check this in your system if this line solve the problem, if you activate it?:

https://github.com/lochmueller/calendarize/commit/c99b6441a4eaea4a690cff134e4835a3e80e8427

**Comment by okmiim** [comment]
I could not reproduce this bug.

Normally _strftime_ `Format the time and/or date according to locale settings` [see php.net](https://www.php.net/manual/en/function.strftime.php).
So normally it should output it in the local timezone. However if for some reason `date_default_timezone_set`, `setlocale`, the c lib or something else changes the timezone, it breaks.

As a result of this I believe, this is **not** a problem with calendarize, but more likely to be a problem with the server configuration.

@webian Maybe check your server configuration and look for differences in timezone, locale, ...

You could use `F Y` (instead of `%B %Y`) as format (for reference see [here](https://www.php.net/manual/de/datetime.format.php)) in `Month.html`, however it **WON'T** comply with the locale (e.g. this means: January won't be translated).
_(Note: Locale could also be set by `intl` php extensions for date formatting - untested.)_

**Comment by lochmueller** [comment]
@okmiim Does the last PR fix this problem? Because it is DateTime related.

**Comment by okmiim** [comment]
@lochmueller I dont think so, because the month name generation is independent from the PR changes.

**Comment by lochmueller** [comment]
I close this issue. I moved the day to Y-m-3 instead of Y-m-1 in the year view. So we avoid timezone problems. The 2-days shift should be no problem, because the date is only used for the iteration and the output of the "Month Year" header. I hope there will be a cool core solution in the future.

Regards,
Tim
