### ISSUE TITLE
Can't use input type date in search

### ISSUE THREAD

**Issue by webian** [lochmueller/calendarize#416]
It seems not possible to use HTML5 input of type `date` in search.

I can make it work if I set
`value="{startDate -> f:format.date(format: 'Y-m-d')}" type="date"`
here
https://github.com/lochmueller/calendarize/blob/2c73d90cbdc437d4fcd7e625aa61e5fa2e4b982b/Resources/Private/Templates/Calendar/Search.html#L4

But I also have to set
`'Y-m-d'`
here
https://github.com/lochmueller/calendarize/blob/2c73d90cbdc437d4fcd7e625aa61e5fa2e4b982b/Classes/Controller/CalendarController.php#L63

because the parsed value of HTML5 input of type date is always formatted yyyy-mm-dd.

But I'm not sure if this edits could brake other use cases.

**Comment by lochmueller** [comment]
Hey @webian ,
fixed in current master. The fields are HTML5 date fields in the next version.
Regards,
Tim
