### ISSUE TITLE
PHP Warning GET,POST

### ISSUE THREAD

**Issue by hweckhardt** [lochmueller/calendarize#417]
Since I installed Caledarize 7.0.0-dev I receive this PHP-Warning:

Core: Error handler (FE): PHP User Warning: Assigning addQueryStringMethod = GET,POST or POST,GET is not supported anymore since TYPO3 v10.0 - falling back to GET. in /html/typo3/typo3_src-10.4.6/typo3/sysext/extbase/Classes/Mvc/Web/Routing/UriBuilder.php line 366

Basically the extension works (many thanks !), but the warning is a little bit distracting.

**Comment by lochmueller** [comment]
Method is switched to "GET". Thank you for reporting this issue.
