### ISSUE TITLE
Error installing Version 7.0 from Git

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#418]
I get an error in Typo3 10 if I install the Version 7.0 from Github. I copied all files in my directory on the server and than I installed it from Typo3 from the installed extensions by pressing "activate"-button:

[Semantical Error] The annotation "@signalClass" in method HDNET\Calendarize\Slots\Database::loadCalendarizeTables() was never imported. Did you maybe forget to add a "use" statement for this annotation?

**Comment by lochmueller** [comment]
Hey @GitCybers ,
the slot is already migrated to an PSR-14 event listener and not part of the extension anymore:
https://github.com/lochmueller/calendarize/commit/b026a7f07be584b094194659daed769dc32cfc88
Please use the current dev-master (i suggest to install the extension via composer) and drop all caches.
Regards,
Tim
