### ISSUE TITLE
ICS import - wrong event titles

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#423]
If I create a new event (Title "Schulferien") or a configurationgroup (Title "Schulferien1") with an extern url [https://www.ferienwiki.de/exports/ferien/2020/de/nordrhein-westfalen](url) the title for all imported events ist "Schulferien(1)". But the title should be "Herbsferien", "Weihnachtsferien", etc.
You can see the result here: [http://release.kgsfrankenforst.de/termine.html](url) The event "Launch Homepage" is an own single event.

**Comment by andreheuer** [comment]
Hi @GitCybers,
even though this is a bit of topic, I would like to ask a question on this.
I am currently trying to use the ICS import of calendarize. However, I failed till now. Can you send your snippets (or steps) to import ics files into calendarize?
Thanks!!

**Comment by GitCybers** [comment]
It was my error. I tried it with the extern url function in the time option.
