### ISSUE TITLE
settings.dateLimitBrowserNext with dynamic value

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#424]
In case of static values, you have to manually correct the value every year.
A better solution is a dynamic value.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.3/Feature-63561-AddTypoScriptStdWrapStrtotime.html

plugin.tx_calendarize {
	settings {
		dateLimitBrowserPrev = TEXT
		dateLimitBrowserPrev {
			data = date: U
			strtotime = - 1 year
			strftime = %Y-%m-%d	 
		}
		dateLimitBrowserNext < .dateLimitBrowserPrev
		dateLimitBrowserNext {
			strtotime = + 1 year
		}
	}
}

**Comment by lochmueller** [comment]
hey @birgitberlin 
Added in the current master. Default is now: "-2 years" for prev and "+3 years" for next.
Thanks,
Tim
