### ISSUE TITLE
Language viewhelper problem

### ISSUE THREAD

**Issue by p380** [lochmueller/calendarize#425]
The monthly calendar template contains the viewhelper {c: language ()}, but it doesn't work. It does not return data.

Found that the function '$ tsfe-> sys_language_isocode' is deprecated.
More: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88559-TSFE-sys_language_isocode.html

**Comment by lochmueller** [comment]
Thanks for reporting. Fixed in current master and next release.
