### ISSUE TITLE
Backend module: empty title if the event is hidden

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#426]
In my case:
{index.originalObject} = News

if a news is hidden, the {index.originalObject.title} is empty, but the index items are visible and editable in the backend module
![Bildschirmfoto 2020-09-07 um 15 29 37](https://user-images.githubusercontent.com/47122416/92392755-0c3fa800-f11f-11ea-8e89-28938ef5cbf2.jpg)

**Comment by lochmueller** [comment]
Added to the current master and is part of the next release. Also the icon is the right one now.
![Bildschirmfoto 2020-10-02 um 23 59 14](https://user-images.githubusercontent.com/3907126/94973245-6f98dc00-050b-11eb-805e-db26f918ba7f.png)
