### ISSUE TITLE
de.locallang_mod.xlf: target-language="de" is missing

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#427]
in Resources/Private/Language/de.locallang_mod.xlf the target-language is missing.
The backend module shows the default language labels.

<file source-language="en" target-language="de" datatype="plaintext" original="messages" date="2013-10-21T09:49:32Z" product-name="calendarize">

**Comment by lochmueller** [comment]
Hey @birgitberlin 
The file do not exists, but I create one.
Regards,
Tim

Note: I try to mvoe the translation to crowdin.com at the moment, so translation handling will changed in one of the next versions.

**Comment by birgitberlin** [comment]
Sorry, then it was my mistake. Thanks a lot!
