### ISSUE TITLE
Wrong week switch in prev browser while modification: '-7 day'

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#429]
Prev anchor jumps to wrong week when weekStart = 0 and modification: '-7 day' (week.html)

TYPO3 9.5.0
calendarize 6.0.0
PHP 7.2.3

**Comment by sdesign6** [comment]
Seems to work with this fix #402 in calendarize 6.0.0. with TYPO3 9.5

**Comment by lochmueller** [comment]
Hey @sdesign6 ,

currently there is no "old version" planed, except there were security issues.
So I suggest to patch the version you are currently on. 

Tipp:
- Use https://github.com/cweagans/composer-patches for the patch
- Perhaps you can use the official commit as patch: https://github.com/lochmueller/calendarize/commit/2de25accd8d755786c726dfad49ea3f112797b4e.patch

Regards,
Tim
