### ISSUE TITLE
Standalone usage of IndexRepository

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#43]
Not really an issue, but odds I faced using the IndexRepository in a scheduler task – maybe you have some suggestions.
- what is the function of the $contentObject inside the repo? At least I have to pass an array [uid:-1] to my own IndexRepo instance to prevent an error thrown in EventSearch (invalid sql statement because of missing uid).
- what does the dispatched signal slot?
- inside a scheduler task, IndexRepo:getDefaultConstraints() will make the root page the storage pid – the only workaround I found was adding TS setting **config.tx_extbase.persistence.storagePid** which seems to be no nice solution.

**Comment by lochmueller** [comment]
- $contentObject is the rendering CE, but this do not exists in the scheduler interface. I fixed this here: https://github.com/lochmueller/calendarize/commit/3ba0c12ccf1d21bad28890248d9d28dce4e56cf5
- The signal Slot dispatcher is part of the core. You can define Slots for the calendarize signals to change the variables in the given signal.
- Do you have a smarter idea then "config.tx_extbase.persistence.storagePid"?

Thanks for the feedback...

**Comment by saneinsane** [comment]
Looks more like a TYPO3 core issue. "config.tx_extbase.persistence.storagePid" would be a generic setting used for all types of repositories. No smart ideas here for now...
