### ISSUE TITLE
ICS import does not create individual events

### ISSUE THREAD

**Issue by andreheuer** [lochmueller/calendarize#430]
Hi all,

I am currently struggeling in setting up the extension in my Typo3 10 installation. I have downloaded and installed the latest version in the repo.

What I am trying to do is to set up an import from an ICS file. I already saw that several others already managed this. Till now, I tried to set up the import by using groups, events and groups in events. However, even after reindexing, there were no event created (with description, location etc.) from the ICS file. Only events with the name of the event or the configuration group are created.

Can anyone give any advices? (or any hint were to find some tutorial on this)

Thank you & br
André

**Comment by andreheuer** [comment]
Hi @lochmueller,

when I want to import an ICS file in Typo3 10 using the scheduler, I cannot configure the import job:
![image](https://user-images.githubusercontent.com/10393020/94374562-79869d80-010d-11eb-9845-a82353a8f864.png)

So, I can neither add arguments to specify the ICS file not a PID to store the events like in the screenshot shared in #366.

Do you have a hint for me on how to configure the import?

Sorry for bothering :-(

BR
André

**Comment by lochmueller** [comment]
I saw that two commands are in the old structure and need some love. I will check this in the next weeks. Will be part of the next release.
