### ISSUE TITLE
PHP Catchable Fatal Error with Search

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#431]
Hi, 

I get the following error when in plugin is in search mode after typing and sending the search

PHP Catchable Fatal Error: Object of class DateTime could not be converted to string in /html/typo3/typo3conf/ext/calendarize/Classes/Domain/Repository/IndexRepository.php line 689 

calendarize 6.0.0
TYPO3 9.5.21

**Comment by lochmueller** [comment]
Hmm... sound like a addDateFrameConstraints without a "startTime" arguments. Do you have a full stack trace?
Thanks @sdesign6

**Comment by sdesign6** [comment]
Thanks for your reply. I uploaded the TYPO3 Exception as zip (html).

Thanks @lochmueller 
[TYPO3 Exception-Search.html.zip](https://github.com/lochmueller/calendarize/files/5255503/TYPO3.Exception-Search.html.zip)

**Comment by lochmueller** [comment]
Hey @sdesign6 
The bug is already solved in version 7.0.0: https://github.com/lochmueller/calendarize/commit/bdde788ee406b577f43835c4f784d6444a903200
If you need this for the old release, please create a composer patch and patch this in your version.
Regards,
Tim
