### ISSUE TITLE
Error when basic.respectTimesInTimeFrameConstraints set to true

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#435]
There seems to be an error when activating basic.respectTimesInTimeFrameConstraints (boolean)  in ext configuration. Stack Trace is attached as zip (html).
There is also no output, when plugin setting is set to Override start-date (relative) e.g. 'now'. 
Thanks @lochmueller 
[TYPO3 Exception-respectTimesInTimeFrameConstraints.html.zip](https://github.com/lochmueller/calendarize/files/5255574/TYPO3.Exception-respectTimesInTimeFrameConstraints.html.zip)

PHP 7.2-latest FPM
calendarize 6.0.0
ke_search 3.2.0
TYPO3 9.5.21

**Comment by timkarliczek** [comment]
This was already fixed in #402 (this fix is part of calendarize 7.0.0).
@lochmueller maybe you can add a support Branch vor essential fixes that should be added to calendarize 6.0.0?

**Comment by sdesign6** [comment]
Thanks @timkarliczek, the fix from #402 is working in 6.0.0. It would be great if the bugfixes could be adapted to Version 6.0.0 for compatibility with TYPO3 9.5.x. I think many people are still using T3 V9.5 with calendarize and there still seem to be some other issues as well @lochmueller. I would donate someting for fixing issues.

**Comment by lochmueller** [comment]
Hey @sdesign6 ,
Hey @timkarliczek ,

currently there is no "old version" planed, except there were security issues.
So I suggest to patch the version you are currently on. 

Tipp:
- Use https://github.com/cweagans/composer-patches for the patch
- Perhaps you can use the official commit as patch: https://github.com/lochmueller/calendarize/commit/2de25accd8d755786c726dfad49ea3f112797b4e.patch

Regards,
Tim
