### ISSUE TITLE
Categories and Frontend

### ISSUE THREAD

**Issue by EvelynGreen511** [lochmueller/calendarize#44]
Hallo Tim,

folgende Zeilen in der ext_tables.php bereiten mir Kopfzerbrechen:
if (\TYPO3\CMS\Core\Utility\GeneralUtility::compat_version('7.0.0')) {
//    $GLOBALS['TCA']['tt_content']['types']['list']['subtypes_addlist']['calendarize_calendar'] .= ',categories';
}

Wenn diese Zeile drin ist, werden die Kategorien auf einer Seite, wo das Plugin fürs Frontend eingebunden wird, nicht unter dem Reiter Categories angezeigt, sondern sind direkt im Plugin. Dort allerdings kann man keine Kategorie auswählen, die dann auch gespeichert würde. Die Änderungen verfallen einfach.
Ist die Zeile draußen, sind Kategorien da wo man sie vermutet und Änderungen wirken sich direkt auch auf die Anzeige im Frontend aus (sehr fein übrigens).

Kannst du mit den Code erklären? Ist das ein Bug oder ein Feature? :)

Ich nutze Typo3 in der Version 7.6.2

Schöne Grüße
Evelyn

**Comment by lochmueller** [comment]
You are right. Perhaps same old code lines. I drop the lines in the current master...

PS: Please write issues and feature requests in english
