### ISSUE TITLE
Output entries by category

### ISSUE THREAD

**Issue by der-phillip** [lochmueller/calendarize#444]
Is there no longer the possibility? I am using version 5.0.1, with which I can filter the output according to the content element categories. In the current 7.x version it doesn't work anymore.

**Comment by lochmueller** [comment]
I will check this for the current version...

**Comment by lochmueller** [comment]
Hey @der-phillip ,
this is fixed in current master. The annotation in Version 7 was wrong. Fixed with this commit: https://github.com/lochmueller/calendarize/commit/8eb00626b7345b08196de23ec87c1fc9c9a1e38c#diff-30080fa3938f05761f49ec5f1e8fde539d383ed4813bd5c4c6cf0dd03d256fae
Regards,
Tim

**Comment by der-phillip** [comment]
Hey @lochmueller,
I just pulled the current master from the .git and tried it out. Unfortunately, specifying the category has no effect on the output.

Just so that we understand each other correctly, I'll set the categories that I want to display in the content element in the Categories tab. In the plug-in tab there is no way to output categories¿?

**Comment by lochmueller** [comment]
Yes. That should be the case. But there is already a more new issue related to this: https://github.com/lochmueller/calendarize/issues/469
