### ISSUE TITLE
missing importer in scheduler with version 7.1.0

### ISSUE THREAD

**Issue by SmartViDi** [lochmueller/calendarize#446]
In the last version 7.1.0 there is no import funktion. In the Git-Version 3 days ago there was an importer.

**Comment by lochmueller** [comment]
The commands are migrated to symfony console commands. Please drop the old one and use the new one.

**Comment by andreheuer** [comment]
Hi @lochmueller,
I have the same issue as @SmartViDi. After installing version 7.1.0 from extension repo, no symfony commands at all are present anymore:
![image](https://user-images.githubusercontent.com/10393020/96563073-cfd89d80-12c1-11eb-8324-e6a793803e55.png)

**Comment by GitCybers** [comment]
I had to "Flush TYPO3 and PHP Cache". After flushing the cache the new import function was selecable.

**Comment by lochmueller** [comment]
I also checked this in my installation. Please clear all caches (via Install Tool) and check again. The commands should be listed...

**Comment by andreheuer** [comment]
Yep, that also worked for me. Thanks!
