### ISSUE TITLE
ongoing events in list view

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#447]
Ongoing events aren't shown in the list view after the start date is expired.

For example: Herbstferien, 12.10.2020 - 24.10.2020

Up to the 12.10.2020 the event was listed in the list view. But on the following days the event isn't listed anymore because the start date expired. Is there a chance to get the event listed during the whole time?

Thanks, Sascha

**Comment by pixelfabrik** [comment]
Same to me, **even sort by "end date" is not helping me out.** (End date in the future!) As long as the start date is in the past, the event will not show up.
Does anybody know if there is a configuration setting that events can be displayed (# of days) after expiration? If not, this would be a useful feature.

Thanks, Nick

Calendarize 7.0.0 | Typo3 v10.4

**Comment by timkarliczek** [comment]
Does enabling **Respect times in time frame constraints** in the extension configuration solve this issue?

**Comment by timkarliczek** [comment]
> 
> 
> Same to me, **even sort by "end date" is not helping me out.** (End date in the future!) As long as the start date is in the past, the event will not show up.
> Does anybody know if there is a configuration setting that events can be displayed (# of days) after expiration? If not, this would be a useful feature.
> 
> Thanks, Nick
> 
> Calendarize 7.0.0 | Typo3 v10.4

In the plugin is an option **Use relative Date**.
In the fields **Override startdate (relative)** and/or **Override enddate (relative)** you can add something like `now -7 days`. This should make it possible to include the events of the last seven days in the list view (i have not tested that yet). May be you can give it a t try.

**Comment by GitCybers** [comment]
I tried this already ([https://github.com/lochmueller/calendarize/issues/344#issuecomment-692176017](url)) but after this all dates in the frontend aren't displayed anymore. I tried several ways: now, -30, +365

**Comment by pixelfabrik** [comment]
> 
> 
> Does enabling **Respect times in time frame constraints** in the extension configuration solve this issue?

Sorry, no.

**Comment by pixelfabrik** [comment]
> 
> 
> > Same to me, **even sort by "end date" is not helping me out.** (End date in the future!) As long as the start date is in the past, the event will not show up.
> > Does anybody know if there is a configuration setting that events can be displayed (# of days) after expiration? If not, this would be a useful feature.
> > Thanks, Nick
> > Calendarize 7.0.0 | Typo3 v10.4
> 
> In the plugin is an option **Use relative Date**.
> In the fields **Override startdate (relative)** and/or **Override enddate (relative)** you can add something like `now -7 days`. This should make it possible to include the events of the last seven days in the list view (i have not tested that yet). May be you can give it a t try.

YES, that works!
But nevertheless, if an event is still running it should show up until the "end-day" is over. Otherwise - you might have events with loger duration (couple of weeks), so you have to manually control each time if the "override startdate" setting is still working for the special event AND all other events, that are already over (but getting cached by the 'override startdate' rule), still get presented on the page.

Thx for your reply - Nick

**Comment by lochmueller** [comment]
Found this problem: https://github.com/lochmueller/calendarize/commit/b9510c73bbf3beda68739c23eb2412a7743fd77c
Perhaps this issue is also related to the migration of real DB types and the selection. I will check this.

**Comment by GitCybers** [comment]
Thanks, with the new Version on Git it works without any problems.
