### ISSUE TITLE
bug with umlauts with imported events

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#456]
There is a bug with imported events. If I import an ics-file with the scheduler and if there are umlauts in the event title or the event discription the event title/discription will be cut of at the umlaut. For example:
ics-file: Bitte Termin für die Elterngespräche in der KW 47 mit den Klassenlehrerinnen vereinbaren.
Database: Bitte Termin für die Elterngespr

or ics-file: Pädagogischer Ganztag OGS
Database: P

**Comment by lochmueller** [comment]
Hey @GitCybers 
which calendarize version do you use?
The "umlauts" are not the problem I think, if the database record looks like "Bitte Termin für die Elterngespr", because there is a "ü" in the "für" that is imported.
Plase attach a ICS file as example.
Regards,
Tim

**Comment by GitCybers** [comment]
Hello Tim,
thanks for your answer. It was an error from me. The event title/description ist cut of at the "für -> f". I attached the ics-file. I had to change the file extension to jpg. Please change it back to ics
Regards, Sascha

![schultermine](https://user-images.githubusercontent.com/16307134/98927532-f2349400-24d8-11eb-95e0-29d7f070fca4.jpg)

**Comment by lochmueller** [comment]
Hey @GitCybers Cannot access the file. Could you upload the file to your own server or use a ZIP?

**Comment by GitCybers** [comment]
[schultermine.zip](https://github.com/lochmueller/calendarize/files/5530051/schultermine.zip)

**Comment by okmiim** [comment]
The ics file you uploaded is in the `ANSI` characterset encoded.
However the parsing in the current version (1844b65d8aab283b4d72d8c8010e7a9c37fdc353) uses `UTF-8` encoding, which is also the default specified in [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.1.4).
I think there is no need for a fix.

This even creates a SQL error (`utf8_unicode_ci`) (`Incorrect string value: '\xE4dagog...' for column ...`) for me.

@GitCybers 
How did you create this file / Where did you download it?
If you provide the file yourself, I suggest you should convert the file from `ANSI` to `UTF-8`.

**Comment by GitCybers** [comment]
It was a problem with ANSI. After converting to UTF-8 it works.
The ics-file is generated by a VBA code in Excel:
`Option Explicit
Sub ICS_Erstellen()
'Sortiert die Tabelle nach Startdatum und -Zeit (chronologische Reihenfolge)
'Eintr_ge ohne Datumsangabe werden dabei ans Ende gestellt
 On Error GoTo Fehler
    Dim varICS_Datei As Variant
    Dim FF As Integer
    Dim Zeitstempel As String
    Dim datum As Date, datum2 As Date
    Dim i As Long       'Zeilenzaehler
    Dim k As String
    Dim rngData As Range, rngStart As Range
    Dim intPos As Integer
    Dim sSubject As String, sLocation As String, sDescription As String, sByDay As String
'Dateiauswahldialog fÙr ICS-Datei abhaengig vom Betriebssystem _ffnen
    If Left(VBA.Environ("OS"), 7) = "Windows" Then
        'unter Windows-Betriebssystem
        varICS_Datei = Application.GetSaveAsFilename( _
                FileFilter:="ICS-Datei (*.ics),*.ics", _
                Title:="Bitte Dateiname fÙr die ICS-Datei eingeben/ausw_hlen")
    Else
        'etwas anderes - ggf. Parameter FileFilter oder FilterIndex passend fÙr _
            Betriebs-System angeben
        'MAC evtl: FileFilter:=MacID("ICS") oder FileFilter:=MacID("TEXT")
Dialog_anderes_OS:
        varICS_Datei = Application.GetSaveAsFilename( _
                Title:="Bitte Dateiname fÙr die ICS-Datei eingeben/ausw_hlen", _
                ButtonText:="Ausw_hlen")
    End If
    If varICS_Datei = False Then Exit Sub
    
'Daten aufsteigend nach Startdatum / Starzeit sortieren
    Range("A1").Select
    With ActiveSheet
        Set rngStart = .Cells(2, 1) '"A2"
        'Bereich mit den Daten inkl. Titelzeile
        Set rngData = .Range(.Cells(2, 1), .Cells(.Rows.Count, 1).End(xlUp).Offset(0, 11))
    End With
    With rngData
        .Sort Key1:=.Range("C1"), Order1:=xlAscending, _
            Key2:=.Range("D1"), Order2:=xlAscending, Header:=xlYes, _
            OrderCustom:=1, MatchCase:=False, Orientation:=xlTopToBottom
    End With
'Erstellt den Zeitstempels
    'wird ben_tigt fÙr die UID des Kalendereintrages und fÙr die Felder
    '"erstellt am" --> "DTSTAMP" und "zuletzt geaendert am" --> "LAST-MODIFIED"
    'einfachere Form fÙr Zeitstempel
    Zeitstempel = Format(Now, "YYYYMMDD""T""hhmmss""Z""")

'Erstellt die Kalenderdatei
'Dateiname kann frei gew_hlt werden
'Der entsprechende Ordner MUSS vorhanden sein, da sonst ein Fehler auftritt
'Datendatei erstellen und zum beschreiben _ffnen
    FF = FreeFile()
    Open varICS_Datei For Output As FF

'Schreibt den allgemeinen Teils der Kalenderdatei
    Print #FF, "BEGIN:VCALENDAR"
    Print #FF, "VERSION:2.0"
    Print #FF, "PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.0//EN"
    Print #FF, "X-WR-TIMEZONE:Europe/Berlin"
    Print #FF, "X-WR-CALNAME;VALUE=TEXT:Schulkalender KGS Frankenforst"
    Print #FF, "X-APPLE-CALENDAR-COLOR:#ff0084"
    Print #FF, "COLOR:#ff0084"

'Schleife zur Ermittlung aller Eintr_ge
'Benutzt alle Datens_tze, die ein Start-Datum enthalten
    With rngStart
    i = 1
    While .Offset(i, 2) <> ""
    
    'Ermittelt die Daten fuer den Kalendereintrag um Umlaute zu Šndern folgendes zwischen die beiden offen Klammern schreiben: fncSonderzeichen
    'SUBJECT
        sSubject = Left((.Offset(i, 0).Text), 65)
    'LOCATION
        sLocation = Left((.Offset(i, 1).Text), 65)
    'DESCRIPTION
        sDescription = (.Offset(i, 7).Text)
        
    'PrŸfen ob Termin = ganzer Tag
    'Die Angaben mit dem Zusatz 2 werden fuer das Ende des jeweiligen Termins gebraucht
    'Das Ende eines ganztaegigen Ereignisses ist immer der darauffolgende Tag
        If .Offset(i, 6) = True Then
            datum = .Offset(i, 2)
            datum2 = Application.WorksheetFunction.Max(.Offset(i, 4), .Offset(i, 2)) + 1
        Else
            datum = .Offset(i, 2) + .Offset(i, 3)
            datum2 = Application.WorksheetFunction.Max(.Offset(i, 4), .Offset(i, 2)) + .Offset(i, 5)
        End If
        k = Format(i, "0")
    
    'Schreibt den Kalendereintrag
    'Der Zusatz "-@Schulkalender-" in der UID kann nach Belieben geaendert werden
    'k ist ein durchlaufender Zaehler
        Print #FF, ""
        Print #FF, "BEGIN:VEVENT"
        Print #FF, "UID:" & Zeitstempel & "-@Schulkalender-" & k
        '…ffentlicher oder privater Kalendereintrag - Standard = PUBLIC
        If .Offset(i, 11).Text = "" Then
            Print #FF, "CLASS:PUBLIC"
        Else
            Print #FF, "CLASS:" & .Offset(i, 11).Text
        End If
        Print #FF, "SUMMARY:" & sSubject        'Zusammenfassung/Betreff
        
        'Print #FF, "DESCRIPTION:"               'Beschreibung / Notiz
        'Text in Zeilen mit je 60 Zeichen in die Text-Datei schreiben
        For intPos = 1 To Len(sDescription) Step 60
            sByDay = Mid(sDescription, intPos, 60)
            Print #FF, "DESCRIPTION:" & Mid(sDescription, intPos, 60)
        Next
        Print #FF, "LOCATION:" & sLocation      'Ort"
        
'        Print #FF, "X-MOZILLA-ALARM-DEFAULT-LENGTH:0"
'        Print #FF, "X-MOZILLA-RECUR-DEFAULT-UNITS:years"      'Wiederholung-Einheit
        
        Select Case rngStart.Offset(i, 8).Text
            Case "" 'keine Wiederholung
            
            Case "YEARLY"
                Print #FF, "RRULE"
                With rngStart.Offset(i, 10) 'COUNT
                    Print #FF, " :FREQ=YEARLY;INTERVAL=1" & IIf(.Text <> "", ";COUNT=" & .Text, "")
                End With
                
            Case "QUARTERLY"
                Print #FF, "RRULE"
                With rngStart.Offset(i, 10) 'COUNT
                    Print #FF, " :FREQ=MONTHLY;INTERVAL=3;BYMONTHDAY=" & Format(Day(datum), "0") _
                        & IIf(.Text <> "", ";COUNT=" & .Text, "")
                End With
                
'RRULE:FREQ=MONTHLY;COUNT=8;INTERVAL=3;BYMONTHDAY=1
            Case "MONTHLY"
                Print #FF, "RRULE"
                With rngStart.Offset(i, 10) 'COUNT
                    Print #FF, " :FREQ=MONTHLY;INTERVAL=1" & IIf(.Text <> "", ";COUNT=" & .Text, "")
                End With
                
            Case "WEEKLY"
                With .Offset(i, 9) 'Zusatzangabe
                    Select Case .Text
                        Case "" 'Wiederholungs-Wochentag wird aus 1. Datum ermitelt
                            Select Case Weekday(datum, vbSunday)
                            Case 1: sByDay = "SU"
                            Case 2: sByDay = "MO"
                            Case 3: sByDay = "TU"
                            Case 4: sByDay = "WE"
                            Case 5: sByDay = "TH"
                            Case 6: sByDay = "FR"
                            Case 7: sByDay = "SA"
                            End Select
                        Case Else
                            sByDay = .Text
                    End Select
                End With
                Print #FF, "RRULE"
                With rngStart.Offset(i, 10) 'COUNT
                    Print #FF, " :FREQ=WEEKLY;BYDAY=" & sByDay & IIf(.Text <> "", ";COUNT=" & .Text, "")
                End With
                
            Case "DAILY"
                Print #FF, "RRULE"
                With .Offset(i, 10) 'COUNT
                    Select Case rngStart.Offset(i, 9).Text 'Zusatzangabe
                        Case "", "Jeden Tag"
                            Print #FF, " :FREQ=DAILY" & IIf(.Text <> "", ";COUNT=" & .Text, "")
                        Case "Mo bis Fr"
                            Print #FF, " :FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR" & IIf(.Text <> "", ";COUNT=" & .Text, "")
                    End Select
                End With
        End Select
        
        'Start - Datum/Zeit
        If .Offset(i, 6) = True Then
            Print #FF, "DTSTART;VALUE=DATE:" & Format(datum, "YYYYMMDD")
        Else
'            Print #FF, "DTSTART:" & Format(datum, "YYYYMMDD""T""hhmmss""Z""")
            Print #FF, "DTSTART:" & Format(datum, "YYYYMMDD""T""hhmmss")
        End If
        'Ende - Datum/Zeit
        If .Offset(i, 6) = True Then
            Print #FF, "DTEND;VALUE=DATE:" & Format(datum2, "YYYYMMDD")
        Else
'            Print #FF, "DTEND:" & Format(datum2, "YYYYMMDD""T""hhmmss""Z""")
            Print #FF, "DTEND:" & Format(datum2, "YYYYMMDD""T""hhmmss")
        End If
        Print #FF, "DTSTAMP:" & Zeitstempel                            'Speicherzeitpunkt
        Print #FF, "LAST-MODIFIED:" & Zeitstempel                      'Letzter Aenderungszeitpunkt
        Print #FF, "END:VEVENT"
        
        i = i + 1
    Wend
'Ende der Schleife
    End With 'rngZelle
    
'Ende der Kalenderdatei
    Print #FF, ("END:VCALENDAR")
    
'Datendatei wieder schliessen
    Close #FF
'Sortiert die urspruengliche Tabelle in alphabetischer Reihenfolge
    With rngData
        .Sort Key1:=.Range("A1"), Order1:=xlAscending, _
              Key2:=.Range("B1"), Order2:=xlAscending, Header:=xlYes, _
              OrderCustom:=1, MatchCase:=False, Orientation:=xlTopToBottom
        .EntireRow.AutoFit
    End With
Fehler:
    With Err
        Select Case .Number
            Case 0 'alles OK
            
            Case Else
                MsgBox "Fehler-Nr.: " & .Number & vbLf & .Description
                Close
        End Select
    End With
End Sub

Sub run()
    'Application.run "'ICS_erstellen.xls'!ICS_Erstellen"
    Call ICS_Erstellen
End Sub

Sub edit()
    Application.Goto Reference:="ICS_Erstellen"
End Sub

Function fncSonderzeichen(sText As String) As String
    'Ersetzt Sonderzeichen und Zeilenschaltungen, da Sunbird hatte Probleme mit Sonderzeichen, _
        aus diesem Grund habe ich die "Wichtigsten" ersetzt
    Dim arrZeichen, arrReplace, intZ As Integer
    Dim sErgebnis As String
    arrZeichen = Array("_", "Û", "_", "É", "Ù", " ", "¤", _
        "Š", "€", "š", "…", "Ÿ", "†", "§", Chr(10)) ', " ")
    arrReplace = Array("ae", "Ae", "oe", "Oe", "ue", "Ue", "ss", _
        "ae", "Ae", "oe", "Oe", "ue", "Ue", "ss", "\n") ', "e")
    sErgebnis = sText
    For intZ = LBound(arrZeichen) To UBound(arrZeichen)
        sErgebnis = Replace(sErgebnis, arrZeichen(intZ), arrReplace(intZ))
    Next
    fncSonderzeichen = sErgebnis
End Function

`
The school works with Excel for the dates.

**Comment by lochmueller** [comment]
OK. Thanks for your feedback... so I close this issue.

PS: Crazy VBA script ;)
