### ISSUE TITLE
List view for calendar widget shows wrong events (from the day before)

### ISSUE THREAD

**Issue by wazum** [lochmueller/calendarize#459]
See screenshot. 

The values in the database (table `tx_calendarize_domain_model_configuration`) are correct (`start_date = 2020-11-14`, `end_date = 2020-11-14`).
The date on the server is correct too
```bash
$ date
Sat Nov 14 09:02:06 UTC 2020
```

URL: `?tx_calendarize_calendar%5Bday%5D=15&tx_calendarize_calendar%5Bmonth%5D=11&tx_calendarize_calendar%5Byear%5D=2020`

![Screenshot 2020-11-14 at 09 58 02](https://user-images.githubusercontent.com/146727/99143748-2c7c6d80-2660-11eb-9cf3-f12a4c04709e.png)

**Comment by lochmueller** [comment]
Do you check the PHP timezone condiguration. The server use UTC, but your PHP is running under a other timezone, perhaps...

**Comment by wazum** [comment]
@lochmueller I propose the fix in the linked pull request.

And the second issue was a wrong comparison.

**Comment by wazum** [comment]
For reference: there's also a core bug in TYPO3 9 and 10 with DataHandler when copying fields with `date` type:
https://forge.typo3.org/issues/89914
