### ISSUE TITLE
Question/Feature ics-link with webcal:

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#461]
Hello,
is there a chance to set webcal: in front of the ics-download-link? I use this code for the link: `<f:link.action action="list" format="ics" arguments="{hmac: extended.pluginHmac}"><img src="/fileadmin/user_upload/iCal_Symbol_klein.png" alt="" title="" style="height: 3rem;">Kalender downloaden</f:link.action>`
In link-action there is no parameter to set a prefix.

**Comment by lochmueller** [comment]
Hey @GitCybers ,
sorry but I don't understand the problem?! What is "wecal"? What kind of prefix?
Regards,
Tim

**Comment by GitCybers** [comment]
Sorry, there was a typo in the text: webcal:
If you have a link with webcal: in front of the link like webcal:www.muster.de/muster.ics the link is defind as a calendar. iOS for example subscribes the new calendar to your calendar with one klick.

**Comment by lochmueller** [comment]
Ahh... ok. TYPO3 have to support this, before I can integrate this into EXT:calendarize. I think the „other“ scheme in the URL „webcal:“ will not pass the Site handling middleware in the Frontend middleware stack :-/ Do you check this? Could you call the URL in TYPO3 v10 in the Frontend?

**Comment by GitCybers** [comment]
If I create an text element on my side in the type3 backend with a link like this, it works:
`<a href="webcal://www.muster.de/termine.html?tx_calendarize_calendar%5Bformat%5D=ics&amp;tx_calendarize_calendar%5Bhmac%5D=d09408665ef58ef0ce5cfbe298d91cc561c91af9&amp;cHash=60b04c3499c046d664d97e1f1c14d4ac" target="_top">Kalender abonieren</a>`
I copied the URL from the generated ics-link in the calendarize list view and added the webcal: in front of. Normaly Typo3 ads the http:// in front of the URL automatically after adding a link.

**Comment by lochmueller** [comment]
No news since 2y. I will close this issue. If there are any news on this topic, feel free to reopen this.
