### ISSUE TITLE
Fetch external ics - get title

### ISSUE THREAD

**Issue by rabele** [lochmueller/calendarize#463]
Hi Tim,
is it intended / possible to get the title (SUMMARY) of events when fetches with event oder group configuration in backend? 

I tried to get events from an ics calendar and the times are imported correctly but the title isn't fetched. In the frontend all of these events have got the same title (configuration title).

Thanks a lot
Regards
Ralf

**Comment by lochmueller** [comment]
Ist composer mode enabled? Do you use the most current version or dev-master?

**Comment by rabele** [comment]
Composer mode isn't enabled. I will try dev-master and try again.

**Comment by lochmueller** [comment]
Note: in composer mode you will get sabre/vobject and a more advanced import process. In non-composer installations there is only a fallback integration. Feel free to fix the fallback layer.

**Comment by okmiim** [comment]
There are two ways to import external ics:

- A configuration with type "external"
    - only imports the times, so the same event (title) occous multiple times
    - (seems like you are using this)
- A scheduler task "Execute console commands" -> "calendarize:import"
    - creates a seperate event for each ics entry

**Comment by rabele** [comment]
Thank you very much Tim and okmiim. The scheduler task ist doing a great job.
