### ISSUE TITLE
getConfigurationTitleTime throws TypeError in Backend

### ISSUE THREAD

**Issue by j4k3** [lochmueller/calendarize#468]
TYPO3 10.4.10, PHP 8, calendarize 7.3.0

When listing any Backend pages with calendarize indexes with an empty end_date, a TypeError is raised that the catch block can't catch:

(1/1) TypeError
strftime() expects parameter 2 to be integer, boolean given

in /html/typo3/typo3conf/ext/calendarize/Classes/Service/TcaService.php line 150
...                $dateStart = strftime(DateTimeUtility::FORMAT_DATE_BACKEND, (new \DateTime($row['start_date']))->getTimestamp());

Additionally, (string)"0000-00-00" equals boolean true, but should be treated like a zero value instead.

Here's a quick fix for the function that assumes more type checks:

    /**
     * Get the title for a configuration time.
     *
     * @param $row
     *
     * @return string
     */
    protected function getConfigurationTitleTime($row)
    {
        $title = '';
        if($row['start_date'] && ($row['start_date']!='0000-00-00')){
            try {
                if(is_object($dateTimeStart = new \DateTime($row['start_date']))){
                    if(is_integer($timestampStart = ($dateTimeStart)->getTimestamp())){
                        $dateStart = strftime(DateTimeUtility::FORMAT_DATE_BACKEND, $timestampStart);
                        $title .= $dateStart;
                        if(is_object($dateTimeEnd = new \DateTime($row['end_date']))){
                            if($row['end_date'] && ($row['end_date']!='0000-00-00')){
                                if(is_integer($dateEnd = strftime(DateTimeUtility::FORMAT_DATE_BACKEND, ($dateTimeEnd)->getTimestamp()))){
                                    if ($dateStart !== $dateEnd) {
                                        $title .= ' - ' . $dateEnd;
                                    }
                                }
                            }
                        }
                    }
                }
            } catch (\Exception $exception) {
            }
        }
        if ($row['all_day']) {
            $title .= ' ' . TranslateUtility::get('tx_calendarize_domain_model_index.all_day');
        } elseif ($row['start_time']) {
            $title .= ' <br />' . BackendUtility::time($row['start_time'] % DateTimeUtility::SECONDS_DAY, false);
            $title .= ' - ' . BackendUtility::time($row['end_time'] % DateTimeUtility::SECONDS_DAY, false);
        }
        if ($row['frequency'] && Configuration::FREQUENCY_NONE !== $row['frequency']) {
            $title .= ' <br /><i>' . TranslateUtility::get('configuration.frequency.' . $row['frequency']) . '</i>';
        }

        return $title;
    }

**Comment by j4k3** [comment]
I just noticed that there is something much more fundamentally broken here. All entries in the index table have zero value start_date and end_date entries after updating.

**Comment by lochmueller** [comment]
Thanks @j4k3 for opening and closing this issue :) 

Note for other readers of this issue: Please run the upgrade wizard for the migration of the fields.

**Comment by j4k3** [comment]
I don't really want to reopen this issue again, but for whatever reason none of the three update tasks show up in the Update Wizard. All three class names show up in the system configuration in $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update'], but none of them is displayed.

**Comment by lochmueller** [comment]
Hey @j4k3 Are they listed as "already done" or they aren't listed at all?

**Comment by j4k3** [comment]
Hey Tim,
no, I've checked that. They aren't listed at all. I've just reinstalled calenarize just to be sure, but they still aren't there.

**Comment by lochmueller** [comment]
Hey @j4k3 this "could be" right. A Upgrade wizards, that was not executed before and do not need to execute (updateNecessary function in the wirzard) is not listed at all.
Regards,
Tim

**Comment by lochmueller** [comment]
Furthermore. I streamline the classes a little bit: https://github.com/lochmueller/calendarize/commit/66ce1a5fda92b1ed65e069df371694f8e81b5591 👍

**Comment by j4k3** [comment]
Hey Tim @lochmueller,

thanks for taking the time. I just applied the patch, flushed all caches and checked. The Updates still don't appear in the Upgrade Wizard. Other Updates from Extensions however, are listed. Can I do anything to debug this further?
I think I can recreate the neccessary update SQL queries from the script however, so if this s an edge case or localized problem that only happens to me, then please don't waste your time on it.

**Comment by lochmueller** [comment]
If the upgrade wizards are not display, they don't need to be executed. Please check the "updateNecessary" function of the wizard that should be there and check why the function return "false". Please create a new issue, if you find a bug related to the upgrade wizards.

Note: The Patch was just a "cleanup" and no fix, because I don't found a issue.
