### ISSUE TITLE
Realurl in autoconf and calendarize

### ISSUE THREAD

**Issue by alat54** [lochmueller/calendarize#47]
Hi, 

When i activate realurl autoconf i have this message on pages with calendarize : 
Fatal error: Class 'tx_realurl_advanced' not found in /var/www/lib/typo3_packages/typo3_src-7.6.2/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4505

Can you explain what's the problem?

Thanks a lot

**Comment by lochmueller** [comment]
Hey @alat54 
Do you have same deeper information, like the function stack in the error situation? Who tries to load "tx_realurl_advanced". Do you use the current version of realurl?

Regards,
Tim

**Comment by alat54** [comment]
I'm using the last version of realurl (ter version : 2.0.0), last version of calendarize (ter version : 2.0.2).
Parameters of your plugin are default, realurl too.

On my page there is a month view, with 5 events. The page worked with realurl desactivated.

Thanks

**Comment by lochmueller** [comment]
Ok... tehre is no 2.0.0 TER version of realurl ;) I will run same tests with realurl 2.0.0 (at least if the release is public in TER) in the next days...

**Comment by alat54** [comment]
Oh that's my fault sorry, i test the ter version this afternoon.

**Comment by alat54** [comment]
I have installed the ter version but no events showed (they exist)... what a curious problem...

**Comment by lochmueller** [comment]
Fix the bug, for the new realurl version. Please test the current master. If the problem still exists, please create a new ticket... :+1:

**Comment by alat54** [comment]
Another upgrade of realurl broke calendarize :( 

Fatal error: Call to a member function convertToSafeString() on null in /var/www/_minisites/htdocs/typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php on line 252

Thanks
