### ISSUE TITLE
WeekView DateTime::setISODate() Exeption

### ISSUE THREAD

**Issue by der-phillip** [lochmueller/calendarize#470]
After Update from 7.2.0 to 7.3.0 I have this error on Week.html Template

`DateTime::setISODate() expects parameter 1 to be int, string given`

at DateTime->setISODate('2020', 43, 1)
in /typo3conf/ext/calendarize/Classes/Utility/DateTimeUtility.php line 75
```
    public static function convertWeekYear2DayMonthYear($week, $year, $startDay = 1): \DateTime
    {
        $date = self::getNow();
        $date->setTime(0, 0, 0);
        $date->setISODate($year, $week, $startDay);

        return $date;
    }
```

**Comment by okmiim** [comment]
Mhmm, I changed that bit lately...
I will take a look later.
