### ISSUE TITLE
Real url error

### ISSUE THREAD

**Issue by alat54** [lochmueller/calendarize#48]
Hi, 

I have tried your master with realurl 2.0.0 but i have this error now : 

> Fatal error: Class 'DmitryDulepov\Realurl\Encoder\UrlEncoder' not found in /var/www/lib/typo3_packages/typo3_src-7.6.2/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4505

**Comment by lochmueller** [comment]
Does the class exists? EXT:realurl/Classes/Encoder/UrlEncoder? Because it is part of the current master:
https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php
Please clear all caches and delete also typo3temp/autoload...

**Comment by alat54** [comment]
I have download the master of realurl and delete all cache and autoload directory.
It seems to be nice with that.
I upgrade of extension via ter will not break that :)

Thanks

**Comment by lochmueller** [comment]
OK... closed :) If there are more problem please create a new issue...
