### ISSUE TITLE
viewhelper for title does not work

### ISSUE THREAD

**Issue by andreaskastl** [lochmueller/calendarize#482]
Hi @lochmueller,

the view helper for title tag seems to be broken. I had a look at recent news extension and page title API spec. Here is my proposal how to fix this issue - please verify.

New class Classes/Seo/CalendarizeTitleProvider.php
[CalendarizeTitleProvider.php.txt](https://github.com/lochmueller/calendarize/files/5735357/CalendarizeTitleProvider.php.txt)

Adjustments in Classes/ViewHelpers/TitleTagViewHelper.php
[TitleTagViewHelper.php.txt](https://github.com/lochmueller/calendarize/files/5735361/TitleTagViewHelper.php.txt)

Additional typoscript setting
config.pageTitleProviders {
  calendarize {
    provider = HDNET\Calendarize\Seo\CalendarizeTitleProvider
    before = altPageTitle,record,seo
  }
}

Regards
Andreas

**Comment by lochmueller** [comment]
Hey @andreaskastl 
yes. This is the right way. Could you create a pull request?
Regards & Merry Christmas,
Tim
