### ISSUE TITLE
multi-day events not shown properly in day view

### ISSUE THREAD

**Issue by andreaskastl** [lochmueller/calendarize#483]
Hi @lochmueller ,

multi-day events are not shown properly in a day view. Example: 
- event start date = 2021-01-27
- end date = 2021-01-30
- all day flag is set (no time selected)

When I open the day view for 2021-01-27 no events are shown. Same for 2021-01-30. Only for 2021-01-28 and 2021-01-29 the event is shown on day view. It seems that first and last day of this multi-day event are cut of from index/view.
In month view the multi-day event is shown correctly on all 4 days.

I checked my templates but could not find the issue. I use fresh 7.3 snapshot from git on Typo3 10.4.12.
Would you please check the day view logic for multi-day events?

Regards
Andreas

**Comment by okmiim** [comment]
Hi @andreaskastl,
I can confirm that. I believe the problem lies inside `IndexRepository::addDateFrameConstraints`.
A workaround is to enable `basic.respectTimesInTimeFrameConstraints ` in the extension settings.

Since I am currently also refactoring that function, I fix that later.
