### ISSUE TITLE
Frontend error

### ISSUE THREAD

**Issue by wannensn** [lochmueller/calendarize#486]
Hi,
I get the following error, when displaying an event list in the frontend:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function dispatch() on null | Error thrown in file /typo3conf/ext/calendarize/Classes/Domain/Repository/IndexRepository.php in line 643

What I did:
I installed the extension with TER. Some test events where displayed at this point. Because the categorization of events by using typo3 categories wasn't working I updated the extension. Therefore I downloaded the code as zip file from the repository, removed the extension folder online and uploaded the the new files. To be honest I'm not a typo3 pro and I'm not sure if that's the right way to update the extension manually ;-(

Thanks,
Stephan

**Comment by okmiim** [comment]
Hi @wannensn,
could you clean the cache in the install tool and retry?

The categories currently don't work (see #469).

_Note_: The current git-version contains breaking changes, so you may need to run the update wizard/db.

**Comment by wannensn** [comment]
Thanks, that did the trick.
