### ISSUE TITLE
Feature request: search by category

### ISSUE THREAD

**Issue by der-phillip** [lochmueller/calendarize#492]
Hi, the extension is getting better and better. Here is a feature I would like to see in one of the next versions.

- Inclusion of a category search (dropdown) in the search form.
- Ajax reload of the categories after submitting the search.
- Display of the assigned categories at the event itself

**Comment by artus70** [comment]
On your third point: To display assigned categories in the list, add code like this in the Partial Event/ListItem.html:

```
<div class="cal_categories">
	<f:for each="{event.categories}" as="category" iteration="itemIteration">
	<span class="category c{category.uid}" data-calcat="{category.uid}"><i class="fa fa-tags"></i>&nbsp;{category.title}</span>
	</f:for>
</div>
```

(The code with `category.uid` will allow you to i.e. hide special categories by CSS.)

**Comment by lochmueller** [comment]
Hey @der-phillip & @artus70 
I added the example output with this commit https://github.com/lochmueller/calendarize/commit/c81851d2cb8e3b9275e942cf4de225b1f187a962 Furthermore I changed the search event to support categories by the custom search. So a dropdown could be displayed and the search respect the selection of the category.
The AJAX wish will not be part of the EXT:calendarize extension. You could handle AJAX stuff in your frontend integration.
Regards,
Tim

**Comment by bavarianbytes** [comment]
The search/filter via category is very nice and essential for working with categorized events!
As far as is understand the code of commit [c81851d](https://github.com/lochmueller/calendarize/commit/c81851d2cb8e3b9275e942cf4de225b1f187a962) it's only possible to filter for **one** category id, isn't it?

It would be cool if you could also filter for multiple category ids, maybe comma-separated, e.g. '1,3,9'. Therefore users could built a multi-category-filter (checkboxes or similar) in the frontend.

**Comment by lochmueller** [comment]
Hey @bavarianbytes 
Feel free to create a new PR to change the DTO and templates from integer to array. Good point.
Regards,
Tim

**Comment by bavarianbytes** [comment]
I will do! But will need some time.
