### ISSUE TITLE
cal migration wizard assumes categories are still in tx_cal_category and tx_cal_event_category_mm

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#494]
The latest version of cal already uses the sys_categories.

Because of this, the existing cal migration wizard will not correctly migrate the event / category relations. I think what I will do now is use the existing migration wizard and make some changes for the categories.

**Comment by sypets** [comment]
Update: I managed to migrate with some modifications to the upgrade wizard. I could make this available (as PR or as separate extension), but I am not sure how you want to handle this and if you still making updates to the wizard.

Also, the plugins are not converted (and I did not find any wizard to do that) so I will be working on that too.

**Comment by lochmueller** [comment]
Hey @sypets 
Great. I could merge the changes to the EXT:calendarize, if you have fixed to the most current EXT:cal version.
Regards,
Tim
