### ISSUE TITLE
cal migration: how to define time windows in calendarize?

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#500]
In Cal, we could use TS to narrow down the time window of the dates shown (here: to show the archive of a particular semester):

```
view.list.starttime=2011-04-01
view.list.endtime=2011-09-30
```

Is there a way to define something like this in Calendarize? However, it would have to be possible to do this in Flexform, as our editors are not allowed to edit template things like constants.

**Comment by lochmueller** [comment]
Right. There is also a more generic configuration for the allowed range in TS:  https://github.com/lochmueller/calendarize/blob/master/Configuration/TypoScript/constants.txt#L5
