### ISSUE TITLE
Translated events not displayed on translated page (with language setting = "strict")

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#504]
I don't know if I am missing something. I tested this on 2 systems, one with the migrated content. On the other with events created from scratch.

## System 

* calendarize: 8.1.0 (also reproducible with "master")
* TYPO3: 10.4.13

## Reproduce

1. create storage page with some events
2. localize the events (translate)
3. create plugin List+Detail on one page, leave most configuration as default
4. localize the page, copy the plugin (or set language in plugin to -1: has same result).

Load translated page in Frontent. No events are displayed. Events are displayed for default language though. 

## Problem

On the translated page, no events are displayed. Only if I create an event with language = -1, the event is displayed.

**Comment by sypets** [comment]
More information: I tested with introduction package + TYPO3 10.4.13 and the translated events appear correctly. So it looks like it might be a problem on our end or with our configuration.

I narrowed it down now: 
The language setting was "**strict**".

When I change it to "fallback", the events are displayed.

Also, when I switch to "strict" in the site based on Introduction Package, the events on the translated page are no longer displayed.

I think this should also work with "strict". We had no problem with EXT:news: records. They also appeared on translated pages.

----

I will update description above and create separate issue for the error message - seems to be unrelated

**Comment by okmiim** [comment]
The behavior was irregular, however:
One problems seems to be within the Index, where the `l10n_parent` is not generated properly (always `0`).

A workaround is to disable the parent column. For this add the following in `Configuration/TCA/tx_calendarize_domain_model_index.php`. This however makes the `fallback` mode useless.
```php
unset(
    $base['ctrl']['transOrigPointerField'],
    $base['ctrl']['transOrigDiffSourceField'],
    $base['columns']['l10n_parent'],
    $base['columns']['l10n_diffsource']
);
```
---
The value for `l10n_parent` is generated inside `IndexPreparationService`.
From my obersvations where clause contains `tstamp` and `crdate` resulting in almost no matches.

https://github.com/lochmueller/calendarize/blob/7a50c49367d1d735402cec6559400ce9d61708ec/Classes/Service/IndexPreparationService.php#L76-L112

This needs more investition. I probaly will look into this back soon.
