### ISSUE TITLE
Error message: Localization failed: "languageField" and "transOrigPointerField" must be defined ...

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#505]
When localizing an event, I get an error message when the form is opened:

`1: Localization failed; "languageField" and "transOrigPointerField" must be defined for the table tx_calendarize_domain_model_configuration`

## System

* TYPO3 10.4.13
* calendarize 8.1.0 (can also be reproduced with "master")
* Introduction package TYPO3 (with bootstrap_package), created with Composer

**Comment by okmiim** [comment]
Related #490
Related #315
Reappeared due to #466

**Comment by artus70** [comment]
Does this mean that actual localization of events is not possible right now?

**Comment by okmiim** [comment]
@artus70 Localization still works fine and is possible. You can just ignore the error message.

**Comment by artus70** [comment]
Ah, thanks! But it's only possible in web->list view, right? Or can I localize in web->Calendarize view, too?

**Comment by okmiim** [comment]
@artus70 Inside `web->Calendarize` it is kinda possible. For this open the event in edit mode. In the top bar (where close, save, ... are) you can find a dropdown with languages and localize it.

**Comment by artus70** [comment]
You are right - this way it's easy to accomplish. Good hint, thank you!

**Comment by lochmueller** [comment]
Hey everyone... I enable translation for the configurations and set it to l10n_mode exclude (and remove the read only). The read only cause some problems, so I think this is the best solution: https://github.com/lochmueller/calendarize/commit/d970b109d2355dc2d17eda9e426cb349cf6fdb2f
