### ISSUE TITLE
Not possible to list events in the past?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#508]
## Problem

It is not possible to show events in the past in list view.

## System

* TYPO3 10.4.13
* calendarize: current "master"

## Reproduce

I tried the following combinations:

1. TypoScript constant:

plugin.tx_calendarize.settings.listStartTime =-1 year

2. In FlexForm:

settings.useRelativeDate=1
settings.overrideStartRelative=-1 year
settings.overrideEndRelative=now

I am not sure if this is so by design, a bug or I am doing something wrong.

**Comment by lochmueller** [comment]
Hey @sypets 
There is a separate view (pastAction) that can be used, if you want to display only events in the past. 
For a view like "-1 month -> +1 month" we have to check the settings/integration.
Regards,
Tim

**Comment by sypets** [comment]
Yes the "past" view works. 

However, the sort order DESC does not in this case, so if you want to display past events in descending order I have not found a way to do this.

Also the relative start / stop time is not available as mentioned.

**Comment by sypets** [comment]
Closing this now in favor of more specific issue #511
