### ISSUE TITLE
DESC sorting does not work correctly with "past" view (and paging)

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#511]
## Reproduce

* Sort by `[settings.sortBy]`: Start date `[start]`
* Sorting `[settings.sorting]`: `DESC`
*  Mode `[switchableControllerActions]`: Past `[Calender->past]`

Created a test page with 2 events. This works as required (with ASC as ascending and DESC as descending and "past" events).

**But**, when you have more events and they are paginated, the outcome is like this:

* First page, events are displayed in ascending order (ASC)
* Second page: events _before_ first page are displayed, also ASC
* third page: events _before_ second page, also ASC etc. 

Results (I changed number of events per page to 4):

Page 1:

1. 23.02.2021
2. 03.03.2021
3. 11.03.2021 (2x)

Page 2 

1. 14.01.2021
2. 28.01.2021
3. 17.02.2021
4. 18.02.2021

Page 3

1. 23.11.2020
2. 01.12.20202
3. 03.12.2020
4. 10.12.2020

I have not tested if the sorting works correctly with ASC.

## System

* calendarize: "master"
* TYPO3: 10.4.13

## Related

* #508

**Comment by okmiim** [comment]
Hi,
I was not able to reproduce this behavior.

Did you modify the partials or widget template?

---
With my testdata I got the following result (which looks right to me):

Page 1:
1. 20.03.2021
2. 19.03.2021
3. 18.03.2021
4. 17.03.2021

Page 2:
1. 17.03.2021
2. 15.03.2021
3. 12.03.2021
4. 11.03.2021

...

**Comment by sypets** [comment]
@okmiim  You are right. I can reproduce that it works. I am sorry about that. It seems there was something in our template which corrected a problem in cal. I should have tested on a "clean" installation (which I usually do, but not here).

Closing. Not reproducable.
