### ISSUE TITLE
"Past" mode has setting settings.useRelativeDate but no way to set the date

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#512]
![image](https://user-images.githubusercontent.com/13206455/111280336-fcf46680-863b-11eb-824f-6bd624983456.png)

In the "list" mode the setting settings.useRelativeDate is combined with overrideStartdate + overrideEnddate or overrideStartRelative + overrideEndRelative

![image](https://user-images.githubusercontent.com/13206455/111280219-e0582e80-863b-11eb-9fe7-60a804a84811.png)

## System

* calendarize: "master"
* TYPO3: 10.4.13

## Related

* #508

**Comment by okmiim** [comment]
Hi,
as of now, the current implementation only supports overwrite dates in the list (and maybe latest/result) actions, however not in the past action.
The `Use relative Date` options is irritatingly displayed for all views, however only supported in the above mentioned.

**Comment by sypets** [comment]
Yes. So the solution might be to only display `settings.useRelativeDate` in the flexform if used, not for action "past", etc?

**Comment by lochmueller** [comment]
I close this issue. The field is already only visible in the actions with a integration behind it (based on "determineSearch" -> list, latest, result).

Regards,
Tim
