### ISSUE TITLE
Feature Request: Dont' hide past events 

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#52]
Hi,
it would be helpful to have the option to show events for e.g. a whole year even if the event is over. I would use it to show the activities of an organization in a special time period.

Regards & thanks for the great extension
Hobokens

**Comment by lochmueller** [comment]
With the constant `{$plugin.tx_calendarize.settings.listStartTimeOffsetHours}` you can already display "older events". Set `listStartTimeOffsetHours` to -168 and the default list will display the events of the last week also.

The date views display always the whole period. The year view get all events of one year. What is you specific usecase? Display the regular list view with a fixed time slot (from date A till Date B)?

**Comment by Hobokens** [comment]
Hi Tim,

thanks for your reply. I need exactly what you describe in your last sentence:   a regular list view with a fixed time slot (from date A till Date B).

Regards
Tom (alias Hobokens)

**Comment by lochmueller** [comment]
Hey Tom,

OK. I will add the feature in the next week at the T3BOARD :)

Regards,
Tim

**Comment by Hobokens** [comment]
great, have a good time at the T3BOARD!

Tom

**Comment by lochmueller** [comment]
done ;)

**Comment by Hobokens** [comment]
great!
Can you give me a hint how to configure start date and end date?
Regards
Tom

**Comment by lochmueller** [comment]
At the moment it is only part of the Flexform in the ListView. Do you also need this in TS? Please try settings."overrideStartdate" and settings."overrideEnddate"?! If this do not work, please create a new ticket...

**Comment by Hobokens** [comment]
I'm sorry, I missed to check the flexform and tried TS only. 
Now the calendar is perfect for me and I will try - as a last step - to filter the events in list view by categories. 

Thanks for the great support
Tom
