### ISSUE TITLE
Syntax Error in Updater

### ISSUE THREAD

**Issue by Make66** [lochmueller/calendarize#523]
just updated my T3 to 10.4.14 and installed a fresh calendarize-8.2.0 when backend sys "Whoops" and I need to deactivate calendarize again by PackageStates.php. Parse Error is shown (Syntax Error), but the code looks fine for me and phpStorm
/Classes/Updates/CalMigrationUpdate.php line 549
ParseError
syntax error, unexpected ')'
```->where(
                        $q->expr()->eq('uid_foreign', $q->createNamedParameter($eventUidOld, \PDO::PARAM_INT)),
                        $q->expr()->eq('tablenames', $q->createNamedParameter('tx_cal_event')),
                        $q->expr()->eq('fieldname', $q->createNamedParameter('category_id')),
                   )->execute();  // this is line 549
            } else {
                $q->delete($table)
                    ->where(
```

**Comment by sypets** [comment]
@Make66 

There should not be a comma here after the last argument in where, also in the delete directly after:

```
$q->expr()->eq('fieldname', $q->createNamedParameter('category_id')),
                   )->execute();  // this is line 549
```

Can you confirm that that fixes it? (I don't get any errors currently and have been working with that version in several installations)

**Comment by lochmueller** [comment]
Fixed in version 8.2.1

**Comment by Make66** [comment]
same in line 555. The something strange happens: 
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
Expected to find class "HDNET\Calendarize\Command\CleanupCommandController" in file "/home/testsite.com/typo3conf/ext/calendarize/Classes/Command/CleanupCommandController.php" while importing services from resource "../Classes/*", but it was not found! Check the namespace prefix used with the resource.

**Comment by lochmueller** [comment]
Please upgrade to 8.2.1 and clear all your caches (via install tool). @sypets fixed both lines.

**Comment by Make66** [comment]
8.2.1 already on TER! Great... :-)
confirm - issue disappeared.
Thank you
