### ISSUE TITLE
How can I change the days of the week to German?

### ISSUE THREAD

**Issue by vojavojo** [lochmueller/calendarize#524]
Hello Tim,
thanks for the great extension,
How can I change the days of the week to German?
plugin.tx_calendarize.settings.dateFormat = 1, d.m.Y

config.sys_language_uid = 0
config.language = de
config.locale_all = de_DE.utf-8

The days of the week are still displayed in English.
Would be very grateful for a tip!
best regards

**Comment by lochmueller** [comment]
Please use a format that is related to "strftime"
https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3/fluid/latest/Format/Date.html#localized-dates-using-strftime-date-format

Means... format the date with "%" annotation. Then the format view helper will respect your current locales.

I will close this issue.

Question: Is there any default format without "%" format? Then we should switch this to the locale aware format.
