### ISSUE TITLE
Syntax Error in TCA

### ISSUE THREAD

**Issue by Make66** [lochmueller/calendarize#526]
Using PHP-7.2.24 and calendarize-8.2.1 on T3 10.4.14

ParseError
syntax error, unexpected ')'

in /home/testsite.com/typo3conf/ext/calendarize/Configuration/TCA/tx_calendarize_domain_model_index.php line 19

...because of exessive "," in line above...

**Comment by lochmueller** [comment]
FYI @Make66 & @okmiim 

I release 8.2.2 a few seconds ago. Thanks for the fix @okmiim.

FYI: I will drop PHP 7.2 shortly. It is already EOL and I suggest to upgrade to PHP 7.4.

Regards,
Tim
