### ISSUE TITLE
Run automatic checks?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#528]
@okmiim ran check with phpcs but can we:

* add some more checks to automatic checks run by GitHub?
* document running checks locally for contributors, e.g. add CONTRIBUTING.rst or CONTRIBUTING.md, see https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

Related: #527, #526, #523

As for me, I familiarized myself with working in TYPO3 core projects where everything is already configured and built in (phpstan, testing framework), but am a bit lost in other projects which use different tools.

About #525. PhpStorm showed me the problem in my core development project, but not in the project I was developing in when using calendarize.

**Comment by lochmueller** [comment]
Hey @sypets 
Thanks to @okmiim the UnitTests was already in the GitHub Actions. I added the php-cs-fixer in --dry-run mode also to the GitHub actions. If there are files that are not in the right format, the action will failed (error code 8). I will check if I add more tooling in the future. `CONTRIBUTING.md` is also part of the extension. I will close this issue for now.
Regards,
Tim
