### ISSUE TITLE
cal => calendarize migration migrates deleted events

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#534]
Just did another fresh migration and deleted  tx_cal_event records / records on deleted pages also got migrated.

Looking at the source - this shouldn't be - the query is performed using the appropriate Deleted restriction: https://github.com/lochmueller/calendarize/blob/32cbdd984ea97a7889108363fc72e819e23cdf6f/Classes/Updates/CalMigrationUpdate.php#L170 

You can easily remove them after migration, but still, it would be good to look into this.

---

to check for records after migration:

`SELECT neu.uid,neu.import_id,alt.uid,neu.deleted,alt.deleted,neu.title,alt.title FROM tx_calendarize_domain_model_event neu INNER JOIN tx_cal_event alt ON neu.import_id = CONCAT('calMigration:',alt.uid) WHERE alt.deleted AND NOT neu.deleted;`

**Comment by okmiim** [comment]
This might be due `cal` not being installed anymore.

Looking at the [`DeletedRestriction`](https://github.com/TYPO3/TYPO3.CMS/blob/14b865a5cc1f1969de4f95807703c1867c9ab47e/typo3/sysext/core/Classes/Database/Query/Restriction/DeletedRestriction.php#L41-L46), you can see that the TCA configuration is used to determine the deleted column / constraint.
If `cal` is not installed, these are missing
This results is the restrictions being useless on `tx_cal_*` tables.

**Comment by sypets** [comment]
Ah cool,  I didn't think about that. That is probably it.
