### ISSUE TITLE
CAL Migration, SQL error

### ISSUE THREAD

**Issue by HeikoKanzler** [lochmueller/calendarize#539]
Hello. 

I am trying to migrate an older T3 from 8.7x to 9.5.24 (and later 10.x) and away from cal to Calendarize. I am not very proficient when it comes to T3 and currently struggeling with the migration assistant.

What I did:
- Installed Calendarize via composer
- Access the migration assistant via the Upgrade -> Upgrade WIzard

And getting the following SQL error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: 
An exception occurred while executing 
'SELECT * FROM `tx_calendarize_domain_model_pluginconfiguration` WHERE (`uid` = ?) AND ((`tx_calendarize_domain_model_pluginconfiguration`.`deleted` = 0) AND (`tx_calendarize_domain_model_pluginconfiguration`.`hidden` = 0) AND (`tx_calendarize_domain_model_pluginconfiguration`.`starttime` <= 1617014940) AND ((`tx_calendarize_domain_model_pluginconfiguration`.`endtime` = 0) OR (`tx_calendarize_domain_model_pluginconfiguration`.`endtime` > 1617014940)))' with params [0]: Table 'duisburg.tx_calendarize_domain_model_pluginconfiguration' doesn't exist | Doctrine\DBAL\Exception\TableNotFoundException thrown in file /Volumes/Workhorse/Kundenprojekte/../live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 46. `
However, the table `tx_calendarize_domain_model_pluginconfiguration` does exist, but as any other calendarize tables, it's empty.

/heiko

**Comment by okmiim** [comment]
Hi,
Please try uninstall & install the extension again and/or run the [database analyser](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/Upgrade/RunTheDatabaseAnalyzer/Index.html).
Could you also provide information about which Typo3 and calendarize **version** you are using?

_Note_: If you want to use the [MigrationWizard](https://docs.typo3.org/p/lochmueller/calendarize/master/en-us/AdministratorManual/Migration/MigrateFromCal.html) to migrate from `cal` to `calendarize`, I would recommend you to use Typo3 10 with the latest version, since there have been some fixes lately. This works without `cal`  installed (only the db tables have to exist).
And as always: backup your tables beforehand.

**Comment by HeikoKanzler** [comment]
I am using Typo3 9.5.24 and Calendarize 5.0.1, the latest stable for 9.5.x Typo3. 
Migrating T3 to LTS 10 is a later step (the codebase / custom extensions and site packs needs a bit of more work)

I'll check with removing and reinstalling later.

**Comment by HeikoKanzler** [comment]
So, removing and reinstalling the extension got me a step further, the migration assitstant now created the missing tables, however, the migration failes now with a different SQL statement:

An exception occurred while executing `UPDATE 'sys_category' SET WHERE 'uid' = ?' `with params [4]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` = ?' at line 1

**Comment by sypets** [comment]
@HeikoKanzler Can you look in your logfiles if there is an exception stack trace and post the relevant information where the exception occurred (source code + line numbers)?

Again, to reiterate what @okmiim already wrote:

> Note: If you want to use the MigrationWizard to migrate from cal to calendarize, I would recommend you to use Typo3 10 with the latest version, since there have been some fixes lately. This works without cal installed (only the db tables have to exist).

Also, please note if there is a problem _during_ migration, it may not be possible to complete the migration properly. I would always recommend to create a database backup before migrating and if the migration fails but the problems can be fixed, to restore from the database and make a fresh start. 

If the events themselves have already been migrated, the wizard will assume there is nothing left to do, see https://github.com/lochmueller/calendarize/blob/c28fba241982415ca320755804134e1d74336c3e/Classes/Updates/CalMigrationUpdate.php#L1125 What you reported looks like a problem with the sys_category migration which happens after migrating the events tables.

**Comment by HeikoKanzler** [comment]
Thanks for your help, @sypets. 
Migrating to 10 is at the moment not an option due to some dependencies on custom code (I "inherited" the project).

I just checked the sys_category table and it appears that some events have been created (despite the initialy error I reported). The stacktrace in the Wizard and Logfiles:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` = ?' at line 1 | Doctrine\DBAL\Exception\SyntaxErrorException thrown in file /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 83. Requested URL: http://duisburglive/typo3/install.php?install[controller]=upgrade&install[context]=backend - {"TYPO3_MODE":"BE","exception":"Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` = ?' at line 1 in /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:87\nStack trace:\n#0 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php(137): Doctrine\\DBAL\\Driver\\Mysqli\\MysqliStatement->__construct(Object(mysqli), 'UPDATE `sys_cat...')\n#1 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1069): Doctrine\\DBAL\\Driver\\Mysqli\\MysqliConnection->prepare('UPDATE `sys_cat...')\n#2 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(210): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `sys_cat...', Array, Array)\n#3 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php(185): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#4 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php(801): TYPO3\\CMS\\Core\\Database\\Query\\QueryBuilder->execute()\n#5 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php(103): HDNET\\Calendarize\\Updates\\CalMigrationUpdate->performSysCategoryUpdate(Array, Array, '')\n#6 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Updates/AbstractUpdate.php(254): HDNET\\Calendarize\\Updates\\CalMigrationUpdate->performUpdate(Array, '')\n#7 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Service/UpgradeWizardsService.php(397): TYPO3\\CMS\\Install\\Updates\\AbstractUpdate->executeUpdate()\n#8 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Controller/UpgradeController.php(999): TYPO3\\CMS\\Install\\Service\\UpgradeWizardsService->executeWizard('HDNET\\\\Calendari...')\n#9 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Http/RequestHandler.php(221): TYPO3\\CMS\\Install\\Controller\\UpgradeController->upgradeWizardsExecuteAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#10 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Http/Application.php(65): TYPO3\\CMS\\Install\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Install\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/install.php(104): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#13 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/install.php(105): {closure}()\n#14 {main}\n\nNext Doctrine\\DBAL\\Exception\\SyntaxErrorException: An exception occurred while executing 'UPDATE `sys_category` SET  WHERE `uid` = ?' with params [4]:\n\nYou have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `uid` = ?' at line 1 in /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:83\nStack trace:\n#0 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(172): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException))\n#1 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(151): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\Mysqli\\Driver), Object(Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException), 'An exception oc...')\n#2 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1087): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\Mysqli\\Driver), Object(Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException), 'UPDATE `sys_cat...', Array)\n#3 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(210): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `sys_cat...', Array, Array)\n#4 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php(185): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php(801): TYPO3\\CMS\\Core\\Database\\Query\\QueryBuilder->execute()\n#6 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3conf/ext/calendarize/Classes/Updates/CalMigrationUpdate.php(103): HDNET\\Calendarize\\Updates\\CalMigrationUpdate->performSysCategoryUpdate(Array, Array, '')\n#7 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Updates/AbstractUpdate.php(254): HDNET\\Calendarize\\Updates\\CalMigrationUpdate->performUpdate(Array, '')\n#8 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Service/UpgradeWizardsService.php(397): TYPO3\\CMS\\Install\\Updates\\AbstractUpdate->executeUpdate()\n#9 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Controller/UpgradeController.php(999): TYPO3\\CMS\\Install\\Service\\UpgradeWizardsService->executeWizard('HDNET\\\\Calendari...')\n#10 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Http/RequestHandler.php(221): TYPO3\\CMS\\Install\\Controller\\UpgradeController->upgradeWizardsExecuteAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/install/Classes/Http/Application.php(65): TYPO3\\CMS\\Install\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Install\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#13 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/install.php(104): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#14 /Volumes/Workhorse/Kundenprojekte/DuisburgKontor/live9/public/typo3/install.php(105): {closure}()\n#15 {main}"}

``

![CleanShot 2021-04-05 at 16 14 16](https://user-images.githubusercontent.com/5279575/113584245-f3529300-962a-11eb-80b7-ae8054d5919b.png)

**Comment by HeikoKanzler** [comment]
(So it looks like that updating the parent fails, according to the source code, line 801, if I understand the strack trace correctly)

**Comment by okmiim** [comment]
hi,
I seems like you are now (after reinstallation) on calendarize 6.0.0 .
However in this version the start/end dates in the migration are broken (#453).
In your case you should downgrade to 5.0.1 (or better to the current with TYPO3 10).
Due to breaking changes in the db the data cannot be downgraded to the previous version, so you should remove them (e.g. truncate) and run the database analyser/update.

---

Tip: Please use [fenced code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) <code>\```blablabla```</code> for stacktraces.

---

The actual problem lies in these lines
https://github.com/lochmueller/calendarize/blob/a4f34fafff453577adf1ec999bf06925c17ce5ac/Classes/Updates/CalMigrationUpdate.php#L787-L801

The `values(...)` part of the query builder is not supported with update queries.
So you have to replace these lines **by hand** (this is fixed in 8.0.0 and later) with the following lines:

```php
            // update parent, because there are just the old uids
            $q->resetQueryParts()->resetRestrictions();
            $q->update('sys_category')
                ->where(
                    $q->expr()->eq('uid', $q->createNamedParameter((int)$sysCategory['uid'], \PDO::PARAM_INT))
                )->set(
                    'parent',
                    $this->getSysCategoryParentUid(self::IMPORT_PREFIX . (int) $sysCategory['parent'])
                );

            $dbQueries[] = $q->getSQL();

            $q->execute();
```

**Comment by HeikoKanzler** [comment]
Hello @okmiim, also many thanks for your support.

You're right, I used the 6.0, but downgraded now to 5.0.1 and truncated the tables.

After modifying `performSysCategoryUpdate()` I get a different SQL error:

```
SELECT * FROM `sys_category` 
WHERE 
(`import_id` <> ) AND 
((`sys_category`.`deleted` = 0) AND 
(`sys_category`.`hidden` = 0) AND 
(`sys_category`.`starttime` <= 1617715260) AND 
((`sys_category`.`endtime` = 0) OR (`sys_category`.`endtime` > 1617715260)))'

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND ((`sys_category`.`deleted` = 0) AND (`sys_category`.`hidden` = 0) AND (`sy' at line 1
```
From what I can see, the `import_Id` is  not set?

![CleanShot 2021-04-06 at 15 32 15](https://user-images.githubusercontent.com/5279575/113718810-4d1b9180-96ed-11eb-907b-3d04dc3fb983.png)

**Comment by okmiim** [comment]
Hi @HeikoKanzler,

please check out f1d6f82f0258880bd32e2dd3d9d9afcc496e6314 or the master branch and apply appropriate changes yourself.
In this case a change is required inside `getCalendarizeCategoryUid`.

**Comment by lochmueller** [comment]
I will close this issue. If there are still problems in EXT:calendarize >= 10.x or dev-master feel free to create a new issue. Sorry but there will be no bugfix releases for old EXT:calendarize versions.

Regards,
Tim
