### ISSUE TITLE
ICS Error - how to make ICS work?

### ISSUE THREAD

**Issue by ClaudiaK21** [lochmueller/calendarize#545]
Hallo,

we have Typo3 9.5.26 and Calendarize Extension version 6.0.0.
Unfortunately the ICS button does not work, to add the date into Outlook calender f.i.

There is this error:
Sorry, the requested view was not found.
The technical reason is: **No template was found**. View could not be resolved for action "year" in 
class "HDNET\Calendarize\Controller\CalendarController"

Can someone please tell us where this template is located and what must be done to  implement it?

Thanks in advance.

**Comment by lochmueller** [comment]
Hey @ClaudiaK21 
do you have mutiple plugins on the page? Please use a seprate page for list & detail and point the ICS to the detail page. Sounds like you are using the "List + Detail" and "Year" on one page and the format ICS is not supported by the year view.
Regards,
Tim

**Comment by ClaudiaK21** [comment]
Thank you so much for the quick answer and yes, you are absolutely right ;-)
We had the year calender plugin additionally on the detail page, now it is working again.
