### ISSUE TITLE
Filter by categories

### ISSUE THREAD

**Issue by rtgmbh** [lochmueller/calendarize#547]
Currently, when filtering events with multiple categories assigned, this is done with an OR operation. However, I need an AND operation.

Example:
Event 1 - Category 1 and Category 2
Event 2 - Category 1
Event 3 - Category 2

If I select category 1 and category 2 in the frontend plugin I get the following result: Event 1, Event 2 and Event 3

With an AND operation as I need, I would get the following result: Event 1

Is it possible to set the type of operation? For me it would also be ok if I had to change this in the code.

**Comment by okmiim** [comment]
Hi,
you can manually patch [Classes/Slots/EventSearch.php](https://github.com/lochmueller/calendarize/blob/eba3fcef070b4053909d23f8f322a70113a03c06/Classes/Slots/EventSearch.php#L91) with the attached patch
[calendarize-categories-and.patch](https://github.com/lochmueller/calendarize/files/6435764/calendarize-categories-and.txt)
This results in ALL filtering to be AND.
I wont provide further support for this.

**Comment by rtgmbh** [comment]
Thank you very much.
I really appreciate your help.
