### ISSUE TITLE
Add (default) controller and actions to uris

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#553]
Add controller and actions to all uris.
With the routing since 9, the setting skipDefaultArguments is not needed and must be avoided to get proper urls (see [Warning for Extbase Plugin Enhancer](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Routing/AdvancedRoutingConfiguration.html#extbase-plugin-enhancer)).
Through this we can define proper routes for the actions.

- Remove `skipDefaultArguments`
- Add additionalParams in Sitemap, LinkViewHelper, KeSearch, ...
- Improve RouteEnhancers (for each action a seperate uri)

> To prevent the change, add `plugin.tx_calendarize.features.skipDefaultArguments = 1` to the setup

## Important actions for admins

- Action and controller are now required in URLs
    - Rerun the KeSearchIndexer
    - Update the XML-Sitemap configuration in typoscript
- Update or review [routeEnhancers](https://github.com/lochmueller/calendarize/blob/master/Configuration/Yaml/RouteEnhancers.yaml)
- _Cached pages or existing uris may get invalid_

## Important actions for developers

- Add action and controller to any custom link-generation (e.g. custom `LinkViewHelper`)
- `AbstractActionViewHelper` added (extends `AbstractLinkViewHelper` with controller and actions parameters )

**Comment by lochmueller** [comment]
Great idea. Perhaps we could push this in the v11 release?! I will change the Slot logic to PSR-14 events shortly and want to release v10 as "slug and PSR-14" release. Or should we push this also in the next major?

**Comment by okmiim** [comment]
I think we can include this in the next major release, since this also changes the way urls work (e.g. like the slugs) and can be considered as breaking.

The change should not take too long anymore, since this is already implemented ([feature/uri-controller-action](https://github.com/okmiim/calendarize/commits/feature/uri-controller-action)) and only needs some **testing / cleanup / etc**.
So I see no reason, why this should be kept back.
