### ISSUE TITLE
Curious bug

### ISSUE THREAD

**Issue by alat54** [lochmueller/calendarize#56]
Hi, 

After last upgrade (thanks for it :) ) i have this trouble on my page: 
`Configuration Error
Basic configuration settings are missing. It seems, that the Static Extension TypoScript is not loaded to your TypoScript configuration. Please add the calendarize TS to your TS settings.`

But this message appear on a page with 2 calendarize plugin (one calendar view and one list view)
The calendar view works perfectly, the list view don't show the abstract and show this message.

My static template is loaded (if not nothing could appear)

Do you have an idea?
I'm on a 7.6.4 with the last master of calendarize

Thanks a lot.

**Comment by lochmueller** [comment]
Hey @alat54 Do you run same debugging of the internal function calls?

**Comment by alat54** [comment]
Yes :)

**Comment by lochmueller** [comment]
Hey @alat54 
The listView is the only view which check the configuration settings in "checkStaticTemplateIsIncluded". I check the problem twice and cannot rebuild your problem. Do you really load the Static Extension TypoScript from calendarize (not your own TS!)?

Regards,
Tim

**Comment by lochmueller** [comment]
Try again. Please test again your env... if the problem still exists, please comment here (incl. debug information) and we will open the issue again.

**Comment by devxpoint** [comment]
Hi Tim,

I get now this problem with TYPO3 9.5 and calendarize 5.0 after running 1 year without problems.
When I call the URL with the plugin, the parameter "?tx_indexedsearch_pi2%5Baction%5D=noTypoScript" is added
![screencapture-fichtelbergbahn-de-veranstaltungen-2021-03-11-15_38_11](https://user-images.githubusercontent.com/4798067/110804033-16826080-8280-11eb-8b60-95a6e051e4b8.png)
TypoScript is included of course!
Plugin runs in "only list" mode.

**Comment by lochmueller** [comment]
This option is not related to EXT:calendarize.... (sounds like indexed_search) please create new issues for "new problems"... Regards, Tim

**Comment by devxpoint** [comment]
What a shame -.-
Thanks, now it works.
