### ISSUE TITLE
Migrate "cal" plugins to "calendarize" - existing extension "cal2calendarize"

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#576]
We recently migrated our site from cal to calendarize. 

The migration of the events and event / category relations with the upgrade wizard worked very well (especially with the latest fixes). :+1: 

Additionally, there were 2 steps necessary:

* migrate the existing plugins
* migrate the address relations (tx_cal_organizer / tx_cal_location) which can be inserted into tt_address

Calendarize is now used in our site along with calendarize-address.

The migration of the plugins was done because there were quite a few plugins with already existing events , the migration was done along with a major upgrade to TYPO3 v10 and new site should be up and running quickly with all existing information.

However, the migration of the plugins is quite a nightmare as configuration of the plugins is complex and not everything can be mapped easily to calendarize. So, I restricted this to the most basic migration of storagePid, category selection, detailPid, switchableControllerAction and a few other things.

Due to this some manual fixing was still necessary, but the automatic migration helped a lot.

The extension is available: https://github.com/sypets/cal2calendarize (and via packagist). 

Further maintenance depends if there is an interest in using it and maintaining it further.

I most likely have no further use for it.

I did not create a PR here because I thought it might be better to have this as separate extension and also use a CLI command with some parameters and not an upgrade wizard.

**Comment by okmiim** [comment]
Wow, interesting extension 👍

**Comment by sypets** [comment]
I created this issue as placeholder in case someone is interested. No extra work in calendarize required so it can be closed any time. Thanks.

**Comment by lochmueller** [comment]
@sypets thanks for sharing and @okmiim thanks for adding this to the documentation. I will close this issue.
