### ISSUE TITLE
DateTime Modify fails due to leapyear?

### ISSUE THREAD

**Issue by Schweriner** [lochmueller/calendarize#58]
In the Month view you use a ViewHelper to change the month of the date objekt. Today, on march 30th, the functions fails for me. I can't go back to february when using the ViewHelper like this:

`<c:dateTime.modify modification="-1 month">{date}</c:dateTime.modify>`

The result is 1. March. So the link to the last month does not work for me and always returns March...

I'm using PHP 5.6 but I don't think this error is caused by PHP. Using the ViewHelper in the Month.html Tempalte to this solves the problem for me:

`<c:dateTime.modify modification="first day of last month">{date}</c:dateTime.modify>`

Or the complete month switcher:

```
<f:if condition="{settings.monthPid}">
					<f:if condition="{c:ifDateUpper(base: settings.dateLimitBrowserPrev, check:date)}">
						<c:dateTime.modify modification="first day of last month">{date}</c:dateTime.modify>
						<c:link.month pageUid="{settings.monthPid}" date="{date}">
							&lt;
						</c:link.month>
						<c:dateTime.modify modification="first day of next month">{date}</c:dateTime.modify>
					</f:if>
				</f:if>
				<f:format.date format="%B %Y">{date}</f:format.date>
				<f:if condition="{settings.monthPid}">
					<f:if condition="{c:ifDateLower(base: settings.dateLimitBrowserNext, check:date)}">
						<c:dateTime.modify modification="first day of next month">{date}</c:dateTime.modify>
						<c:link.month pageUid="{settings.monthPid}" date="{date}">
							&gt;
						</c:link.month>
						<c:dateTime.modify modification="first day of last month">{date}</c:dateTime.modify>
					</f:if>
				</f:if>
```

**Comment by lochmueller** [comment]
Hey @Schweriner ,

thanks for the report. The problem is, that the {date} is not always the first day in month and if the user use the date for a "dd.mm.yy" output, the result is not the right one after the "first day of next month" -> "first day of last month" modification, because then, it is always the first day. It is important, that after the +- modification the date is the same as the original date.

I will check this behavior in detail in the next days...

Regards,
Tim

**Comment by Schweriner** [comment]
"first day of last month" does not solve the problem as I though. Still can't go back to february in the month view...

**Comment by lochmueller** [comment]
Hey @Schweriner ,

please test the patch in this repo. If the problem still exists, please create a new issue. The problem is part of the DateTime shift.

Regards,
Tim
