### ISSUE TITLE
Typo3 10.4.17

### ISSUE THREAD

**Issue by typomike** [lochmueller/calendarize#586]
Hi
may I ask you if somebody had the same issue? After installing calendarize, I tried to open the extension and get this message:

Oops, an error occurred!
Return value of HDNET\Calendarize\Controller\BackendController::getPageTitles() must be of the type array, null returned
![oops](https://user-images.githubusercontent.com/3757657/124615789-dcb01800-de75-11eb-9298-d126bcb376f1.JPG)

**Comment by lochmueller** [comment]
Hey @timkarliczek 
Please create a storage folder first and create a least one event. We will fix this in the code shortly.
Regards,
Tim

**Comment by typomike** [comment]
many thanks!
the storage folder is created. After setting the date and time I save the entry, I get this message:
![opps2](https://user-images.githubusercontent.com/3757657/124616909-c6568c00-de76-11eb-902e-1325222953cc.JPG)

**Comment by lochmueller** [comment]
Hey @typomike 
both problems are fixed in current master.
Feel free to add a "more speaking issue title" next time. 
Thank you for reporting.
Regards,
Tim
