### ISSUE TITLE
Feature: Option to show only first date of recurring events in list view

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#590]
If an event has several recurrences, these may clutter the list view (see below "Beratung von Studierenden").

Could a checkbox be added to decide that only the closest date of a repeating event shall be shown in the list?

Addition: Actually, it would be even better to be able to define this individually per event! For example, consultation hours take place regularly and every date must be shown. For a workshop lasting several days, however, only the start date should be displayed. - So, it depends.

![grafik](https://user-images.githubusercontent.com/367315/126348752-21d211ed-9ba0-45b9-8411-13b2df37a2f0.png)

**Comment by lochmueller** [comment]
Hey @artus70 
do you try this ViewHelper based on the Event of the index: https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/GroupedFor.html Then you can control the output in one list, if there are mutliple. Furthermore do you already try to add the needed checkbox to your event and use one of the Events to modifiy the SQL selection?
Regards,
Tim

**Comment by lochmueller** [comment]
There are no news about this topic and perhaps the GroupedFor helper could solve this problem (or a other kind of ViewHelper that group the items). I will close this issue, because it is very old...
