### ISSUE TITLE
Problem with language labels in calendarize dashboard widgets

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#591]
updated to calendarize 10.2.0, flushed caches, downloaded language packs, but still have widget with empty text (when trying to add dashboard widget):

en:

![image](https://user-images.githubusercontent.com/13206455/126772057-4fb4c9c4-e756-4c8e-98f0-a9863eda68e0.png)

de (German):

![image](https://user-images.githubusercontent.com/13206455/126771999-59f01cba-40bd-4331-b80d-2894ad5c75d5.png)

After inserting (the second widget with empty texts), I get texts 'LLL:EXT:calendarize...

![image](https://user-images.githubusercontent.com/13206455/126772230-abd73846-6027-4762-b43d-61d4fb47e428.png)

The other widget "Next events" looks fine.

**Comment by lochmueller** [comment]
Hey @sypets 
do you try "clear all caches" via Install tool already?
I will check this CrowdIn integration.
Regards,
Tim

**Comment by sypets** [comment]
@lochmueller Yes, that's what I did first. Flushed cache in install tool (or via composer commands), downloaded language packs, also flushed browser cache (just in case).

About crowdin: The problem exists in English as well.

If you can't reproduce it, there may be something else causing this on my end.

Reproduced with:

- non-Composer installation 10.4.18 + calendarize 10.2.0
- coredev installation from core 10.4 branch + calendarize 10.2.0
- Composer installation 10.4.18  + calendarize 10.2.0
