### ISSUE TITLE
Runtime exception after updating calendarize to 10.2.0 on installation without dashboard

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#592]
The extension does not have a requirement for `typo3/cms-dashboard`, so I guess it should work on installations without dashboard.

After installing via Composer and running usual setup-routines, there is a runtime Exception:

```
vendor/bin/typo3cms extension:setupactive

                                                                                                                             
  [ Symfony\Component\DependencyInjection\Exception\RuntimeException ]                                                       
  Invalid service "dashboard.widgets.calendarizeNextEvents": class "TYPO3\CMS\Dashboard\Widgets\ListWidget" does not exist.  
```

----
            
* TYPO3 10.4.18
* calendarize 10.2.0

**Comment by lochmueller** [comment]
Hey @sypets 
I added the EXT:dashboard as requirement. I open a new task for checking the integration without the EXT:dashboard.
Regards,
Tim
