### ISSUE TITLE
Exception when updating to 11.0.0 (due to not performed DB changes)

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#597]
When updating to calendarize 11.0.0 (from 10.2.0 or 10.1.0) via Extension Manager on a non-Composer installation, I get kicked out of the backend (see login view), the installation procedure does not finish and there are DB changes left unexecuted. The results are various exceptions (due to missing DB change).

**The situation can be remedied by executing the DB changes** (Analyze Database) (and flushing cache and autoload). However, this should normally not be necessary.

This may also be a core problem or something on my end, I am not sure what the underlying problem is. Unfortunately, I get no exception or indicator why this happened **during** the update procedure. There is no log entry during the update. (Only afterwards due to the unperformed DB changes).

Could reproduce this on 2 systems. 

---

## Versions

* TYPO3 10.4.19
* non Composer
* autoloader: 7.1.4 / 7.2.0
* calendarize: version before updating: 10.1.0 / 10.2.0
* calendarize: version to update to 11.0.0

## Steps

* Update calendarize to 11.0.0 in extension manager

## Errors

1. During update, I get kicked out of the backend
2. After logging in again, error in dashboard calendarize widgets
3. Immediately after calling reindex in scheduler:

`Die Ausführung von Task "Konsolenbefehle ausführen (scheduler)" ist fehlgeschlagen mit folgender Meldung: An exception occurred while executing 'SELECT * FROM `tx_calendarize_domain_model_index` WHERE (`t3ver_wsid` = ?) AND (`foreign_table` = ?) AND (`foreign_uid` = ?) AND (`tx_calendarize_domain_model_index`.`deleted` = 0)' with params [0, "tx_calendarize_domain_model_configurationgroup", 1]: Unknown column 't3ver_wsid' in 'where clause'`

After doing the DB compare, everything looks ok. Reindex can be performed.

**Comment by lochmueller** [comment]
Hey @sypets 

If the DB compare fix all this, it is ok. It is a major release with DB changes (breaking changes). The DB compare is part of the update process and cannot trigger by the extension itself. The reason of the "Logout" could be the removal of some classes.

But if the system works well after "DB compare + Clear cache + remindex all", I would close this issue.

Regards,
Tim

**Comment by sypets** [comment]
Yes, as described, the DB compare fixes the issue.
