### ISSUE TITLE
PHP Warning: file_exists(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by kesandal** [lochmueller/calendarize#604]
Hello,

I'm trying to use calendarize unfortunately the extension isn't working for me.

**Environment**
PHP: 7.4.22
Typo3: 10.4.20
calendarize: `8.2.2`
composer based installation
open_basedir: `{WEBSPACEROOT}{/}{:}{TMP}{/}{:}{/}var{/}lib{/}php{/}sessions`
Public dir: `httpdocs/_beta/public/`
Typo3 directory: `httpdocs/_beta/[FILES]`

**How to reproduce**
1. Install the extension with composer
2. login into the backend and execute the database check + let typo add the missing tables for calendarize
3. create a folder for the calendar events
4. create a new event:
a) enter a title
b) click on "Date options"
c) click on "Create new"
d) --> Error undefined

![image](https://user-images.githubusercontent.com/9745973/130774222-e310d702-ca5e-416a-ae43-568b99fd2fce.png)

**More details about the error**
Clicking on `create new` results in an ajax request: `https://example.com/typo3/index.php?route=%2Fajax%2Frecord%2Finline%2Fcreate&token=bd34f764852727a652e7b3543b72a2c2bb53fb7c`
Result: **Error 500** "Whoops, looks like something went wrong."

**Misc**
I've found a similar error in another extension, maybe this will help here:
https://github.com/WebentwicklerAt/typo3-emogrifier/issues/9

Please let me know if you need further information.

Best regards

**Comment by kesandal** [comment]
Update: I've been able to resolve the problem.

composer installed an old version of `calendarize` (`8.2.2`) because my `composer.json` have had php `7.2`. in the plattform configuration. After updating that value to `7.4` and running `composer update` I've been able to install `calendarize` version `11`.

Everything is working fine now. 👍

**Comment by lochmueller** [comment]
Hey @kesandal 

Great that the new version fix this problem. I will close this issue. 

If you get this error again (in calendarize or another extension) you could active the developer tool in your browser and check "the real" error in the AJAX request. There was a failed AJAX request and TYPO3 just render this red box (without information), but the complete problem you will (mostly) see in the response of the AJAX request.
Thanks for reporting...

Best regards,
Tim
