### ISSUE TITLE
Workspaces: list-view doesn't load

### ISSUE THREAD

**Issue by twestner** [lochmueller/calendarize#611]
I have a simple list view. If i call it in live-workspace, it loads as espected with some events.

If i switch to draft workspace in BE and then call my list view in FE again, it loads and loads and loads... and results in "mysql server gone away" or some other timeouts.

I could not detect any hint, WHERE the error occurs yet.

**Comment by lochmueller** [comment]
Hey @twestner do you work with the current master or the last release? Regards, Tim

**Comment by twestner** [comment]
oh, sorry. I'm working with the current master.
If you can confirm, that the ws-overlayed list view is working for you, then I will dig deeper into my project first.

**Comment by lochmueller** [comment]
![Bildschirmfoto 2021-09-13 um 22 43 23](https://user-images.githubusercontent.com/3907126/133153643-b3946d0b-a9d8-4e6b-a3fe-d06c216db49e.png)

Hey @twestner  The list view is working for me. Changed a Event (added the "2") and preview the workspace in frontend. No problems on my side. Could you check where the problem occur?!

**Comment by twestner** [comment]
ok, I will dig deeper into my installation. Thank you for the confirmation, that it works for you.

**Comment by twestner** [comment]
The function EventUtility::getOriginalRecordByConfiguration(..) is the place, where the immense time is spent. When my list has some more entries (>= 10), it runs in a timeout.

My event-type has a regular categories-field, when I change this to lazy loading, i can increase runtime of the function extremely (1/15 of the time before!).

This only happens in draft workspace. It seems, that overlaying the categories does take so much time.
