### ISSUE TITLE
Workspaces: Event is not indexed on first save-click

### ISSUE THREAD

**Issue by twestner** [lochmueller/calendarize#612]
I'm working with 10.4.20 and the current master branch of calendarize.

I have an event in live-workspace. It does not matter, if there is an valid index or not (e.g. date is over).
I switch into draft-workspace and edit this event. After saving the event it is not indexed.
When I save AGAIN, the index is created/updated.

I guess, indexing only works when a workspace-version of the event/configuration is already there and not if is just in creation.

**Comment by lochmueller** [comment]
I checked it in my installation and it works. Could you check, with Hooks are triggerd on your site:
"ProcessDatamapClass" and "ProcessCmdmapClass" control the Index process. "ProcessDatamapClass" collect configuration and trigger the reindex on "processDatamap_afterAllOperations" and the Cmdmap is checkd via "processCmdmap_postProcess". Perhaps there are other hooks that stop the hook execution or unregister hooks?!

**Comment by twestner** [comment]
The bug got lost while searching for it... or while fixing another issue. Whatever it was, it works now. Thank you.
