### ISSUE TITLE
Workspaces: Configuration is not overlayed by workspace data while indexing

### ISSUE THREAD

**Issue by twestner** [lochmueller/calendarize#613]
I have an event in live-workspace, which is indexed.
Then I switch into the draft-workspace and change the date. The draft-workspace-event will also be indexed with the new date when saving the event.

But when the draft-workspace-event is indexed, the date of the live-event is adapted to - which is a bug. The live index should not be touched at all.

-- 

calendarize im master-branch, T3 10.4.20

**Comment by lochmueller** [comment]
Hey @twestner 
this is right. In the indexing of Workspace records I trigger the Live Indexing: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/IndexerService.php#L154
This is just "more safe" to get a valid and consistently index result. So it is ok, that the Index of the live record is triggerd. But I will check the date problem...
Regards,
Tim
