### ISSUE TITLE
Show only the next date per Event

### ISSUE THREAD

**Issue by mithri** [lochmueller/calendarize#62]
Hi,

a customer has a feature request. He wants to only display the next upcoming date from one "Event". Maybe you can add a input field in the flexform to limit how much dates per event will shown in the view.

Thanks for this great extension.
Tobias

**Comment by lochmueller** [comment]
Nice idea... i will check this feature in the next days...

**Comment by lochmueller** [comment]
There is no smart solution, because the Query Builder in extbase do not allow GROUP BY :( Any suggestions?

**Comment by mithri** [comment]
Hmm, right. No idea at the moment. Maybe an extended viewhelper to hide the second and third events..

**Comment by lochmueller** [comment]
Hey @mithri ,
I checked the ExtBase "Group By" selection of models and there is no smart solution for this. I will integrate the feature, if ExtBase provide a better API for DISTINCT/GROUP BY queries. Sorry...
Regards,
Tim
