### ISSUE TITLE
Import UID

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#620]
Hello Tim,

if I import an ICS-File with an event UID like this:

Termin1
UID:Schulkalender-001

Termin2
UID:Schulkalender-002

Termin3
UID:Schulkalender-003

Then I get 3 Events in Typo3: Termin1, Termin2, Termin3 ---> everything is ok
______
When I change the ICS-File because some events changed or have been cancelled like this:

Termin5
UID:Schulkalender-001

Termin6
UID:Schulkalender-002

Then the two changed events will be displayed in Typo3 correctly. But the cancelled event Termin3 is still displayed because the UID:Schulkalender-003 will not be overwritten or deleted.

Is there a chance to compare the number of events in ICS-File with the Typo3 database. For example with the first part of the UID "Schulkalender". Or all Events with the UID Schulkalender will be deleted in the Database first and then the new events will be imported.

Thanks, Sascha

**Comment by lochmueller** [comment]
Very old ticket and no progress... I will close this issue. Sorry.
