### ISSUE TITLE
Feature: Add checkbox to hide past events in BE Calendarize view

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#623]
The more past appointments there are, the more confusing the appointment list in the Calendarize view becomes. If I want to sort the appointments chronologically in ascending order, past appointments often just get in the way. It would help to have a switch to hide all past appointments.

**Comment by okmiim** [comment]
Hi @artus70,

with 98732ac381f582cbd94d60a3a75e2bf4d04430b2 you now have an option, to filter the indices by start- and enddate.
This is more versatile than a simple switch and should serve a similar purpose.

**Comment by artus70** [comment]
Great, thx!
