### ISSUE TITLE
Calendarize BE form doesn't respect my RTE yaml configuration

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#624]
For text&media elements I have a yaml configuration for the RTE (CKEditor 4) which adds some style menu entries, further CKEditor plugins, own css etc. When editing events in calendarize, the RTE field does not respect those settings but shows only the standard RTE configuration - how to fix this?

**Comment by lochmueller** [comment]
This is not EXT:calendarize related. You can define new configurations and have to set the PageTsConfig for the TABLE.FIELD to the new preset. I close this issue...

https://docs.typo3.org/c/typo3/cms-rte-ckeditor/master/en-us/Configuration/Examples.html

Regards,
Tim

**Comment by lochmueller** [comment]
Perhaps, because EXT:autoloader set the preset explicit to default: https://github.com/lochmueller/autoloader/blob/c0b6a3eba626460eca4e7b55aa1e9b5dffed2069/Classes/Service/SmartObjectInformationService.php#L100 

But if the one additional line worked, great.

**Comment by artus70** [comment]
It seems that text&media is the only use case where my own `RTE.default.preset` setting is respected. Other extensions like news and tt_address also require the `RTE.config.tablename.fieldname.preset` setting. I didn't know this before (and didn't even know where to search for it), so thanks again for the hint!
