### ISSUE TITLE
calendarize is not PHP-7 compatible

### ISSUE THREAD

**Issue by rabe69** [lochmueller/calendarize#63]
After switch my environment to php 7, I get this error in calendar list view:
`PHP Warning: Declaration of HDNET\Calendarize\ViewHelpers\Link\IndexViewHelper::render(HDNET\Calendarize\Domain\Model\Index $index, $pageUid = NULL) should be compatible with TYPO3\CMS\Fluid\ViewHelpers\Link\PageViewHelper::render($pageUid = NULL, array $additionalParams = Array, $pageType = 0, $noCache = false, $noCacheHash = false, $section = '', $linkAccessRestrictedPages = false, $absolute = false, $addQueryString = false, array $argumentsToBeExcludedFromQueryString = Array, $addQueryStringMethod = NULL) in /var/www/vhosts/website.de/httpdocs/preview/web/typo3conf/ext/calendarize/Classes/ViewHelpers/Link/IndexViewHelper.php line 17
`

**Comment by lochmueller** [comment]
Hi @rabe69 
thanks for the bug report. I will check the calendarize extension for PHP7 in the next days/weeks. This is a first good hint. You can reduce the error reporting configuration in this case, because it is only a warning.
Regards,
Tim
