### ISSUE TITLE
Configuration groups broken after changes for workspaces

### ISSUE THREAD

**Issue by phvt** [lochmueller/calendarize#632]
Unfortunately, it appears that the fix for #613 broke editing of events when a configuration group is used. The event record saves, but the record changes don't get indexed.

This is the error:
> Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function HDNET\Calendarize\Service\TimeTableService::getTimeTablesByConfigurationIds(), 1 passed in /.../ext/calendarize/Classes/Service/TimeTable/AbstractTimeTable.php on line 57 and exactly 2 expected | ArgumentCountError thrown in file /.../ext/calendarize/Classes/Service/TimeTableService.php in line 35

If I remove the configuration group, the record saves and indexes correctly, with no errors.

More work is needed to make everything handle workspaces correctly.

**Comment by lochmueller** [comment]
Hey @phvt 
Thanks for reporting. I fixed the function calls in the current integration and will add some more Unit tests for the Workspace functions in the next days.
Regards,
Tim

**Comment by phvt** [comment]
Thanks Tim! 4b9f091 fixed the issue on our end.
