### ISSUE TITLE
v11 support?

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#633]
Are you working on it, are PR in this area welcome?

**Comment by agendartobias** [comment]
Any info for 11.5 release? Can we test something?

**Comment by lochmueller** [comment]
No there are no news. I prepare some things und current master, but the extension is not ready for v11 yet. I will check this in the next weeks...

**Comment by lochmueller** [comment]
Hey @agendartobias & @sypets 
Current master works with TYPO3 v11 in my dummy installation on https://jetzt.fruit-lab.de/
Feel free to test it and send us some feedback.
Regards,
Tim
