### ISSUE TITLE
Feature: Offer raw URLs from link viewhelpers

### ISSUE THREAD

**Issue by yol** [lochmueller/calendarize#642]
Currently, the link.* viewhelpers always return an HTML <a> element (as far as I can tell). For some use cases, it is better to just have the raw URL and create the <a> (or whatever) tag in fluid. It also makes it easier to pass the link URL to preexisting partials that expect to just get the URL. So it would be nice to either have extra viewhelpers (like fluid: f:link.page vs. f:uri.page) or offer an argument to just render the URL.

**Comment by lochmueller** [comment]
Hey @yol ,
I will close this issue. 

Next to the "link.*"-ViewHelpers are already "uri.*"-ViewHelpers.

Link: https://github.com/lochmueller/calendarize/tree/master/Classes/ViewHelpers/Link
Uri: https://github.com/lochmueller/calendarize/tree/master/Classes/ViewHelpers/Uri

If there are missing ViewHelpers, please create separated issues.

Best regards,
Tim

**Comment by yol** [comment]
Of course I only looked for arguments on the link.* viewhelpers and didn't even notice the uri.* viewhelpers :see_no_evil: Sorry for the noise and thanks.
