### ISSUE TITLE
Feature: Optional RTE for teaser

### ISSUE THREAD

**Issue by yol** [lochmueller/calendarize#643]
Sometimes, it is useful to have a rich-text editor also in the teaser, e.g., to bolden some words. The news extension, for example, has this as extension option: https://github.com/georgringer/news/blob/923b96496cb054a6b3c678b48c19755fbb9b2276/ext_conf_template.txt#L10 -> if set, this enables rich-text editor for the teaser

**Comment by lochmueller** [comment]
Hey @yol 

Thanks for reporting. In general, EXT:calendarize is a very flexible calendar framework that allow you, to register any custom data structure for the calendar output (example: EXT:calendarize_pages). If the example event in EXT:calendarize do not fit your needs, it is recommended to create an own/custom data structure exactly for your use case.

I will close this issue.

Regards,
Tim

PS: Perhaps you could also enable the RTE with PageTsConfig.
