### ISSUE TITLE
Check TimeZone for e.g. import processes

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#645]
<img width="621" alt="image001" src="https://user-images.githubusercontent.com/3907126/148454331-d77c5fa7-679e-41b1-bced-3c55d20402c6.png">

**Comment by okmiim** [comment]
Hi @lochmueller 
`W. Europe Standard Time` is the time zone format by Microsoft typically used in Windows.
Outside the MS world, IANA time zones are normally used.

- Is this the server timezone (e.g. `TZ` env variable) or inside the `.ics` file (e.g. `TZID="W. Europe Standard Time"`)?
- Is the installation with or without composer?

**Comment by lochmueller** [comment]
Hey @okmiim 
You are right, the problem is part of a ICS import from MS. We do not need to handle old/strange time zones... But I think we should catch the exception and set a default time zone in case of an error.
Regards,
Tim
