### ISSUE TITLE
Booking feature - mail configuration

### ISSUE THREAD

**Issue by vogelgeyer** [lochmueller/calendarize#647]
Hello Mr. Lochmueller,

I'm just a dumb user of typo3, no developer. And so i hope I'm not completely wrong here.
I already used calendarize in some of my homepage projects. Now I would like to integrate the booking function which would be a great and useful feature.
Up to now I can chose an event and the booking form is shown. After filling in the necesserry fields and pushing the "Send" button the success message appears. The problem is that I do not receive an email and i cannot find an entry in the db where the inserted data is stored.
I coul not find any documentation about the booking feature. 
Can I use the booking feature out of the box or is there any further coding necessary?

I would appreciate an answer,
Greetings
JG

**Comment by okmiim** [comment]
Hi @vogelgeyer,
currently, calendarize only provides the interfaces and does not process the data.
It is meant to be extended by custom logic.

As an alternative, maybe take a look at [powermail](https://github.com/einpraegsam/powermail).

---

If anyone wants to implement this, these are roughly the steps:
- [PSR-14 Event listener](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Hooks/EventDispatcher/Index.html#implementing-an-event-listener-in-your-extension) for [GenericActionAssignmentEvent](https://github.com/lochmueller/calendarize/blob/4e7a52e89a9ec3933936377776f247bae716010c/Classes/Event/GenericActionAssignmentEvent.php) (className=[BookingController](https://github.com/lochmueller/calendarize/blob/4e7a52e89a9ec3933936377776f247bae716010c/Classes/Controller/BookingController.php))
  - to receive the submitted data
- Complete **booking logic**
  - Database
  - Email notification
  - Configuration
  - ...
- for *custom data fields*
  - custom BookingRequest (like [DefaultBookingRequest](https://github.com/lochmueller/calendarize/blob/4e7a52e89a9ec3933936377776f247bae716010c/Classes/Domain/Model/Request/DefaultBookingRequest.php))
  - custom HTML template ([Resources/Private/Templates/Booking/Booking.html](https://github.com/lochmueller/calendarize/blob/4e7a52e89a9ec3933936377776f247bae716010c/Resources/Private/Templates/Booking/Booking.html))
- for *custom events*
  - add the feature [BookingInterface](https://github.com/lochmueller/calendarize/blob/4e7a52e89a9ec3933936377776f247bae716010c/Classes/Features/BookingInterface.php)

**Comment by lochmueller** [comment]
Thanks @okmiim for the details. I will add this to some documentation in the next days... Regards, Tim

**Comment by lochmueller** [comment]
Thanks @okmiim 
I will close this issue.
