### ISSUE TITLE
Uncaught exception in CalendarController: Call to a member function getUid() on null 

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#655]
I am seeing a number of these in the log messages (this is not new, been having this for a while)

This results in an "Oops an exception occurred" on some detail event URLs. I have not tracked down yet why it happens, but perhaps a check for null would help. 

```
Wed, 02 Feb 2022 04:17:06 +0100 [CRITICAL] request="696fd1cd85f79" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): 
Uncaught TYPO3 Exception: 
Call to a member function getUid() on null 
| Error thrown in file 
/var/www/mysite/releases/53/htdocs/typo3conf/ext/calendarize/Classes/Controller/CalendarController.php
in line 509. 
Requested URL: https://mysite.de/en/physics/events/event/sitzungspause-sommerferien-5 
```

line 509 in CalendarController

```
$this->addCacheTags(
  ['calendarize_detail', 
  'calendarize_index_' . $index->getUid(), 
  'calendarize_' . lcfirst($index->getConfiguration()['uniqueRegisterKey']) . '_' . $index->getOriginalObject()->getUid()]
);
```
https://github.com/lochmueller/calendarize/blob/6902b0b6a10dd25df3ef8beb50cec420a5e3653c/Classes/Controller/CalendarController.php#L509

---

version

* calendarize 11.0.2
* master

**Comment by lochmueller** [comment]
Hey @sypets 
could you checked, why the line before not handle this problem? If the index is null it should not pass this block, because there is a redirect call in it:
https://github.com/lochmueller/calendarize/blob/master/Classes/Controller/CalendarController.php#L501
Regards,
Tim

**Comment by sypets** [comment]
@lochmueller Thanks for the fast reply.

It is not the `$index` that is null. It is `$index->getOriginalObject()`.

I reproduced again with latest master

I debugged: 

-----

In `Index->getOriginalObject()` the function `EventUtility::getOriginalRecordByConfiguration` returns null.

Line 134 in Index.php

----

In `EventUtility->getOriginalRecordByConfiguration`:

-  `$configuration['title'] = Event`
- `$configuration['modelName'] = AndreasKastl\CalendarizeAddress\Domain\Model\Event`
- `$configuration['partialIdentifier'] = 'Event'`

The subsequent query with ->execute()->getFirst() then returns null.

Perhaps there is a problem with this third party extension calendarize_address which we are using. I will try to look into it.

**Comment by sypets** [comment]
One other thing I noticed: the URLs in the logs are all from English pages. We have German as default language. So it seems to be related to translations.

If I look at an event overview and click on the events, I never see this error. Also if I change the URL into a bogus event name which does not exist, I get error page. 

So it seems to be generally ok, but for some URLs this problem exists. 

I will try to dig further and try to find out how to reproduce this.

**Comment by sypets** [comment]
I researched further. I can reproduce the problem

* with Introduction package with no  route enhancers
*  on my site with route enhancers 

The route enhancers are irrelevant. The problem is that in the language menu an URL to a translated event detail page gets created even if the even has no translation (see my steps to reproduce below). On my site this may be due to our custom made language menu, but the problem also happens with Introduction Package.

I also tried a reindex but this is also irrelevant.

All tests with latest TYPO3 v10 and latest calendarize.

-------

I can reproduce the problem like this:

1. (Create an event1 with default language and translation) - not necessary, but just to double check all else works
2. Create an event2 without translation
3. On the detail page for event2 click on the language menu to load even in another language (or manually construct the URL to use the URL for translated page with the slug from the default language event).

Now the exception gets thrown.

URLs like this should not get created at all, but they might exist if a a translation was created with the same slug and then removed. Or as described with the language menu not functioning correctly.

So this looks 2 problems:

1. Why is the URL created in the language menu (if the translated event does not exist)
2.  Exception should not get thrown, ideally 404 page (as for other not existing events)

----

DE is default language on our site, EN is translation

event1 (same slug for DE and EN)
* DE:` /calendarize/calendarize-detail/termin/testtermin-mit-uebersetzung`
* EN: `/en//calendarize/calendarize-detail/event/testtermin-mit-uebersetzung`

event2: (only event for DE)
DE: `/calendarize/calendarize-detail/termin/calendarize-testtermin-1`
EN: incorrect URL with slug of default: **Exception** `/en/calendarize/calendarize-detail/event/calendarize-testtermin-1`

----

The exception occurs when on a translated page an event detail is loaded with the slug of the default language and not translation.

CalendarController
=> Index::getOriginalObject
  =>  EventUtility::getOriginalRecordByConfiguration

```
SELECT * FROM `tx_calendarize_domain_model_event` 
  WHERE (`pid` = 39087) AND (`sys_language_uid` = 1)
    AND (`l10n_parent` = 5747) 
    AND ((`tx_calendarize_domain_model_event`.`deleted` = 0) 
    AND ((`tx_calendarize_domain_model_event`.`t3ver_state` <= 0) 
    AND (`tx_calendarize_domain_model_event`.`t3ver_oid` = 0)) 
    AND (`tx_calendarize_domain_model_event`.`hidden` = 0) 
    AND (`tx_calendarize_domain_model_event`.`starttime` <= 1643884200) 
    AND ((`tx_calendarize_domain_model_event`.`endtime` = 0) 
     OR (`tx_calendarize_domain_model_event`.`endtime` > 1643884200)) 
    AND ((`tx_calendarize_domain_model_event`.`fe_group` IS NULL) 
      OR (`tx_calendarize_domain_model_event`.`fe_group` = '') 
      OR (`tx_calendarize_domain_model_event`.`fe_group` = '0') 
      OR (FIND_IN_SET('0', `tx_calendarize_domain_model_event`.`fe_group`)) 
      OR (FIND_IN_SET('-1', `tx_calendarize_domain_model_event`.`fe_group`)))) 
 LIMIT 1
```

The event 5747 is the event in default language. No translation exists.
