### ISSUE TITLE
Language menu generates link to translation even if no translation exists for event (Introduction Package)

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#660]
Is related to #655, but is separate issue.

Reproducible with Introduction Package, tested with TYPO3 v10 latest and latest calendarize (master).

Reproduce

1. Set up calendarize, set up a detail page, create a translation for it (e.g. German)
2. Add an event, do not add translation
3. In the FE: In the list view, click on the event. Detail view get shown
4. In language menu (is on bottom in Introduction Package), click on link for translation (e.g. German). 

If an event has no translation, the link to the translation should not get rendered in the language menu.

In introduction package, language setting "**strict**" is used. Default is EN, translation setup for DE and DK exists.

I have not looked into how Introduction Package creates the language menu but I assume this might be a general problem which does not only occur in Introduction Package.

I have also tested with news, where the link is displayed as well and then an empty page is displayed. This does not look good either. This might also be a core problem. Should probably be investigated further.

**Comment by okmiim** [comment]
Hi @sypets,
I think there is at least a solution for news:
- [Language menu on news detail pages](https://docs.typo3.org/p/georgringer/news/9.2/en-us/Tutorials/BestPractice/Seo/Index.html#language-menu-on-news-detail-pages)
- [LanguageMenuProcessor](https://docs.typo3.org/p/georgringer/news/9.2/en-us/Tutorials/ExtendNews/DataProcessing/LanguageMenuProcessor.html)

For the introduction package you would have to add this to the typoscript setup (I think):
```typoscript
page.10.dataProcessing.41 = GeorgRinger\News\DataProcessing\DisableLanguageMenuProcessor
page.10.dataProcessing.41.menus = languagenavigation
```

**Comment by sypets** [comment]
@okmiim Thanks, I will look into it. I just use the Introduction Package as reference system to reproduce problems which need FE rendering. But this might also be helpful for our site (with custom template and custom language menu).

**Comment by okmiim** [comment]
Hi @sypets,
similar to news, I also added this functionality to calendarize (5cc779d345c15a7a2465a82e7e2eb80c9122716f).

```php
page.10.dataProcessing.42 = HDNET\Calendarize\DataProcessing\DisableLanguageMenuProcessor
page.10.dataProcessing.42.menus = languageNavigation
```

**Comment by sypets** [comment]
@okmiim cool, thank you. I will check it out.
