### ISSUE TITLE
Search result pagination is not working

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#665]
The current implementation for pagination does not work on search results.

The search form uses a POST request. The pagination links are GET links and don't submit the filters when the page changes.

## Possible solutions

- Change POST to `method="get"`
- hidden form field with some JS magic
  - Example: pageBrowser Viewhelper in indexed_search ([Search.html](https://github.com/TYPO3/typo3/blob/d164d3e7cd0fd16c3d71f352b091b476ebd771e2/typo3/sysext/indexed_search/Resources/Private/Templates/Search/Search.html#L52), [PageBrowsingViewHelper](https://github.com/TYPO3/typo3/blob/d164d3e7cd0fd16c3d71f352b091b476ebd771e2/typo3/sysext/indexed_search/Classes/ViewHelpers/PageBrowsingViewHelper.php))
- A text input with a number selector
  - See [okmiim/calendarize form-pagination](https://github.com/okmiim/calendarize/tree/form-pagination) (a8ec90cef258f7e5fa1313317d8d4cb29ac5d278) 
- ...

**Comment by lochmueller** [comment]
Hey @okmiim 

I integrated the JS logic from indexed search and use the form field as base (hidden via Boostrap d-none class).

Notice: I set the page "1" as default value for the form. As result the Pagination could use to navigate the results: https://jetzt.fruit-lab.de/ (Search for a 2 years range from now and look for 'Dart') BUT, when you use the form itself (e.g. change search parameters) you will see the first page again. If I use the "currentPage" as default for the form input, you would see the "currentPage" of your last search and I think it is more useful to see the first page, after setting some new search input by the user.

Please check the solution and send me some feedback... Would be cool.

Regards,
Tim

**Comment by lochmueller** [comment]
Notice: Small follow-up cleanup, so the JS is only used, if the search is executed (not in the initial displayed view)

**Comment by lochmueller** [comment]
Hey @okmiim 
I will close this issue. If there are follow-ups/cleanups feel free to add this in the code.
Thanks for your detailed preparation.
Best regards,
Tim
