### ISSUE TITLE
TYPO3 11.5.7 PHP Fatal Error

### ISSUE THREAD

**Issue by Hydroxi** [lochmueller/calendarize#670]
After an T3 update from 11.5.6 to 1.5.7 the extension throws the following error, resulting in a 500 for the whole website:

` PHP Fatal error:  Uncaught Error: Call to a member function resolvePackagePath() on null in /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php:135
Stack trace:
#0 /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Utility/GeneralUtility.php(2745): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::resolvePackagePath()
#1 /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Controller/ErrorPageController.php(47): TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName()
#2 /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3199): TYPO3\CMS\Core\Controller\ErrorPageController->__construct()
#3 /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Error/ProductionExceptionHandler.php(65): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance()
#4 /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Error/AbstractExceptionHandler.php(65): TYPO3\CMS\Core\Error\ProductionExceptionHandler->echoExceptionWeb()
#5 [internal function]: TY in /var/www/typo3/typo3_src-11.5.7/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php on line 135`

I could only find some similiars error in other extensions, this seemed the most related:
https://github.com/FriendsOfTYPO3/extension_builder/issues/124#issuecomment-525197625

**Comment by okmiim** [comment]
Hi @Hydroxi,
I currently cannot trace this error to the calendarize extension since it is not part of the stack trace. My test installation works fine.
You could try the typical debug steps: clear the cache in the install tool, uninstall extensions, ...

**Comment by Hydroxi** [comment]
Hm then it must be an interference with another extension.
A colleague had activated the calendarize extension, but we do not currently have it in use.
After deactivating the extension the page ran again. Therefore this was my first guess.
Thanks for the quick feedback!
