### ISSUE TITLE
Exception after deactivating/activating extension

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/calendarize#672]
```
(1/1) Symfony\Component\DependencyInjection\Exception\RuntimeException
Invalid constructor argument 2 for service "dashboard.widgets.calendarizeNextEvents": argument 1 must be defined before. Check your service definition.

in /Users/***/typo3_src-10.4.24/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php line 54
        // only show the first error so the user can focus on it
        $errors = $value->getErrors();
        $message = reset($errors);

        throw new RuntimeException($message);
    }
}
```

Seems to come from `if ($isDashboardExtensionIsLoaded) { $services->set('dashboard.widgets.calendarizeNextEvents')...` out of `calendarize/Configuration/Service.php`. If i comment out the if condition and dump the autoload in the install tool, it works again.

Version: 12.0.0
Autoloader: 7.3.3
TYPO3: 10.4.24

**Comment by lochmueller** [comment]
Hey @bavarianbytes 
is the EXT:dashboard installed in your installation?
Regards,
Tim

**Comment by bavarianbytes** [comment]
No. Is that required for calendarize?

**Comment by lochmueller** [comment]
No. It is not required. The reason why we use this Services.php and the condition is, that EXT:dashboard is optional and no requirement. I will check this in my test installation again in the next days...

**Comment by mbsued** [comment]
same problem here with Version 12.0.0 and Typo3: 10.4.25

**Comment by okmiim** [comment]
With the change 3ac8bc5985b2db189dc77d3c09b3726f4d6524c7 this should hopefully be fixed.

Since I could not reproduce the problem, I cannot say that for sure. However, the same fix was used in [ke_search](https://github.com/tpwd/ke_search).
If the problem persists with the master/next release, feel free to reopen/create a new issue.
