### ISSUE TITLE
TYPO3 10: Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery()

### ISSUE THREAD

**Issue by cdaecke** [lochmueller/calendarize#673]
The method `QueryBuilder::executeQuery()` is only available in TYPO3 > 10, so I get the error `Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery()` in

https://github.com/lochmueller/calendarize/blob/1db60b14222d53c8a77263ac813c2b9d4faeeec6/Classes/Utility/EventUtility.php#L76

Do you want to adjust this, or is ext:calendarize v12.0.0 for TYPO3 > 10 only?

Environment:
- TYPO3 v10.4.23
- ext:calendarize v12.0.0

**Comment by okmiim** [comment]
Hi @cdaecke,

thank you for the report. TYPO3 v10 is still supported and the bug is fixed in the next release.

**Comment by cdaecke** [comment]
@okmiim Thanks a lot for the quick change!

Unfortunately `fetchAssociative()` is also not available in TYPO3 v10. It should be `fetch()`.

https://github.com/lochmueller/calendarize/blob/be1308810c8a8f84a644a6a7d86269986541fefa/Classes/Utility/EventUtility.php#L77

**Comment by okmiim** [comment]
@cdaecke that is interesting ... since my local installation (also 10.4) worked fine.

After a bit of research, I figured it out:
TYPO3 v10.4 uses `"doctrine/dbal": "~2.10.0 || ~2.11.2 || ~2.13.1"`.
The method `fetchAssociative` was introduced in 2.11, so some older installations are without it.

**Comment by cdaecke** [comment]
@okmiim Thanks a lot for your research!

I tested with TYPO3 v10.4.23 in non-composer mode. Maybe that's the reason, why it did not work for me?
As far, as I can see, TYPO3 v10.4.23 uses Doctrine\DBAL v2.13.5. Strange...
