### ISSUE TITLE
Event is displayed twice in year view

### ISSUE THREAD

**Issue by ok-simplethings** [lochmueller/calendarize#675]
An event is shown in two months if the calendar week in which the event takes place is in two months.

![2022-03-21_09h10_58](https://user-images.githubusercontent.com/102020456/159227884-e4575c80-beb1-4ca9-bf8c-e2a233a94ffe.png)

The problem is in the `calendarize/Resources/Private/Partials/Month.html` template. 
There is a loop over the `weeksInMonth` and then over `daysInWeek`.

```
<tbody class="regularMonthView">
	<c:loop.weeksInMonth date="{date}" iteration="week" weekStartsAt="{settings.weekStart}">
		<tr>
			<c:loop.daysInWeek date="{week.calendar.date}" iteration="day" weekStartsAt="{settings.weekStart}">
				<f:if condition="{c:dateTime.indexOnDay(indices: indices, day:day.calendar.date)}">
```

The calendar week of March 5. begins in February and the calendar week of March 28. ends in April.

![grafik](https://user-images.githubusercontent.com/102020456/159232196-38e3f3f8-b67c-40da-81a3-005a1c6cecf4.png)

# Possible solution

A possible solution is to just loop over the `daysInMonth` in the  `calendarize/Resources/Private/Partials/Month.html` template.

```
<tbody class="regularMonthView">
     <tr>
         <c:loop.daysInMonth date="{date}" iteration="day">
             <f:if condition="{c:dateTime.indexOnDay(indices: indices, day:day.calendar.date)}">
```

![grafik](https://user-images.githubusercontent.com/102020456/159233650-b9053689-39a7-482f-96e2-fa5fe65a64b7.png)

**Comment by lochmueller** [comment]
Hey @ok-simplethings ,

as @okmiim  already mentioned. The month view display events in the overlapping weeks. You have to check the Date in your iteration. You could also check the date of the Iteration with the date of the event with the `Y-m` date format. So the event is only rendered, if the month fit exactly.

I will close this issue. Thank you for reporting...

Regards,
Tim
