### ISSUE TITLE
EventTitle does not show configuration information on hidden items

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#677]
![Two Events in Listview, one missing the configuration info](https://user-images.githubusercontent.com/7593443/159805954-9e361242-ff1b-4316-82d1-0d7d2df875dc.png)

The function `TcaService->eventTitle` (used for `label_userFunc`) does not show infos about the configuration on hidden elements.
The code is probably not workspace aware.

https://github.com/lochmueller/calendarize/blob/d62841c2bfb060d9aa21a9406cc43ab0d7908f48/Classes/Service/TcaService.php#L55-L100

The following query contains `hidden = 0`
https://github.com/lochmueller/calendarize/blob/d62841c2bfb060d9aa21a9406cc43ab0d7908f48/Classes/Service/TcaService.php#L70

**Comment by lochmueller** [comment]
Hey @okmiim 
Should we just replace
```$fullRow = $databaseConnection->select(['*'], $table, ['uid' => $params['row']['uid']])->fetch();```
with
```$fullRow = BackendUtility::getRecord($table, (int)$params['row']['uid']);```

The `getRecord` drop all restriction from the QueryBuilder in the selection.

Regards,
Tim
