### ISSUE TITLE
Is it possible to have events without default language?

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/calendarize#678]
I configured two languages in the site config:
- `de` (default)
- `en` (`fallbackType: strict`)

If i create an event in english only, it doesn't appear in the frontend.
Is there a way to achieve that?

BTW:
For the news extension i use https://github.com/georgringer/extbase_with_no_l10n_parent to achieve exactly that behavior. This extension provides a setting for the db tables it should work. Tried to configure it to `tx_calendarize_domain_model_event`, but doesn't work.

**Comment by okmiim** [comment]
Hi @bavarianbytes,
I have no clue about the mentioned extension, however, try to configure it to use `tx_calendarize_domain_model_index`.
The table is mainly used in the background to generate the lists/details. Only in a "second step" the data of  `tx_calendarize_domain_model_event` is accessed.

**Comment by bavarianbytes** [comment]
Thanks for your input! Doesn't work either :-(
I even tried to set `*` for all tables. Seems that the ext doesn't work for calendarize.

Any other ways to achieve that?
Wonder if other people don't have the use case to have data records in non-default languages...

**Comment by okmiim** [comment]
Hi @bavarianbytes,
I have tested it with my local 11.5 installation and it showed the record in the foreign language (with the mentioned extension). In my testcase I used a listview with no "special" configuration.

Do you use a special configuration, categories, ... or something?

**Comment by bavarianbytes** [comment]
Hi @okmiim,
no, it is just a list view with no special settings and no categories:
<img width="1013" alt="Bildschirmfoto 2022-04-07 um 11 45 51" src="https://user-images.githubusercontent.com/17915115/162171663-176baa2d-01f5-40cb-bb6a-5163e46718b7.png">
<img width="1014" alt="Bildschirmfoto 2022-04-07 um 11 46 03" src="https://user-images.githubusercontent.com/17915115/162171656-ae1a0a23-a0bc-4a5c-923f-0b69b58968c0.png">

I use TYPO3 10.4.26.

How does your config for `extbase_with_no_l10n_parent` and the second language in the `siteconfig` looks?

**Comment by bavarianbytes** [comment]
Thanks for your help @okmiim. I found the problem!

The author of the extension renamed it from `extbase_records_with_no_l10n` to `extbase_with_no_l10n_parent`. Therefore the extension configuration of it (for the tables) had a different naming and couldn't be loaded.
