### ISSUE TITLE
(Edge case) Wrong time of imported recurring events from different timezones with/without DTS

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#679]
Imported recurring events have the wrong time, where the imported date is set in a different timezone (than the server) having no or other Daylight Saving Times (DST).
This affects dates, which are in the "other" DST than the first event or where the switch happens at different dates.

## Example

Server timezone: `Asia/Seoul` (no DST)
Recurring event from `America/New_York` (has DTS)

ICS:
```ics
DTSTART;TZID=America/New_York:19970904T090000
RRULE:FREQ=MONTHLY;COUNT=10
```

The following table shows the actual time, the time in the Seoul timezone and the partly wrong generated indices.

| New_York | New_York -> Seoul | Generated (Seoul), _wrong_ |
|-|-|-|
| 1997-09-04 09:00 | 1997-09-03 20:00 | 1997-09-03 20:00 |
| 1997-10-04 09:00 | 1997-10-03 20:00 | 1997-10-03 20:00 |
| 1997-11-04 09:00 | 1997-11-03 19:00 | _**1997-11-03 20:00**_ |
| 1997-12-04 09:00 | 1997-12-03 19:00 | _**1997-12-03 20:00**_ |
| 1998-01-04 09:00 | 1998-01-03 19:00 | _**1998-01-03 20:00**_ |
| 1998-02-04 09:00 | 1998-02-03 19:00 | _**1998-02-03 20:00**_ |
| 1998-03-04 09:00 | 1998-03-03 19:00 | _**1998-03-03 20:00**_ |
| 1998-04-04 09:00 | 1998-04-03 19:00 | _**1998-04-03 20:00**_ |
| 1998-05-04 09:00 | 1998-05-03 20:00 | 1998-05-03 20:00 |
| 1998-06-04 09:00 | 1998-06-03 20:00 | 1998-06-03 20:00 |

## Example 2

Server timezone: `Europe/Berlin` (no DST)
(same ics as above)

Wrong event: 
- 1998-04-04 _**15:00**_ (instead of 16:00)

Why:
- DTS starts in Berlin 1998-03-29
- DTS starts in New_York 1998-04-05

**Comment by lochmueller** [comment]
Hey @okmiim 
I close this issue currently. It is really a edge case and perhaps more or less a problem of the parsing lib.
Regards,
Tim
