### ISSUE TITLE
imported events aren't displayed

### ISSUE THREAD

**Issue by GitCybers** [lochmueller/calendarize#681]
After importing events with the scheduler the events aren't displayed in the eventlist. When I open the imported event in the list view in typo3 were I can change the event description or the date and save the event WITHOUT making any change the event will be displayed.

**Comment by lochmueller** [comment]
Do you check if this is just a cache invalidation problem. If you clear the FE cache, the event is also loaded?

**Comment by lochmueller** [comment]
Hey @okmiim 

also good point... I also checked the import method and there is a reindexAll: https://github.com/lochmueller/calendarize/blob/master/Classes/Command/ImportCommandController.php#L181 So I hope it is no inconsistency in the index :) 

Hey @GitCybers 
please add your EXT:calendarize version, the information if you use the default events and the default import process, and your TYPO3 Version.

Regards,
Tim

**Comment by lochmueller** [comment]
No feedback related to the open questions. Please check if the reindexAll is really executed at the end of the import in your case and if really the indices are missing in the DB (Check index table, open record, save, check index table again)
