### ISSUE TITLE
"ignore enable columns"???

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#694]
What das "ignore enable columns" mean here?

![grafik](https://user-images.githubusercontent.com/367315/173537122-06e4ea56-c3f9-4e4e-beb1-751350fe5bb3.png)

**Comment by okmiim** [comment]
Hi @artus70,
enablecolumns refers here to the _publishing control features_ of TYPO3. These are `hidden`, `starttime`, `endtime` (not the event configuration, but the records visibility) and `fe_group`.
Example: one configuration is hidden/disabled. The list in the backend will still contain the index, whereas it is not visible in the frontend.

**Comment by artus70** [comment]
That makes it clear to me - thanx a lot!

But at the same time it shows that the wording is not very understandable so far. We may try to rephrase that appropriately.
