### ISSUE TITLE
Feature request - paginator in year, quarter, month, week, day view

### ISSUE THREAD

**Issue by birgitberlin** [lochmueller/calendarize#698]
After upgrading from v.6 to v.12 I lost the pagination (old widget) in several views. 
The pagination is available in list and latest actions only. 

Would be nice, if you would add it to year, quarter, month, week, day action.

 $this->eventExtendedAssignMultiple([
            'indices' => $search['indices'],
            'pagination' => $this->getPagination($search['indices']),
...
], __CLASS__, __FUNCTION__);

**Comment by okmiim** [comment]
Hi @birgitberlin,
could you elaborate a bit more, how you used the pagination, e.g., in the month action?
For me, the month view is just a grid with the events in it and there is nothing to paginate inside one month.

What I can image:
1. You modified the month template and "converted"/displayed it to/as a list
2. You additionally used a list action on the same page
