### ISSUE TITLE
Check translation handling

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/calendarize#70]
https://typo3.slack.com/archives/ext-calendarize/p1464097387000014

Step by step:
1. Create a record in the default language and add a calendarize event
2. Clicked on the detail link `?tx_calendarize_calendar%5Bindex%5D=646` - it works, great (index id 646)
3. Translate the record into a second language
4. Clicked on the detail link `?tx_calendarize_calendar%5Bindex%5D=646` - error, shit (index id 646)

When I create manual a new index, with l10n_parent 646, the detail page works.
It seems like the Model of Index respect the sys_language_id, cant find a non-default language `calendarize_index` and give up.
The `$index` of `detailAction` is empty

**Comment by OwlAsh** [comment]
Dirty workaround, may help to find the bug:

detailAction
`
        if($index === null) {
            $indexId = (int) $this->request->getArgument('index');

            if(is_int($indexId)) {
                $index = $this->indexRepository->findByUid($indexId);
            }
        }`

**Comment by lochmueller** [comment]
Note for me: There is one discussion here: https://github.com/lochmueller/calendarize/commit/2c552df7dafceb6460740983ff62ecb048fb8f76
