### ISSUE TITLE
Issue with latest previous month link

### ISSUE THREAD

**Issue by webian** [lochmueller/calendarize#703]
How to reproduce:
A. have a plugin with switchableControllerActions set as Calendar->month
B. have config: plugin.tx_calendarize.settings.dateLimitBrowserPrev = -2 years

With this setup it happens that:
1. browsing now the month 10/2020 will produce a link to browse the previous month 09/2020.
2. browsing this previous month generates a 404 because method isDateOutOfTypoScriptConfiguration returns true because:
2020-09-24 19:23 > 2020-09-24 00:00

I think that Calendarize shouldn't generate that link to browse previous month OR it should consider the date inside of Typoscript configuration normalizing from 2020-09-24 19:23 to 2020-09-24 00:00.

(same happens with the 'next' link of the last browsable month)

**Comment by webian** [comment]
Maybe there's something wrong here:
https://github.com/lochmueller/calendarize/blob/0cf246212ab421e680ebf50468461dee8d9bd349/Resources/Private/Partials/Month.html#L8
because if xdebugging I place a breakpoint in:
`\HDNET\Calendarize\ViewHelpers\IfDateUpperViewHelper::render`
it doesn't stop (aka: not reaching the render method).

Also, if I take:
`{c:ifDateUpper(base: settings.dateLimitBrowserPrev, check:{date -> c:dateTime.modify(modification: 'first day of last month')})}`
outside of the f:if, it doesn't render the result, it renders the viewhelper configuration as string.

**Comment by webian** [comment]
Yes, replacing:
https://github.com/lochmueller/calendarize/blob/0cf246212ab421e680ebf50468461dee8d9bd349/Resources/Private/Partials/Month.html#L8
with
```
<f:variable name="modifiedDate"><c:dateTime.modify modification="first day of last month">{date}</c:dateTime.modify></f:variable>
<f:variable name="dateCheck"><c:ifDateUpper check="{modifiedDate}" base="{settings.dateLimitBrowserPrev}">1</c:ifDateUpper></f:variable>
<f:if condition="{dateCheck}">
```
it works (same for next).

So probably there's something in the short version that messes in Fluid.

**Comment by okmiim** [comment]
Hi @webian,
good issue description and debugging.
Your were right with the faulty inline statement.
The nested fluid statements were not correctly escaped causing the if to always be true.
