### ISSUE TITLE
Feature Request: move dateFormat and timeFormat to locallang

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/calendarize#704]
Wouldn't it be good practices to handle the `dateFormat` and `timeFormat` (used in the fluid templates) via the `locallang` files instead of via settings?
Therefore users could easily extend the formats for other languages, no TypoScript conditions neccessary.

At least a lot of extensions handle these formats via `locallang`.

**Comment by lochmueller** [comment]
Hey @bavarianbytes 
yes you are right. I think locallang is a good way to configure this.
Regards,
Tim
