### ISSUE TITLE
Feature request - Access event's category record like in tx_cal

### ISSUE THREAD

**Issue by nils-weidinger** [lochmueller/calendarize#705]
Extension tx_cal allowed access to complete category record in event's fluid partial. With field "News category shortcut" (only when tx_news is installed) you could display event's category items as links.

`		<f:for each="{event.categories}" as="category">
			<f:if condition="{category.row.shortcut}">
			<f:then><h3 class="category-link"><f:link.typolink parameter="{category.row.shortcut}">{category.title}</f:link.typolink></h3></f:then>
			<f:else><h3>{category.title}</h3></f:else>
			</f:if>
		</f:for>`

I'd highly appreciate if that was possible with calendarize too. Can I maybe configure calendarize in a way to get that data?

**Comment by lochmueller** [comment]
Hey @nils-weidinger 
this is part of your own event structure. If you are using the example event of the extension. The categories are part of the mapping: https://github.com/lochmueller/calendarize/blob/master/Classes/Domain/Model/Event.php#L135 and should be accessible in every template via "index -> event -> categories".
I will close this issue. Feel free to ask integration questions in the #ext-calendarize Slack channel...
Regards,
TIm
