### ISSUE TITLE
Feature Request: Prevent path duplicates

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#706]
When editing a calendar event, the slug of that event may not be unique. Unlike page slugs, TYPO3 (or Calendarize) does not prevent the accidental creation of path duplicates here, although the resulting path is calculated by TYPO3 and displayed as correct (green).

This may lead to two (or more) event entries linking to the same event detail view - preventing some of the events to show their actual detail view.

May Calendarize check if a slug already exists and - even better - prevent duplicates?

![grafik](https://user-images.githubusercontent.com/367315/195815549-b7597957-354a-4252-932b-0ae99dcc1b24.png)

**Comment by lochmueller** [comment]
Hey @artus70 

That is strange.... https://github.com/lochmueller/calendarize/blob/master/Configuration/TCA/tx_calendarize_domain_model_event.php#L98 "eval = unique" is already set: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Slug.html

Please confirm, that you are using the current version of EXT:calendarize and which TYPO3 Version do you use?

Regards,
Tim

**Comment by artus70** [comment]
I checked again and found that the duplicate check _sometimes_ works!

Then I saw that the event where it doesn't work has `sys_language_uid = -1`, while the event where I'm editing the slug has `sys_language_uid = 0`. Apparently the duplicate check fails when sys_language_uid differs.

Regards
Volker

**Comment by lochmueller** [comment]
Hey @artus70 
perhaps this is a core problem. It is OK, that every slug exist once in every language. But "-1" is a special one. Perhaps this is not checked in core :-/
Regards,
Tim

**Comment by artus70** [comment]
So if the problem is not caused by Calendarize, we can close this issue here.

In the current case I could help myself by renaming the slug to something more individual, so that the risk of a duplicate slug was minimised.

Thanks
