### ISSUE TITLE
Migrate Italian translations to Crowdin

### ISSUE THREAD

**Issue by webian** [lochmueller/calendarize#709]
I probably miss the permissions to upload the TYPO3 10 xlf of the Italian translation in Crowdin because when I try to upload the xlf nothing happens, while I can do it in a personal Crowdin test project.

Please @lochmueller can you try?

Quick steps:
1. [Get the TYPO3 10 xlf](https://typo3.slack.com/archives/C0HMW4NDA/p1666270072324759?thread_ts=1666250671.224879&cid=C0HMW4NDA)
2. Go to [Crowdin Calendarize Italian](https://crowdin.com/translate/typo3-extension-calendarize/5054/en-it?filter=basic&value=0) 
3. Press CTRL+INS to upload the xlf

**Comment by lochmueller** [comment]
Hey @webian 
"You uploaded 204 translations into Italian". Done & Approved. IT is now on 83%.
Regards,
Tim

**Comment by webian** [comment]
Thank you @lochmueller !
I completed the missing translation.
I also tried to improve some already approved translations and Crowding only let me to notify the proofreader (you).
Please accept my edits.

**Comment by lochmueller** [comment]
Hey @webian 
Done. Thanks for the translation and improvement.
I'll close this issue.
Regards,
Tim
