### ISSUE TITLE
Cannot cast object of type "DateTime" to string

### ISSUE THREAD

**Issue by Make66** [lochmueller/calendarize#717]
I had my first composer installation of T3v10 with an old calendarize 5.x which stopped to work because of datetime __toString casting issue. Using default cal_dom_mod_event object, no extension. Now I upgraded calendarize to 12.4.1 (latest) and still got casting issues (loosing all events because of changed date format is ok for me):

(1/1) Error: **Object of class DateTime could not be converted to string**
in /base/project/var/cache/code/fluid_template/partial_Date_Static_859b25ebd1c6a7d5d9c0b9e0ec1540cf91f84e98.php line 1066

So I emptied Partial/Date/Static.html to remove all dateObject->f:format.date viewhelpers.
Error message changed to:

(1/1) #1273753083 TYPO3Fluid\Fluid\Core\Parser\Exception
**Cannot cast object of type "DateTime" to string.**
in /base/project/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php line 71
The code there reads like:
`  /**

     * @param mixed $value

     * @return string
 
     */

    protected function castToString($value)

    {

        if (is_object($value) && !method_exists($value, '__toString')) {

            throw new Parser\Exception('Cannot cast object of type "' . get_class($value) . '" to string.', 1273753083);

        }

        $output = (string) $value;

        return $output;

    }`
What I did to fix the error:
1) Analyze Database Structure until everything is fine.
2) Check cal_dom_mod_index values in db for start_date(date) and end_date(date) which looks fine to me (i.e. "2022-12-01"). start_time(int=0) and end_time(int=1) look good for me as well.
3) Flush TYPO3 and PHP Cache
4) anything missing?

Project composer.json attached (this file is basically generated using "composer req" and manually added the local repos.

How can I make calendarize run?
Many thanks in advance!

Hint for exception timestamp:
TS to Datetime: #1273753083
Assuming that this timestamp is in seconds:
GMT: Thursday, 13. May 2010 12:18:03
Your time zone: Donnerstag, 13. Mai 2010 14:18:03 [GMT+02:00](https://www.epochconverter.com/timezones?q=1273753083) DST
Relative: 12 years ago

[composer.json.txt](https://github.com/lochmueller/calendarize/files/9978971/composer.json.txt)

**Comment by lochmueller** [comment]
Hey @Make66 

first of all: Thanks for the Pizza support :-) 

I checked this. Looks like a date object or property is used in the templates, without the "f:format.date" ViewHelpers. Do you check if you find the template? Do you use any own templates? Are all template the templates of EXT:calendarize?

Regards,
Tim

**Comment by Make66** [comment]
Welcome!

Ok I thought, I would use only original templates. But somebody optimized ListItem view, which I found in the good old TypoScript Object Browser!

Nevertheless, digging and debugging into the templates, I found this:
Resources/Private/Partials/List.html calls partial `{index.configuration.partialIdentifier}/ListItem.html`
but in Debug, (looping over indices as index) there is no 
`indices.0.configuration.partialIdentifier` which should resolve to "Event/"
to find partial Resources/Private/Partials/Event/ListItem.html. 
What is the magic behind?

`Debug of Partial List.html
array(5 items)
   settings => array(31 items)
   indices => TYPO3\CMS\Extbase\Persistence\Generic\QueryResultprototypeobject (1 items)
      0 => HDNET\Calendarize\Domain\Model\Indexprototypepersistent entity (uid=21, pid=8)
         uniqueRegisterKey => protected'Event' (5 chars)
         foreignTable => protected'tx_calendarize_domain_model_event' (33 chars)
         foreignUid => protected7 (integer)
         startDate => protectedDateTimeprototypeobject (2022-12-01T01:00:00+01:00, 1669852800)
         endDate => protectedDateTimeprototypeobject (2022-12-01T01:00:00+01:00, 1669852800)
         startTime => protected0 (integer)
         endTime => protected1 (integer)
         allDay => protectedFALSE
         openEndTime => protectedFALSE
         state => protected'default' (7 chars)
         originalObject => protectedNULL
         slug => protected'hybridseminar-holzfenster-in-olsberg' (36 chars)
         uid => protected21 (integer)
         _localizedUid => protected21 (integer)modified
         _languageUid => protected0 (integer)modified
         _versionedUid => protected21 (integer)modified
         pid => protected8 (integer)
   contentObject => array(112 items)
   pagination => array(2 items)
   index => [HDNET\Calendarize\Domain\Model\Indexprototypepersistent entitysee above](javascript:;) (uid=21, pid=8)
`
You may either close w/o comment but a bit more of learning on my side would be great.

**Comment by lochmueller** [comment]
Hey @Make66 

Does @okmiim explaination help & is this problem solved on your side? Or do you need some more information?

Regards,
Tim

**Comment by Make66** [comment]
Great answer & support, thank you!
