### ISSUE TITLE
PHP 8.2 : Setting the page title on detail view => PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/calendarize#718]
`<c:titleTag><f:render partial="{index.configuration.partialIdentifier}/Title" arguments="{index: index}"/></c:titleTag>`

leads to:

`PHP Runtime Deprecation Notice: Creation of dynamic property TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::$altPageTitle is deprecated in /Users/***/typo3/typo3_src-11.5.16/typo3/sysext/core/Classes/Compatibility/PublicPropertyDeprecationTrait.php line 125`

**Comment by lochmueller** [comment]
Moved to EXT:calendarize Repo.

**Comment by lochmueller** [comment]
Hey @bavarianbytes 
Fixed in current master of EXT:calendarize.
Regards,
Tim
