### ISSUE TITLE
Feature: ICS download containing all events which belong to the currently displayed list

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#719]
The ICS download is so far only possible for individual events. I am looking for an approach to offer an ICS file that contains all events which belong to the current list. 

How can this be achieved? Or does a solution exist already?

**Comment by okmiim** [comment]
HI @artus70 ,

try to remove the commented the lines in the [List template](https://github.com/lochmueller/calendarize/blob/9628732b81c5c69aeed0d80d782e130d59c1d8bc/Resources/Private/Templates/Calendar/List.html):
https://github.com/lochmueller/calendarize/blob/9628732b81c5c69aeed0d80d782e130d59c1d8bc/Resources/Private/Templates/Calendar/List.html#L7-L11
This will generate an ICS link and file with all indices (ignores pagination).

If you only want to generate an ICS with the events on current page (with pagination), replace `{indices}` with `{pagination.paginator.paginatedItems}` in [List.ics](https://github.com/lochmueller/calendarize/blob/9628732b81c5c69aeed0d80d782e130d59c1d8bc/Resources/Private/Templates/Calendar/List.ics)
https://github.com/lochmueller/calendarize/blob/9628732b81c5c69aeed0d80d782e130d59c1d8bc/Resources/Private/Templates/Calendar/List.ics#L4

**Comment by artus70** [comment]
The link urls (ical etc.) are cryptic because of i.e. their cHash parameters.

- Are these links permanent (to be able to subscribe to them with a calendar app)?
- Or: Can they be converted into speaking addresses (leading to permanent urls)?
