### ISSUE TITLE
Class "HDNET\Calendarize\Register" not found

### ISSUE THREAD

**Issue by devxpoint** [lochmueller/calendarize#728]
TYPO3 11.5
PHP 8.1 / 7.4 tested
calendarize 12.4.3
autoloader 7.4.0

Installed calendarize classic way, but can't see static template to include.
Plugin is available as content element, but has no options (flexform)
I can create events and see the backend module.

Very scary.

Any ideas?

**Comment by lochmueller** [comment]
Already fixed. Please uprgade to EXT:calendarize 12.4.4 and EXT:autoloader 7.4.3.
Closed.

**Comment by devxpoint** [comment]
Thanks for your work Tim!
