### ISSUE TITLE
Slug duplicates results in different event displayed for list and detail view

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#731]
Unfortunately, we have several duplicate slugs. 

This sometimes results in the problem that a different event is displayed for detail and for list view.

**SQL**:

for language 0, shows count, everything with count > 1 is a problem:

`select slug,count(*) as c from tx_calendarize_domain_model_event where not hidden and not deleted and (sys_language_uid=0 || sys_language_uid=-1)  group by slug order by c;
`

**Example**: following events on the same page, one with sys_language_uid=0, one with sys_language_uid=1, same slug:

```
select uid,pid,sys_language_uid,slug,title,FROM_UNIXTIME(tstamp),FROM_UNIXTIME(crdate),t3_origuid from typo3.tx_calendarize_domain_model_event  where pid = 21669 and not deleted and slug like 'promovierendenvertretung-6' order by slug;
+------+-------+------------------+----------------------------+---------------------------+-----------------------+-----------------------+------------+
| uid  | pid   | sys_language_uid | slug                       | title                     | FROM_UNIXTIME(tstamp) | FROM_UNIXTIME(crdate) | t3_origuid |
+------+-------+------------------+----------------------------+---------------------------+-----------------------+-----------------------+------------+
| 3655 | 21669 |               -1 | promovierendenvertretung-6 | Promovierendenvertretung  | 2018-09-27 11:05:35   | 2018-09-27 11:05:35   |          0 |
| 7603 | 21669 |                0 | promovierendenvertretung-6 | Promovierendenvertretung  | 2021-07-29 08:56:16   | 2021-07-29 08:56:16   |          0 |
+------+-------+------------------+----------------------------+---------------------------+-----------------------+-----------------------+------------+

```

In the list view, one event is displayed, in the detail view another:

1. list view:
![image](https://user-images.githubusercontent.com/13206455/212045674-c336b6f6-e21d-4e39-b8bf-098abb7bd2b8.png)

2. detail view:
![image](https://user-images.githubusercontent.com/13206455/212045753-c548c4b2-c559-44a3-a674-61e0a40bef10.png)

Notice the different dates.

I assume the collision detection for creating non-duplicate slugs does not work if sys_language_uid=-1 is used.

## version

* TYPO3 11.5.22 (latest)
* calendarize: 12.4.2

**Comment by sypets** [comment]
It looks to me this might actually be a core bug, the configuration (TCA) looks ok to me:

```
slug
  config
    eval = unique
    fallbackCharacter = -
   generatorOptions
     fields
       0 = title
    prefixParentPageSlug =
    replacements
       / = -
    prependSlash =
    type = slug
```

* TCA: slug documentation: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Slug/Index.html

If necessary, this might be helpful:

* changelog: "[Feature: #88198 - TCA-based Slug modifiers for extensions](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5.x/Feature-88198-TCA-basedSlugModifiersForExtensions.html)"

The problem seems familiar and I might have reported it before, but I could not find an issue here or on forge. Will add comment if I find something or report something.

**Comment by sypets** [comment]
https://forge.typo3.org/issues/99529

**Comment by lochmueller** [comment]
Thanks for the investigation.

**Comment by lochmueller** [comment]
hey @sypets 
thanks for push this issue on forge and provide also the fix. The fix is in the core now and I will close this issue here.
Regards,
Tim
