### ISSUE TITLE
After updating from calendarize from 12.4.4 to 12.4.4 date is displayed instead of the start time and end time of all events

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#733]
After the update to 12.4.4, this problem was reported. This is the case in list view and detail view. 

Expected:

> 01.04.2023 12:00 - 14:00

Actual result:

> 01-04-23 01-04-23 - 01-04-23

First tried, reindexing via command line and refresh cache of pages. Did not fix the problem.

On another system, with minimal TYPO3 v11 installation, the problem could be reproduced:

* With calendarize version **12.4.2**: the start and stop time is displayed (ok).
* With calendarize version **12.4.4**, the dates are displayed (not ok).

The same problem occurred with events which had already been created previously and with events which were created with version 12.4.4

## Reproduce

1. Create at least one event in the future with start and stop date
2. Show this event in list and / or detail view

![image](https://user-images.githubusercontent.com/13206455/214105505-e19fdb3f-61bb-4390-92be-d6cccf04dd23.png)

## Versions

* TYPO3 11.5.22
* calendarize 12.4.4

## Example Screenshots

With 12.4.4:

![image](https://user-images.githubusercontent.com/13206455/214104466-0e030bcc-2d38-4aec-b09f-23c876c57851.png)

With 12.4.2:

![image](https://user-images.githubusercontent.com/13206455/214106311-767ff323-0eba-46cc-beca-bf48abe9418d.png)

**Comment by lochmueller** [comment]
Hey @sypets 
Do you clear the system cache after upgrade? We move the date and time format from https://github.com/lochmueller/calendarize/commit/ae59c520518bbdfff25c3abe971a10ecd18b4d14 and the commit looks good for me.
Could you check if the Traslate ViewHelper get the right format?
Regards,
Tim
