### ISSUE TITLE
month view

### ISSUE THREAD

**Issue by d3werk** [lochmueller/calendarize#735]
Moin together,
first of all, that module is really great. I do not know if I'm right here with my question ;)

Can I add the buttons to the previous and next month in the month view above?

I would be glad about ideas...

Cheers

**Comment by lochmueller** [comment]
Hey @d3werk 
You have to set the monthPid for the monthView plugin to the right page (e.g. to the current page).
I will close this issue. Keep in mind, that #ext-calendarize slack channel is the better place for integration questions.
Best regards,
Tim
