### ISSUE TITLE
How to add an additional mode, i.e. "event list with full details"?

### ISSUE THREAD

**Issue by artus70** [lochmueller/calendarize#740]
I would like to offer an _additional_ view mode: Show the full event details _in_ the list view, so that no link to the detail view would be necessary anymore. How can I achieve this? I don't want to overwrite (replace) the existing list template, as I would like to continue using it in this way, too.

Of course, this requires a customised template, a combination of list view and detail view. But how to integrate it?

I know that this will lead to a repeated display of the same full texts when having an event series. But that's not my problem, it's the editors' problem.

**Comment by lochmueller** [comment]
Hey @artus70 
could you change the Template Path for the specific page via TS and overwrite the Templates just for your usecase? I think this is the easiest option (could not controlled by an editor). 

I think it is no "new view", because it is just a list with more information of the model.

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @artus70 
ok. Then I suggest: Extend the flexform configuration with an additional field like "settings.layout". All settings are path trough to the template. In the template, you can evaluate the new setting variable and render an alternative list view. Then the editor can control the different view by setting the "settings.layout" checkbox (or select box).
Regards,
Tim

**Comment by okmiim** [comment]
Just for completeness:

- Add field to flexform
  - The field could look like this [EXT:News `settings.templateLayout`](https://github.com/georgringer/news/blob/d6eb4e9f67cc1d0690f216cb483a5b95f09e5313/Configuration/FlexForms/flexform_news_list.xml#L526-L542)
  - **TYPO3 v11**: Add flexform hook 
    - see [calendarize_news FlexFormHook](https://github.com/lochmueller/calendarize_news/blob/96d7844a9ab6e3cfab238d1331944365b5a40d58/Classes/Hooks/FlexFormHook.php) or [EXT:news v10 Extend FlexForms](https://docs.typo3.org/p/georgringer/news/10.0/en-us/Tutorials/ExtendNews/ExtendFlexforms/Index.html#extend-flexforms-with-custom-fields)
    - `dataStructureKey` should be `calendarize_calendar,list`
  - **TYPO3 v12**: Listen for `AfterFlexFormDataStructureParsedEvent`
    - see [calendarize_news ModifyFlexformEvent](https://github.com/lochmueller/calendarize_news/pull/48) or [EXT:news v11 Extend FlexForms](https://docs.typo3.org/p/georgringer/news/11.2/en-us/Tutorials/ExtendNews/ExtendFlexforms/Index.html?highlight=flexform#extend-flexforms-with-custom-fields)
    - `dataStructureKey` should start with `calendarize_`
- Update fluid templates/partials and check for e.g. `<f:switch expression="{settings.templateLayout}">`
