### ISSUE TITLE
calender export (ICS, Atom, RSS) fails with non-list view plugins on same page

### ISSUE THREAD

**Issue by albig** [lochmueller/calendarize#753]
I'm again on the calendar export feature. In the past, I fixed the usage of multiple calendarize list view plugins on the same page. See #716.

## Description

With a calendarize plugin in non-list view above a list view, the calendar export fails.

![Page · Calendar · New TYPO3 site  TYPO3 CMS 11 5 28 ](https://github.com/lochmueller/calendarize/assets/3354500/26991c8e-06f3-4b1b-82df-d9d7f61ee39e)

Reason is, there is no template found.

```
(1/1) #1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
Tried resolving a template file for controller action "Calendar->year" in format ".xml", but none of the paths contained the expected template file (Calendar/Year.xml).
``` 
That's curios, because the called link is as follows:

https://example.site/content-examples/calendar?tx_calendarize_calendar%5Baction%5D=list&tx_calendarize_calendar%5Bcontroller%5D=Calendar&tx_calendarize_calendar%5Bformat%5D=xml&tx_calendarize_calendar%5Bhmac%5D=904069e516e526113124c3820747ebe721473471&cHash=f8d1591a843eb8bfd34fe88861abd846

* the action is `list`.
* the controller is `Calendar`
* the format is `xml`
* and the hmac is proper calculated

So, why do we need a `Year` template for the export? This is not requested at all.

## Howto Reproduce

* place a calendarize plugin with mode "Year" (or quarter, month, week, day, past) as first plugin
* place a calendarize plugin with mode "List only" or "List + Detail" below
* uncomment the calendar export links in the list view template `Resources/Private/Templates/Calendar/List.html`
* call one of the export formats (rss/xml, atom, ics) in frontend

## Possible fixes

1. You can clone the `List.xml`, `List.atom` and `List.ics` templates and save it as `Year.xml`, `Quarter.xml` and so on. This looks quite ugly, to me, but it works.
2. We find a better solution in the CalendarController class. I'll provide a working proposal as PR.

**Comment by lochmueller** [comment]
Hey @albig 
the "format" requested for the page is the format for all plugins in this context (so also the year plugin). That is the reason, why these problems occur. I think the best solution is, to split up the Plugins and Remove the switchableControllerAction (like EXT:news already did), to avoid the conflict between plugins.
Regards,
Tim
