### ISSUE TITLE
categories missing 

### ISSUE THREAD

**Issue by eBornstein** [lochmueller/calendarize#757]
Hi, 
a user has rights to edit events but the categories that he has no permission for are deleted after saving the record...
I dont know if its a bug or itentional, but how can i prevent this from happening? 
The extension tx_news  can handle it.
TYPO3 10.4.37
calendarize 12.4.4

**Comment by lochmueller** [comment]
Hey @eBornstein ,
could you check your user rights? There is no "internal permission" handling in EXT:calendarize and we use the core permission handling. Please check that the user could edit the event and the index and send us a error message from the log.
Regards,
Tim

**Comment by eBornstein** [comment]
Hi Tim,
sorry for the misunderstanding. The user has rights for event and index and categorie1. If the event has categorie1 and categorie2, and the user saves the event, categorie2 is lost.
But you are right, I tested it with categories on pages and there is the same behavior. So it is a TYPO3 bug/feature. The more I am surprised that it works with tx_news. 
I thank you for the quick answer.
Regards,
Evi
