### ISSUE TITLE
Use system categories for plugin configuration

### ISSUE THREAD

**Issue by devxpoint** [lochmueller/calendarize#758]
It should be possible to select/show events by sys categories in the plugin configuration.
That would be very useful.

**Comment by okmiim** [comment]
Hi @devxpoint,

it is actually possible to filter the displayed events (e.g. plugin list action) by categories.
The categories can be selected in the categories tab of the content element (not in the plugin options) or in the Plugin Configuration. The filter logic uses OR, meaning that all event records which belong to at least one of the selected categories are shown.

![plugin-categories](https://github.com/lochmueller/calendarize/assets/7593443/aaa0e9ec-18bb-4daa-852a-fd7b402fc9d6)



Regards

**Comment by devxpoint** [comment]
Thanks :)
