### ISSUE TITLE
Create a 12.x branch or a 12.4.5 release for pre-12LTS code

### ISSUE THREAD

**Issue by jpmschuler** [lochmueller/calendarize#760]
Could you branch out b109e0b9b181b7c68c89d04a9785682e75b1b67d perhaps?
The commits up to that include fixes I need, because e.g. with my Gmail iCal import I would get errors in 11LTS without it. So there are a lot of valuable commits after the latest 12.4.4 release but before the 12LTS-only-commit 285e2a89de2fca3414466a6fe1ca2a0e3c061768.

I used b109e0b9b181b7c68c89d04a9785682e75b1b67d without problems, so I deem that stable, although I don't use much of the functionality to be a reliable source. Even if a 12.4.5 release would need too much testing to be released, **a 12.x-dev-branch would be appreciated** to easily install that using composer without the need for composer-patches.

(Side-note for the reason: pinning a composer commit is only possible if the branch has the same deps, as the deps of latest commit are used. Thus, b109e0b9b181b7c68c89d04a9785682e75b1b67d is not pin-able with dev-master, as latest dev-master dropped 11LTS support - that is a complex, but known composer issue that won't be resolved)

**Comment by lochmueller** [comment]
Hey @jpmschuler 

done: https://github.com/lochmueller/calendarize/tree/v11

I branch out the v11 version and keep the master on dev/v12

Regards,
Tim

**Comment by jpmschuler** [comment]
Hey Tim,

Wonderful, thx!
(my v12 was in regards to EXT-version following v12.4.4, but naming them in regards to TYPO3-LTS is fine as well)

Regards,
Peter
