### ISSUE TITLE
Past events in list view

### ISSUE THREAD

**Issue by lilu82** [lochmueller/calendarize#763]
Hi,
the list view with relative date is not working as aspected.
I need a view to show past events from -1 month to now, but its not working and i dont know why. The past view is no option.

This setting is working, but i dont want to show future events:
settings.useRelativeDate=1
settings.overrideStartRelative=-1 month
settings.overrideEndRelative=+1 month
- 20.06.22
- 25.10.22
- 06.10.23
- 20.10.23

not working:
settings.useRelativeDate=1
settings.overrideStartRelative=-1 month
settings.overrideEndRelative=+1 day
- no events found

not working:
settings.useRelativeDate=1
settings.overrideStartRelative=-1 month
settings.overrideEndRelative=now
- no events found

The settings in extension configuration are enabled and set: 
basic.respectTimesInTimeFrameConstraints
basic.tillDaysRelative
basic.tillDays = 600
basic.tillDaysPast = 365

What I am doing wrong? 

TYPO3 10.4.37
calendarize 12.4.4

**Comment by okmiim** [comment]
Hi @lilu82,

your first example is correct and works on my side. 
Plugin configuration
```
settings.useRelativeDate=1
settings.overrideStartRelative=-1 month
settings.overrideEndRelative=+1 month
```

The `now` keyword only works in `overrideStartRelative`, NOT in `overrideEndRelative`.

Do you need more support?

---
Explanation:

The end date is relative to the start date, meaning

`startdate = now - 1 month`
`enddate = startdate + 1 month = now - 1 month + 1 month = now`


_Note: the fields (`basic.tillDays*`) in the extension setting are not relevant for the Plugin, but used in the indexing process._

**Comment by lilu82** [comment]
The key is "end date is relative to the start date". 
Thanks, now I understand how it works.
