### ISSUE TITLE
Next months days start earlier with 1 day

### ISSUE THREAD

**Issue by iamrobertsillo** [lochmueller/calendarize#765]
When I'm in the month view on the current month, everything works well and days are positioned exactly as expected, so to make an example for October 2023:
11 Wed 2023 is correct that is on Wednesday.

The issue starts when I go to November and so on. The 1st day of the month should be on Wednesday, but on the Typo3 calendar is on Tuesday. What I found is that there seem to be two Sundays instead of one. One is hidden and one is visible. I found it out by changing the weekStartsAt to 0 instead of 1. This makes my week start with Sunday instead of Monday so all days shift.
Why is that happening and how can I solve this issue? Thanks.

**Comment by lochmueller** [comment]
Hey @iamrobertsillo 
in my current master with TYPO3 v12 everything looks good :-/ Do you have some specail timezone configuration on your server?

<img width="476" alt="Bildschirmfoto 2023-10-12 um 22 24 50" src="https://github.com/lochmueller/calendarize/assets/3907126/549ed283-103a-4da2-975c-7530a5c9494f">

Regards,
TIm
