### ISSUE TITLE
ICS import option for editors

### ISSUE THREAD

**Issue by Somebodyisnobody** [lochmueller/calendarize#769]
As an editor I would like to have an option to upload a CSV or iCalendar (RFC [5545](https://tools.ietf.org/html/rfc5545)) file on demand and insert contained events in a batch to avoid a manual insertion of a large number of entries.

Currently we're using the following fields:
- Title
- Description
- Event location
- Calendarize start date
- Calendarize start time
- Calendarize end date
- Calendarize end time
- System categories to restrict visibility in several views of the calendar (iCalendar categories could be used here)

Does there exist something like this?

**Comment by Somebodyisnobody** [comment]
Okay, so you mean I create the events and their configuration bypassing EXT:calendarize (e.g. through a custom extension that manipulates the database) and then trigger EXT:calendarize to process the events (redexing).

There is no way to implement this as feature? 🥺

**Comment by lochmueller** [comment]
Hmm... I think the feature is in EXT:calendairze in the wrong place, because it is very special. So I suggest developing this in a own extension. If you need help, you can contact me via TYPO3 Slack.

**Comment by Somebodyisnobody** [comment]
Okay thank you. I found a solution with a click-macro for now. I'll close this as not planned for now.
