### ISSUE TITLE
Show only categories from specific storage

### ISSUE THREAD

**Issue by agendartobias** [lochmueller/calendarize#771]
Hey,

does you extension respect TSConfig - TCEFORM.tx_calendarize_domain_model_event.categories.PAGE_TSCONFIG_IDLIST = id ?

So editors can see only specific categories when adding records for calendar.

**Comment by agendartobias** [comment]
Hey, yes i tried it and dont work :/

But it also true that is use your 13.0.0-dev version (because of TYPO3 12.4.x)

**Comment by okmiim** [comment]
Hi @agendartobias,

we don't support this out of the box. But you can add this to your one sitepackage.

`Configuration/TCA/Overrides/tx_calendarize_domain_model_event.php`

```php
$GLOBALS['TCA']['tx_calendarize_domain_model_event']['columns']['categories']['config']['foreign_table_where'] = (
    'AND {#sys_category}.{#pid} IN (###PAGE_TSCONFIG_IDLIST###) ' .
    ($GLOBALS['TCA']['tx_calendarize_domain_model_event']['columns']['categories']['config']['foreign_table_where'] ?? '')
);
```

Regards

**Comment by agendartobias** [comment]
@okmiim thank you, it works !!!
