### ISSUE TITLE
Error: No Event found! There is no valid fallback PID (list) in the detail plugin

### ISSUE THREAD

**Issue by thomasvollmann** [lochmueller/calendarize#776]
Ich bin offenbar zu blöd einen Newseintrag in einem Detail anzeigen zu lassen.

Danke für Feedback!

mfg
TV

**Comment by okmiim** [comment]
Hi @thomasvollmann,

du hast scheinbar ein Plugin mit einer Detail action konfiguriert. Diese Meldung erscheint, wenn du diese ohne ein Event/Index aufrufst (Details ohne ein Event macht keinen Sinn).

- Hast du eine weitere Seite mit einem Calendarize-List-Plugin konfiguriert? (vgl. [Getting Started](https://docs.typo3.org/p/lochmueller/calendarize/12.4/en-us/UserManual/GettingStarted.html), wo List+Detail konfiguriert ist)
- Welche Typo3 & calendarize Version verwendest du?
- Hast du die HTML Templates modifiziert?
- Was meinst du mit "Newseintrag"? Meinst du die Extension News?

**Comment by lochmueller** [comment]
Hey @thomasvollmann 
noch eine Ergänzung, dazu falls du wirklich "Newseintrag" meins (EXT:news Einträge zusammen mit EXT:calendarize_news). Diese haben in Calendarize keine Detail-Seite, sondern nur die Detail-seite von EXT:news.
Beste Grüße,
Tim

**Comment by thomasvollmann** [comment]
Ich schäme und verkrieche mich in ein Mauseloch.... ,)

**Comment by lochmueller** [comment]
D.h. es klappt nun und wir schließen das Issue? ;)
