### ISSUE TITLE
IndexItem sorting

### ISSUE THREAD

**Issue by saneinsane** [lochmueller/calendarize#78]
I have two IndexItems:
a) Lunch, StartDate: 01.02.2016 12:00, Daily
b) Dinner, StartDate: 01.01.2016 18:00, Weekly
When I retrieve the indexItems for a certain day, I get [b,a] which should be [a,b] because on this day b) is scheduled after a).

**Comment by lochmueller** [comment]
Hey @saneinsane 
I cannot rebuilt the problem. Do you have some other special configuration. Please run the calendarize scheduler task and check again. Please also check the Index table (valid data?)?
![test](https://cloud.githubusercontent.com/assets/3907126/16095404/aa3e342e-3344-11e6-8220-2dc9a792b506.png)

**Comment by saneinsane** [comment]
I ran the scheduler task again, problem stays. 
I use $indexRepository->findByTimeSlot() to get indexItems and they are still in wrong order. I reckoned that the repo default sort by [startdate, starttime] would take the start date of the schedule and not the current day it was fetched for.

**Comment by lochmueller** [comment]
Hmm... strange. Please check the records in the DB. "startdate, starttime" sorting is right and should result in the right order (see my screenshot above). I need same more technical information (debugging information), because I can not rebuild the problem...

Regards,
Tim

**Comment by saneinsane** [comment]
I logged date and time of two (wrong sorted) indexitems of one day (uid::startDate::startTime)
50055::2016-06-20::18:00:00
38896::2016-06-20::11:45:00
Below are the two db rows:
![bildschirmfoto 2016-06-20 um 08 40 35](https://cloud.githubusercontent.com/assets/9435220/16185274/eee9328c-36c2-11e6-9c5c-5044bb5b785e.png)
The startDate of the first entry is 1466377200 (20.06.2016 01:00:00) which is 1 hour later than the second entry (1466377200 aka 20.06.2016 00:00:00) so the indexItem-repository of course puts them in the wrong order.
Where could the shifted startDate come from?

**Comment by lochmueller** [comment]
That's strange. Both events are created via the backend? The index is built by this class: https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TimeTable/TimeTimeTable.php
Perhaps you can run some debugging in there? The scheduler tasks and also the "save record" action in the backend should result in the same process, that execute the TimeTable class.

Regards,
Tim

**Comment by saneinsane** [comment]
Problem was the timestamp saved by TYPO3 for the configuration start_date. I had to clear the date field, select the start date again and save the record - now all configuration start_dates are saved with utc +2 and the sorting works.
Maybe the Indexer could ensure that start_date (which is used as base for recurrences) is always cut to 00:00 to prevent such side effects?
Anyway, this behaviour was not caused by calendarize so you can close this one.
Regards,
rainer

**Comment by lochmueller** [comment]
OK. I close this issue. I hope that TYPO3 8.x will be fully UTC supported, so there are no problems in date calculation topics anymore ;)
