### ISSUE TITLE
Search (Filter) don't work

### ISSUE THREAD

**Issue by supercat1510** [lochmueller/calendarize#780]
I create two Content Elements with Search and Result, but the Result is empty.
I try different configs, but i get no Events in the Result.

Typo3 11.5.19
Calendarize 12.4.4

**Comment by lochmueller** [comment]
Hey @supercat1510 ,

I tested the current version with TYPO3 v12 and found the same problem. But only, at the moment, when no static typoscript of EXT:calendarize was included. There already was an error message generation, but no output in the result template. I add the flashMessage rendering, so you get an error now.

<img width="434" alt="Bildschirmfoto 2024-03-10 um 19 59 56" src="https://github.com/lochmueller/calendarize/assets/3907126/03e70263-7cee-4920-9821-663a4f7387f7">

Please check, if you include the static typoscript of the extension. I think this is the problem...

Regards,
Tim
