### ISSUE TITLE
Rework wizard description + icons

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#784]
The plugins items in the content create wizard need a new description, and if possible, also new icons (see screenshot below).

- [x] Create a description for each plugin
- [x] Reorder plugins (e.g. List+Detail first, then list, ...., something that makes sense)
- [ ] New icons

![calendarize-plugin-wizard](https://github.com/lochmueller/calendarize/assets/7593443/7489606a-4ca6-4b09-8f22-6af26c236f62)

Relevant files:
- [NewContentElement.tsconfig](https://github.com/lochmueller/calendarize/blob/5b7597ef1c4361efd2c59534fea072558f754235/Configuration/TsConfig/Page/Mod/Wizards/NewContentElement.tsconfig)
- [locallang.xlf](https://github.com/lochmueller/calendarize/blob/5b7597ef1c4361efd2c59534fea072558f754235/Resources/Private/Language/locallang.xlf)

**Comment by lochmueller** [comment]
I am no designer but...
... I split up the icons
... split up the descriptions
... reorder the items
... create two icon groups (for search&result and all the chronologically items)

I close this issue. Feel free to change the icons even more...
