### ISSUE TITLE
Latest release for TYPO3 v11 (v12.4.4) has PHP code deprecated in PHP 8.2: ${var} string interpolation deprecated

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#787]
`$indexerObject->logger->error("Unable to index ${$row['uid']}: " . $exception->getMessage());`

https://github.com/lochmueller/calendarize/blob/bff41ea4725a90d9b1f57d0a3baf26c7d59dca2c/Classes/Hooks/KeSearchIndexer.php#L144

This was already fixed in master, but not in latest v11 tag (12.4.4). Since master does not support v11, it looks like it might not get fixed in v11.

TYPO3 11 supports PHP 8.2 (and 8.3), see https://get.typo3.org/

calendarize supports ^8.1

Conclusion: should get fixed for latest calendarize version which supports TYPO3 v11.

## Impact

On development system with TYPO3 v11 (latest) and PHP 8.2, cli command `cache:flush` fails:

```
@php vendor/bin/typo3cms cache:flush

                                                                                                  
  [ ErrorReporting\DeprecationNotice ]                                                            
  Deprecated: Using ${expr} (variable variables) in strings is deprecated, use {${expr}} instead  
                                               
```

## Info about deprecation

PHP 8.2: ${var} string interpolation deprecated

https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

**Comment by lochmueller** [comment]
Hey @sypets ,
it is already fixed in the v11 branch: https://github.com/lochmueller/calendarize/commit/b109e0b9b181b7c68c89d04a9785682e75b1b67d
Current state: There will be no future TYPO3 v11 releases, except security related. Please switch to the v11-Branch: https://github.com/lochmueller/calendarize/tree/v11 
Regards,
Tim

**Comment by sypets** [comment]
Thanks! Will do that.
