### ISSUE TITLE
Cannot install Calendarize

### ISSUE THREAD

**Issue by Scopestyle** [lochmueller/calendarize#79]
**TYPO3 version 7.6.9
PHP Version 7.0**

When installing the latest version from Github it crashes the backend. The following error gets thrown:

> Uncaught TYPO3 Exception
> Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]])
> 
> Error thrown in file
> /html/typo3/typo3conf/ext/autoloader/Classes/Mapper.php in line 68.

Crashes as well with the latest version in the repository (Same 2.3.3 version, different error).

> Class 'HDNET\Calendarize\Register' not found
> 
> Error thrown in file
> /html/typo3/typo3conf/ext/calendarize/ext_localconf.php in line 14.

Is there a fix to get around this error?

**Comment by lochmueller** [comment]
The second error is a class loading problem. Please delete `typo3temp/autoload` or run `composer dumpautoload`. The first error is part of the autoloader extension and - I think - related to your PHP version. I will add a UnitTest for the Mapper in the next days/weeks to avoid PHP7 related errors...

**Comment by Hobokens** [comment]
I have the same error message with TYPO3 7.6.9 an PHP 7.0.4 and PHP 7.0.7. I use the newest versions (calendarize, autoloader) from github.

**Comment by Hobokens** [comment]
I checked it again with the TYPO3 7.6.10 and the newest calendarize version from github. There were no more errors.
#### Thanks for the great extension!

**Comment by lochmueller** [comment]
Ok... so I close this issue. If the "Wrong parameters for Exception" apears again, please run same debugging also...

Regards,
Tim
