### ISSUE TITLE
Enddate in Fullcalendar.io month view not correct

### ISSUE THREAD

**Issue by andreheuer** [lochmueller/calendarize#798]
Hello,
I would like to use Calendarize using the Fullcalendar.io mode for the month view.

However, I realized that most of the meetings are ending 1 day later then they should. Please find an example the in the screenshots:

Meeting in backend:
![image](https://github.com/lochmueller/calendarize/assets/10393020/3cc6ff47-bfb5-4a52-88d4-9e6be5626943)

Shown in the frontend:
![image](https://github.com/lochmueller/calendarize/assets/10393020/64a07035-06af-45c5-96a8-6af517a005fe)

JS sources:
![image](https://github.com/lochmueller/calendarize/assets/10393020/c6a42f8c-50f0-49f1-bd90-8bb714660923)

This seems to be related to the fix applied for #116 Most likely, this was now finally fixed in Fullcalendar.io?

I am using Typo3 12.4.12 and Calendarize 13.0.3

**Comment by lochmueller** [comment]
hey @andreheuer 

I updated moment.js and fullcalendar:
- https://github.com/lochmueller/calendarize/commit/562bc8337980811d968f5da4791a13b8d19d9c0f
- https://github.com/lochmueller/calendarize/commit/8324e368ef96518c38fdaedca773b96462d06796

Perhaps this will already fix the problem. I will check your usecase in the next days/weeks.

Regards,
Tim
