### ISSUE TITLE
Add support for multi language installations

### ISSUE THREAD

**Issue by mvoehringer** [lochmueller/calendarize#8]
I setup an website with multiple languages and need the option to create Events in all languages the website supports. Would be nice if calendarize supports the following scenarios:

 * Create events in the default language only
 * Create events in a non default language only 
 * Create events with localisation - default language plus translations 
 * Create events that are set to "All languages" should show up in all language.

**Comment by lochmueller** [comment]
Hey mvoehringer, the calendarize is based on the autoloader. And the autoloader support language handling. Do you have try your different wishes? Regards, Tim

**Comment by mvoehringer** [comment]
Hi Tim, 
yes, i tried all the cases with the default events of calendarize. Here are the results so far: 

 * Create events in the default language only 
    -> default language ok, but in the other language there is an empty record. 
 * Create events in a non default language only 
    -> default language shows an empty record, other language is ok
 * Create events with localisation - default language plus translations 
     -> the list shows the correct translation plus empty records for the other language
 * Create events that are set to "All languages" should show up in all language.
     -> Both languages looks good.

```
config.sys_language_overlay = hideNonTranslated
config.sys_language_mode = strict
```

**Comment by lochmueller** [comment]
It seems it is a problem of the "index" Layer, that do not resepct the languages of the original record. I will check this shortly...

**Comment by ON4R** [comment]
Hey Tim,
did you already look into this?

**Comment by lochmueller** [comment]
I built a test page and run a few tests. First enlightenment was, to deactive the Index configuration in real translations: https://github.com/lochmueller/calendarize/commit/802947fb3b87a3d14228cc9ad77ef5987234cdfa

Next steps will follow....

**Comment by on4r** [comment]
I would love to help but i don't really know where to start...
Shouldn't it apply the `_languageUid` from the **Event** onto the **Index** ?

**Comment by lochmueller** [comment]
My plan was/is....
- Remove the language in the Index Structure: https://github.com/lochmueller/calendarize/blob/master/Classes/Domain/Model/Index.php#L20
- Run DB compare
- Than the IndexRepository should respect the Language of the Index repository
- Add language settings to the Indexer process (like for enableFields): https://github.com/lochmueller/calendarize/blob/master/Classes/Service/IndexPreparationService.php#L53
- A lot of testing ;)

**Comment by lochmueller** [comment]
First steps are done. Please take a look into the current master...

**Comment by lochmueller** [comment]
Many parts of the l10n handling are part of the current master (next release). I close this issue... further task in separate issues...
