### ISSUE TITLE
Translating an event is broken in TYPO3 12.4

### ISSUE THREAD

**Issue by hannesbochmann** [lochmueller/calendarize#801]
When a event should be translated an exception pops up:

Field value of field "type" of database record with uid "7337" from table "tx_calendarize_domain_model_configuration" points to a "ds" key time but this key does not exist and there is no "default" fallback.

This exception might occur on a normal save, too.

I think this is because there are no secondary time tables configured.

TYPO3: 12.4.15
PHP: 8.2

**Comment by nhovratov** [comment]
Also happens when copying an event.
