### ISSUE TITLE
Please create new release for v11 - Exception in IndexerService when deleting a translation page with latest 12.4.4 for TYPO3 v11 (fixed in v11 branch)

### ISSUE THREAD

**Issue by sypets** [lochmueller/calendarize#805]
Can you please tag a new version for v11, due to following problem still existing in latest tag 12.4.4 but fixed in v11 branch: Exception when deleting a (translated) page with PHP 8.2.

IndexerService.php

1. branch v11:

`line 153:         if (VersionState::DELETE_PLACEHOLDER === ($rawRecord['t3ver_state'] ?? false)) {`

https://github.com/lochmueller/calendarize/blob/v11/Classes/Service/IndexerService.php#L153

2. latest tag for v11: [12.4.4](https://github.com/lochmueller/calendarize/releases/tag/12.4.4)

`line 153:     if (VersionState::DELETE_PLACEHOLDER === $rawRecord['t3ver_state']) {`

https://github.com/lochmueller/calendarize/blob/12.4.4/Classes/Service/IndexerService.php#L153

-----

I can use 11.5 branch, but others might run into this problem.

**Comment by lochmueller** [comment]
Hey @sypets 

Feel free to use the Branch with composer mode. There are no official old branches with releases. If you find more error, feel free to send pull requests to this branch (and main, if it is also a main problem).

I will close this issue.

Regards,
Tim
