### ISSUE TITLE
Exception in HDNET\Calendarize\Service\TcaService->getConfigurationGroupTitle()

### ISSUE THREAD

**Issue by Subjekt2Change** [lochmueller/calendarize#811]
En exception is thrown [here](https://github.com/lochmueller/calendarize/blob/master/Classes/Service/TcaService.php#L112) whenever the `BackendUtility::getRecord('tx_calendarize_domain_model_configurationgroup', $id)` the line above returns NULL. Exception: `PHP Warning: Trying to access array offset on value of type null`.
In my case this happened because the group the event was grouped to had been deleted.

My temporary fix:
`$groups[$key] = (isset($row) ? $row['title'] : '') . ' (#' . $id . ')';`
Or should the `$groups[$key]` be unset instead?

**Comment by lochmueller** [comment]
Hey @Subjekt2Change 
thanks for reporting. Fixed in current main branch.
Regards,
TIm
