### ISSUE TITLE
Exception in RecurrenceService

### ISSUE THREAD

**Issue by devmes** [lochmueller/calendarize#817]
In the class ‘HDNET\Calendarise\Service\RecurrenceService’
the method ‘getRecurrenceForNextMonth’ has the return value ‘\DateTime’, but it must have the value ‘\DateTime|false’, otherwise it can lead to an exception.

Exception:
‘Uncaught TYPO3 Exception HDNET\Calendarize\Service\RecurrenceService::getRecurrenceForNextMonth(): Return value must be of type DateTime, bool returned
thrown in file /var/www/html/vendor/lochmueller/calendarize/Classes/Service/RecurrenceService.php
in line 38’

**Comment by lochmueller** [comment]
Fixed via https://github.com/lochmueller/calendarize/pull/818
