### ISSUE TITLE
pi_flexform missing in BE (TYPO3 v10 / calendarize v7.3.0)

### ISSUE THREAD

**Issue by iamwebrocker** [lochmueller/calendarize#819]
Hi, 

I am currently migrating an old TYPO3 project from v8 -> v9 -> v10 -> v11 -> v12… 
I have sucessfully switched from cal to calendarize in v9, and now in v10 everything seems to work (events showing in FE, editors can create and modify events), but there is something strange with the content/plugin in the backend:
The instances that are already there and have been setup in v9 are working fine. But I cannot create new ones -- there are no flexforms any more, and I can't modify the existing ones. There's only the list_type select, and nothing else. There are no errors logged, and nothing (js)error-wise in the browser console.
I have attached some screenshots. The first shows a existing plugin in the "page" view, then the edit view and lastly the part where once more options - flexform - were visible below the list_type select.

![cal1](https://github.com/user-attachments/assets/13829d19-0152-41df-92ff-46324d4f0920)
![cal2](https://github.com/user-attachments/assets/31bc81b0-55d4-4b49-b8ba-379fec1d5559)
![cal3](https://github.com/user-attachments/assets/297ab7d6-038c-46dc-ae2c-256c649836f2)

I'm aware that I'm currently on an outdated TYPO3 (v10.4.37) and calendarize (7.3.0), and that there's no support anymore.
But since this in-between state is neccessary for the next step(s) in my update journey, hopefully someone can point me to what's missing here?

thanks,
tom

**Comment by iamwebrocker** [comment]
Updating to calendarize 12.4.4 (autoloader already at 7.4.4) and running DB compare and upgrade wizard resolved this. thank you.

**Comment by iamwebrocker** [comment]
![grafik](https://github.com/user-attachments/assets/35c417f4-75eb-47a2-bac8-ee154d4a3e94)
@lochmueller noch eine kurze frage; nachdem nun die flexforms da sind, maulen die bestehenden plugininstanzen rum, dass dieses feld nicht gesetzt ist, scheint aber aufs FE keine auswirkung zu haben.
fehlt mir da ein TS setting wert oder muss das in die flexforms rein, bzw könnte ich das über die DB fixen?
ähnliches ist bei den wiederholenden events, da vermisst es das counter_interval, das konnte ich aber via db machen.

**Comment by lochmueller** [comment]
@iamwebrocker Sorry... da kann ich im Detail nicht helfen, weil das scheinen ja alles alte Versionen zu sein. Würde behaupten, dass es "settings.configuration" schon immer gibt. Deshalb komisch, dass es nicht gesetzt ist.
