### ISSUE TITLE
TimeSelectionWizard not compatible with TYPO3 6.2?

### ISSUE THREAD

**Issue by tastendruecker** [lochmueller/calendarize#82]
When trying to enter a new Calendarize record set within TYPO3 6.2 I am getting a core exception: 

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1: PHP Catchable Fatal Error: Argument 2 passed to HDNET\Calendarize\UserFunction\TimeSelectionWizard::renderWizard() must be an instance of TYPO3\CMS\Backend\Form\Element\AbstractFormElement, instance of TYPO3\CMS\Backend\Form\FormEngine given in /typo3conf/ext/calendarize/Classes/UserFunction/TimeSelectionWizard.php line 27 | TYPO3\CMS\Core\Error\Exception thrown in file /typo3_src-6.2.17/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101. Requested URL: typo3/ajax.php?ajaxID=t3lib_TCEforms_inline%3A%3AcreateNewRecord&ajaxToken=448f7cdffd67c5f2eb2f92ae884961b489f6a0c9

Using TYPO3 7 LTS everything works fine.

Best regards
Tastendruecker

**Comment by lochmueller** [comment]
Hey Tastendruecker, thanks for the bug report. Bugfix in a few seconds ;)
