### ISSUE TITLE
"Wrong parameters for Exception" again

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#83]
Hi Tim,
I'm sorry I detected the problem again when trying to open the database analyzer in the install tool. (TYPO3 7.6.10, PHP 7.0.7)

Take a look at the screenshot.

Regards
Hobokens

![2016-08-08 20_53_42-](https://cloud.githubusercontent.com/assets/6764582/17511207/2cd993e4-5e22-11e6-975b-b75e761aa6ab.png)

**Comment by lochmueller** [comment]
I do not get the error right and a can not rebuild this error. One solution is to catch the throwable interface ( http://php.net/manual/en/class.throwable.php ) in this line: https://github.com/lochmueller/autoloader/blob/master/Classes/Service/SmartObjectInformationService.php#L211

But!!! Than the extension will work, but it is strange that PHP 7 do not create the user \Exception and throw an \Error class?!

Do you run same more debugging?

Regards,
Tim

**Comment by Hobokens** [comment]
I will check my installation on a local system here.

Here you have another screenshot when I try to call the detail view of calendarize (debugging on in install tool). MAybe it's helpful.
![2016-08-08 20_53_42-](https://cloud.githubusercontent.com/assets/6764582/17519978/548b7a2a-5e4e-11e6-97b2-90eb53ae6446.png)

Regards
Hobokens

**Comment by lochmueller** [comment]
Thanks to @sirdiego we found the problem. It is an "strange behaviour" in PHP7 with a 32-bit system. We change the length of the exception int-codes to fit into the 32-Bit range. Autoloader and Calendarize are fixed (in git master) and new versions are in TER in a few minutes...

Thanks for reporting...

**Comment by Hobokens** [comment]
Thanks for fixing!
