### ISSUE TITLE
Feature request: add location and organizer fields and views

### ISSUE THREAD

**Issue by andreaskastl** [lochmueller/calendarize#84]
I really like your extension and want to migrate from cal to calendarize events. Your fluid based templates are much better than the outdated templates in cal. The fluid based cal templates seem to be still incomplete resp. not working in 7.6 correctly.

One thing is currently missing in calendarize extension but important for me: similar to cal extension a location and organizer reference and related views should be provided in calendarize extension, too. 
My whish list:
- A reference to e.g. tt_address records for location and organizer should be integrated (to avoid separate address maintenance)
- A static text field (as fallback when no address record could be referenced) should be provided. For location it is currently available, but not for organizer
- A new location view (show address of location, related events in a list, include optionally a google map based on lat/long from address record)
- A new organizer view (similar: show address of organizer and related events in a list)

**Comment by lochmueller** [comment]
Hey @andreaskastl 

thanks for your wishes. All 4 points are related to the data structure. The data structure of events is not the main part of calendarize. That means, it is easy to build a own event Model (with many relation...) and register it to calendarize to use the calendar features.

I will check to extend the "example" Event of the calendarize a little bit more... Perhaps there is a sponsor for a smart integration...

Regards,
Tim

**Comment by lochmueller** [comment]
Add general organizer field to the default event model. Also add the output to the detail view.

Regards,
Tim

**Comment by ses2013** [comment]
It would be even more flexible if the "location" is NOT attachted to the event model but to the "calendarize" Index itself.
This way the same Event e.g. from a page could have different indecies with their own location.
Regard
Stefan
