### ISSUE TITLE
Hide pagination in list view

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#85]
It would be nice to have the pagination only if there is more than one page with events.

**Comment by lochmueller** [comment]
Hey @Hobokens 
this is a feature request for the core PaginateViewHelper, isn't it? ;)
Regards,
Tim

**Comment by Hobokens** [comment]
Hey Tim,
you're right. :-)

Regards
Hobokens

**Comment by r4fx** [comment]
check this workaround in CSS

```
.pagination li:first-of-type:last-of-type {
  display: none
}
```

**Comment by Hobokens** [comment]
nice idea - thanx!

Here a shorter version:

`.pagination li:only-of-type {
	display: none;
}`

**Comment by lochmueller** [comment]
Both are nice CSS Snippets. Thanks for sharing them here...
