### ISSUE TITLE
Category Filter only works with the Standard "Event" Model

### ISSUE THREAD

**Issue by on4r** [lochmueller/calendarize#87]
Because the tablename is hardcoded:
https://github.com/lochmueller/calendarize/blob/master/Classes/Slots/EventSearch.php#L92

If you want to use category filters with a custom model you have to change this entry in the core.

**Comment by lochmueller** [comment]
Hey @on4r ,

the structure of the events (and also the category option on the event) is independent of the EXT:calendarize. The complete EventSearch search class is related to the Event object that is shipped with EXT:calendarize. If you have a own model you have to register a own Slot-Class to change the behavior of the search... But I will restructure the tablename, so it is easier to use the EventSearch-class as base for a own Slot.

Regards,
Tim
