### ISSUE TITLE
Add option to use url params to filter by categories

### ISSUE THREAD

**Issue by r4fx** [lochmueller/calendarize#89]
Please add an option to filter events by category by using url param, like this is doing for example with `tx_calendarize_calendar[endDate]`

**Comment by lochmueller** [comment]
Hey @r4fx 
I need more details. There are several slots (findBySearch, getDefaultConstraints) to handle own criteria for your own models. Please build me a use case...
Regards,
Tim

**Comment by r4fx** [comment]
example, 
on the list of events each of items shows associated categories which are links, when I click on that link I want to filter displayed events by that category, so we need special url parameter and something inside code to achieve this. Excellent solution would be if we could use multiple categories with that special parameter, example url `http://example.com/index.php?id=95&tx_calendarize_calendar[categories]=4,6,5`

**Comment by lochmueller** [comment]
Hey @r4fx 
I added the location to the last commit. I do not have the time for the integration and testing at the moment. I wil check this in a few weeks again...
Regards,
Tim

**Comment by lochmueller** [comment]
Drop this task... please use the Slot by your own or create a pull request...
Regards,
Tim

**Comment by cabi** [comment]
I use the 'findBySearchPre'-slot to search for categories. It is real easy.
