### ISSUE TITLE
calendarize v 1.4 - error with coolURI

### ISSUE THREAD

**Issue by Hobokens** [lochmueller/calendarize#92]
Hi Tim,
with the newest calendarize from github and coolURI I get the following error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Using $this when not in object context | Error thrown in file /html/typo3/typo3conf/ext/calendarize/Classes/Service/Url/CoolUri.php in line 28. Requested URL: http://www.my_domain.org/termine.html`

I changed the CoolUriConf.xml as described in the manual.

**Comment by lochmueller** [comment]
Do you use this code and the error still exists?
`  <part>
    <parameter>tx_calendarize_calendar[@widget_0][currentPage]</parameter>
    <t3conv>1</t3conv>
  </part>
  <part>
    <parameter>tx_calendarize_calendar[index]</parameter>
    <userfunc>\HDNET\Calendarize\Service\Url\CoolUri->convert</userfunc>
  </part>`

**Comment by Hobokens** [comment]
Yes, I added the above code into the the section 
`<uriparts></uriparts>`
and the error still exists.

**Comment by lochmueller** [comment]
Please change your configuration to the "convertStatic" function and test it with the current master.... If the problem still exists, please reopen this issue or create a new one.

**Comment by Hobokens** [comment]
Thanks, the problem is solved for me.
Regards
Hobokens
