### ISSUE TITLE
Deviations possible?

### ISSUE THREAD

**Issue by sevensix** [lochmueller/calendarize#94]
One great thing about the cal-Extension is the possibility to add deviations to recurring events.
is there any possibility to add a deviation to recurring events?
That would be awesome.

**Comment by lochmueller** [comment]
Hey @sevensix 
You can create the recurring event first, then exclude same times, and create the new times configuration after that (all in one event). So it is easly configurable. The only point is, that you can exclude times only with exclude groups. Should we create a "Exclude Time" record, so you can exclude entries without creating a a exclude group first?
Regards,
Tim

**Comment by lochmueller** [comment]
I added a "time (exclude)" configuration to easily create the deviations in one event, without creating a configuration group first. More complex, but very flexible ;)

**Comment by sevensix** [comment]
how does this actually works? I have a recurring event but on one day i would like to not show this event. so i added a calendarize option with a exclude item. but the event is still showing up in the frontend. 
![calendarized](https://cloud.githubusercontent.com/assets/4035097/19355624/4b1653ca-916b-11e6-93b3-4bb68e0f194d.JPG)

**Comment by sevensix** [comment]
I tried to include the time(exclude) option. I have a recurring event and added an exclude time item but the event is still showing up in the FE (yes i cleared the cache). So how does it work? what did i wrong?
![calendarized](https://cloud.githubusercontent.com/assets/4035097/19355692/881a4894-916b-11e6-8c27-1a79ca6ba647.JPG)

**Comment by lochmueller** [comment]
Do you try to exclude the complete Day in the exclude configuration (checkbox: allday)?

**Comment by sevensix** [comment]
yes i tried that too, still the event of the 15.10 is visible in the FE
![cal2](https://cloud.githubusercontent.com/assets/4035097/19356801/4f299716-916f-11e6-8e3e-c9ba16c59a92.JPG)

**Comment by lochmueller** [comment]
Hey @sevensix 
the last patch should fix this issue.
Thanks for your bug report.

Regards,
Tim
